### ISSUE TITLE
need -v flag

### ISSUE THREAD

**Issue by henryhu712** [oclif/oclif#1024]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
The --version flag is working to show my command version information. But there is no -v flag.

What is the expected behavior?
------------------------------
Expect -v or -V is the short flag for --version.

**Comment by mdonnalley** [comment]
You can leverage the `additionalVersionFlags` property in the oclif section of your package.json to accomplish this. There's more about this in the [@oclif/core migration guide](https://github.com/oclif/core/blob/main/MIGRATION.md#restore--h--v-and-version) if you want to take a look.
