### ISSUE TITLE
Follow semver, keep track of supported Node versions better

### ISSUE THREAD

**Issue by jasonmobley** [oclif/oclif#1034]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
"oclif" package still lists Node v12 in "engines" config in package.json but it depends on @oclif/core@^1.20 which requires minimum of Node v14 since v1.13.0 and whose dist includes code that won't run on Node v12.

What is the expected behavior?
------------------------------
Keep track of your supported engines correctly. Deprecating a supported engine should be a breaking change.

**Comment by jasonmobley** [comment]
I understand support for Node 12 LTS has ended, but I'm dealing with a bunch of version pinning and resolutions nonsense to workaround oclif's very inconsistent versioning discipline.

**Comment by mdonnalley** [comment]
@jasonmobley Sorry for the inconvenience. We're following the practice you outlined now
