### ISSUE TITLE
`oclif readme` can't import Typescript files from other workspace package

### ISSUE THREAD

**Issue by adi-code** [oclif/oclif#1036]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

*bug*

What is the current behavior?
-----------------------------

EDIT: The example repo that presents this bug can be found at https://github.com/adi-code/npm-ts-workspaces-example

I recently migrated my CLI to `@oclif/core` according to https://github.com/oclif/core/blob/main/MIGRATION.md
Before that, I was using `oclif-dev readme` to generate README.md and it worked as expected.
After migration, I can't make `oclif readme` work the same. I'm using Typescript and npm workspaces registered under `@myworkspace` namespace, with the following packages (in `packages/`):
 - `cli`
 - `core`

My commands (from `@myworkspace/cli` package) import files from `@myworkspace/core` packages in the following way:
`import { Entity } from '@myworkspace/core/src/some-module/some-file';`
and the intention here is to import from Typescript file (from src/ not dist/, file some-file.ts).

And `oclif readme` is failing because there are errors like this:

```
(node:37619) [MODULE_NOT_FOUND] ModuleLoadError Plugin: @myworkspace/cli: [MODULE_NOT_FOUND]
require failed to load /home/adrian/repos/myworkspace/packages/cli/dist/commands/example/print-test.js:
Cannot find module '@myworkspace/core/src/some-module/some-file'
Require stack:
- /home/adrian/repos/myworkspace/packages/cli/dist/commands/example/print-test.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/module-loader.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/config/plugin.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/config/config.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/config/index.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/command.js
- /home/adrian/repos/myworkspace/node_modules/@oclif/core/lib/index.js
- /home/adrian/repos/myworkspace/node_modules/oclif/bin/run
```

What should I do to make it work as before migration? 
I feel like `ts-node` should be registered somewhere but I'm not sure where (and whether my suspicion is valid at all).

P.S. Imports like `import { Entity } from '@myworkspace/core/src/some-module/some-file';` were problematic for other reasons as well, as I needed to register `ts-node` in my `bin/run` script and set `tsnodeEnabled` so it reads files from `src/` (not from `dist/`, to not have to rebuild the CLI after every change when running `npx myworkspace-cli`):
```
#!/usr/bin/env node

const oclif = require('@oclif/core')
const path = require('path')
const project = path.join(__dirname, '..', 'tsconfig.json')
require('ts-node').register({
    transpileOnly: true,
    project,
});
oclif.settings.tsnodeEnabled = true;
oclif.run().then(require('@oclif/core/flush')).catch(require('@oclif/core/handle'))
```

Probably it's not the best solution, so I would be grateful for your suggestions here as well, before migration `npx myworkspace-cli` worked fine.

What is the expected behavior?
------------------------------
OS: `Linux .15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
oclif: `oclif/3.2.27 linux-x64 node-v16.17.0`

`oclif readme` works properly with TypeScript codebase as `oclif-dev readme` worked before migration

**Comment by mdonnalley** [comment]
`oclif readme` requires that the source code is compiled first - which we're not going to change. Auto-compilation is exceedingly difficult to get right given the wide variety of variables that go into it (e.g. ESM vs CJS, ts-node or node or tsx or bun, node 20 + ts-node + ESM don't play nicely together, etc...)
