### ISSUE TITLE
generator produces yarn-dependent project even when yarn was not selected

### ISSUE THREAD

**Issue by ianwremmel** [oclif/oclif#104]
I don't use yarn in my workflow and I'd prefer not to add it for one project. As such, I did not select yarn during the generator process yet it's referenced all over the generated build scripts and README.

**Comment by jdxcode** [comment]
Can you be more specific about where it is used in the build scripts?

**Comment by jdxcode** [comment]
got it: you mean the CI scripts. I've started work on this but it's not super straightforward. I might move nyc and nyc-config into the project to simplify the configuration (though this makes setting up the project take quite a bit longer)

**Comment by ianwremmel** [comment]
Is there something that makes using npm commands more difficult than yarn commands? Or is it ensuring the generator supports both makes this not very straightforward?

**Comment by jdxcode** [comment]
generating the template scripts gets very complex very quickly once there are more than 1 conditional involved. The semantic-release stuff in particular is pretty complex

**Comment by jdxcode** [comment]
where in the readme is it referenced? I'm not seeing anything in the [generated output](https://github.com/oclif/example-multi-ts)

**Comment by ianwremmel** [comment]
hmm, neither am I. I might have just been reading a diff too quickly when I reported the `README` bit. apologies for that.
