### ISSUE TITLE
CLA bot shows error message despite success

### ISSUE THREAD

**Issue by strophy** [oclif/oclif#1061]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Try to sign the CLA. Upon signing, the message `Could not sign the CLA, please contactoss-cla@salesforce.com` appears. Upon trying to sign again, the site says `You already signed the CLA on 2022-12-15`

What is the expected behavior?
------------------------------
Signing CLA should show user appropriate messages.

Firefox 107.0.1 on Fedora 37 x86

**Comment by RodEsp** [comment]
Hey @strophy, sorry about that. The CLA bot sometimes has hiccups and does weird things like that. I see that your PR has the correct label now so I'll go ahead and close this issue.
