### ISSUE TITLE
Cannot create version indexes .json file

### ISSUE THREAD

**Issue by mattbr0wn** [oclif/oclif#1062]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Potential bug

What is the current behavior?
-----------------------------
```
oclif promote --version [version#] --sha [sha]
```
works beautifully...copies all files and manifests into the stable channel within the defined s3 bucket.

```
oclif promote --version [version#] --sha [sha] --indexes
```
copies the first file and manifests into the stable channel, then errors with

```
TypeError: The "path" argument must be of type string. Received undefined
Code: ERR_INVALID_ARG_TYPE
```

There is no current .json index file in the s3 bucket.  I had a look at the code and it appears to be erroring here:

https://github.com/oclif/oclif/blob/09ace7d7ff2d328ba04552068e303e4d75760229/src/version-indexes.ts#L37

Additional context
------------------------------
oclif/3.2.31 darwin-arm64 node-v18.12.1

package.json
```
"oclif": {
    "bin": "openline",
    "dirname": "openline",
    "commands": "./dist/commands",
    "update": {
      "s3": {
        "host": "http://openline.sh.s3-website-us-east-1.amazonaws.com",
        "bucket": "openline.sh"
      }
    },
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-plugins",
      "@oclif/plugin-not-found",
      "@oclif/plugin-update"
    ],
```

**Comment by mshanemc** [comment]
oh, it's expecting a folder on the pjson.oclif.s3.config.  Adding that should get you going.

I'll make a better error message to check that prop before trying to use it.

**Comment by mattbr0wn** [comment]
Thanks, that unblocked me!
