### ISSUE TITLE
Support kebab and camelCase flags

### ISSUE THREAD

**Issue by ianwremmel** [oclif/oclif#107]
I'd like my cli to accept e.g. `--fail-fast` or `--failFast`, but I'd like to define that as `{ failFast: flags.boolean() }`. 

I've been trying to get this to work by overriding `Command#parse()`, but it seems like I need to do something at a deeper level.

**Comment by jdxcode** [comment]
sorry but for UX reasons I don't think this is a good idea. It makes it unclear which is the 'right' behavior and could make later migrations cause commands to stop working.

**Comment by wataruian** [comment]
Will this not be supported in the near future? I am seeing lots of CLIs implementing this. Is kebab-case not unix standard?
