### ISSUE TITLE
oclif pack:macos fails at pkgbuild command

### ISSUE THREAD

**Issue by shrutiburman** [oclif/oclif#1070]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Report a bug

What is the current behavior?
-----------------------------
When cmd oclif pack:macos is called, it fails at pkgbuild step. 

What is the expected behavior?
------------------------------
The package should have built successfully. 

Please mention your oclif and OS version.
oclif : v2
OS: macos-11 (Github Actions env)

Steps to reproduce: 
1. `oclif pack:macos`

Error:
```
oclif: gathering workspace for twilio to <path>
oclif: will build 2 targets in parallel
oclif: building target twilio-v5.0.0-aaaaaa-darwin-x64.tar.gz
oclif: copying workspace ./tmp/twilio ./tmp/darwin-x64/twilio
oclif: building target twilio-v5.0.0-aaaaaa-darwin-arm64.tar.gz
oclif: copying workspace ./tmp/twilio ./tmp/darwin-arm64/twilio
oclif: downloading node-v16.19.0-darwin-x64
oclif: downloading node-v16.19.0-darwin-arm64
oclif: extracting node-v16.19.0-darwin-arm64
oclif: extracting node-v16.19.0-darwin-x64
    Error: Command failed: pkgbuild  --root 
    <root_location>
    --component-plist 
    abc.plist 
    --identifier <twilio_identifier> --version 5.0.0 --install-location 
    /usr/local/lib/twilio-cli --scripts 
    <script_location> --sign 
    twilio-x.x.x.pkg
    Usage: pkgbuild [options] --root <root-path> [--component-plist 
    <plist-path>] <package-output-path>
    	Build a package from an xcodebuild destination root

    Usage: pkgbuild --analyze --root <root-path> <plist-output-path>
    	Create template component plist from an xcodebuild destination root

    Usage: pkgbuild [options] {--component <component-path>} 
    <package-output-path>
    	Build a package from one or more previously-built bundles

    See pkgbuild(1) for details.


    Code: 1
Error: Process completed with exit code 1.

    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

```

**Comment by cristiand391** [comment]
> Please mention your oclif and OS version.
> oclif : v2
> OS: macos-11 (Github Actions env)
> ...
>  oclif: building target twilio-v5.0.0-aaaaaa-darwin-arm64.tar.gz

oclif v2 doesn't build arm64 pkgs, you seem to be using at least v3.0.0, see:
https://github.com/oclif/oclif/releases?page=6

How are you calling `oclif pack:macos`? (npx, package.json scripts, `yarn run`, etc). I tried building `sfdx` locally (macos Big Sur) and it finished successfully:

repo: https://github.com/salesforcecli/sfdx-cli

```
➜  sfdx-cli git:(main) yarn oclif pack:macos --targets darwin-x64
yarn run v1.22.19
$ /Users/cdominguez/code/gh/sf/sfdx-cli/node_modules/.bin/oclif pack:macos --targets darwin-x64
oclif: gathering workspace for sfdx to /Users/cdominguez/code/gh/sf/sfdx-cli/tmp/sfdx
oclif: will build 1 targets in parallel
oclif: building target sfdx-v7.182.1-4c27817-darwin-x64.tar.gz
oclif: copying workspace ./tmp/sfdx ./tmp/darwin-x64/sfdx
oclif: downloading node-v18.12.1-darwin-x64
oclif: extracting node-v18.12.1-darwin-x64
✨  Done in 195.25s.
➜  sfdx-cli git:(main) yarn oclif --version
yarn run v1.22.19
$ /Users/cdominguez/code/gh/sf/sfdx-cli/node_modules/.bin/oclif --version
oclif/3.4.2 darwin-x64 node-v18.12.1
✨  Done in 0.67s.
➜  sfdx-cli git:(main)
```

**Comment by shrutiburman** [comment]
Yep, looks like I am using Oclif v3 to pack tarballs. 
The cmd I used was `npx oclif pack:macos` inside my CLI. It didn't work locally on my Mac Ventura too.

**Comment by cristiand391** [comment]
Can you try calling oclif using yarn and `macos-latest`? I tried locally with sfdx and npx and works so I suspect it's something with your cli.

Here's the workflow we use to pack a macos installer for sfdx:
https://github.com/salesforcecli/github-workflows/blob/main/.github/workflows/packUploadMac.yml

**Comment by AsabuHere** [comment]
Tried calling oclif with yarn and macos-latest. Still the same error persists
The commanda tried are

yarn oclif pack:macos and 
yarn oclif pack:macos-latest

**Comment by cristiand391** [comment]
@AsabuHere do you know if it started to fail after a change in your CLI?

**Comment by AsabuHere** [comment]
> @AsabuHere do you know if it started to fail after a change in your CLI?

It started failing without any new changes in CLI
