### ISSUE TITLE
calling `this.exit()` from a hook does nothing - regression in oclif 2+

### ISSUE THREAD

**Issue by vlukashov** [oclif/oclif#1083]
Do you want to request a ~feature~ or report a *bug*?
-----------------------------------------------------
**[bug]** This is a regression that we've run into when migrating from oclif 1.x to the latest oclif 3.5.

What is the current behavior?
-----------------------------
In a CLI generated with the latest `oclif` version, calling `this.exit()` in a hook does not stop the CLI execution:
```ts
import { Hook } from "@oclif/config";

const hook: Hook<"init"> = async function (this) {
  if (process.env.EXIT_ON_INIT) {
    this.log(">>> The CLI should exit NOW <<<");
    this.exit(0);
  }
};

export default hook;
```
⬇️
```bash
$ EXIT_ON_INIT=1 bin/dev help
```
⬇️
```
>>> The CLI should exit NOW <<<
oclif example Hello World CLI

VERSION
  oclif-hello-world/0.0.0 darwin-arm64 node-v16.18.0
...
```

What is the expected behavior?
------------------------------
No further commands should be executed if a hook calls `this.exit()`
```bash
$ EXIT_ON_INIT=1 bin/dev help
>>> The CLI should exit NOW <<<
$
```

---
It looks like this issue was introduced into `@oclif/core` by https://github.com/oclif/core/pull/253. And when `@oclif/core` replaced `@oclif/config` in the generated CLIs with the `oclif` 2.0 release this issue started affecting users.

Please let me know if you are ready to review and accept a PR fixing this issue.

Meanwhile, a workaround is to use `process.exit()` instead of `this.exit()`.

**Comment by vlukashov** [comment]
Just found the same issue reported in `@oclif/core`: https://github.com/oclif/core/issues/515.
If 'breaking' `this.exit()` in hooks was a conscious decision I suggest to remove this method from the hooks context altogether.

**Comment by jmealo** [comment]
This is concerning for folks looking to start LTS projects using `oclif`. I'm looking forward to understand the decision making process here.
