### ISSUE TITLE
Does oclif include any mechanism for bash_completion?

### ISSUE THREAD

**Issue by sagarpanchal** [oclif/oclif#1086]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Request a feature

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

**Comment by mdonnalley** [comment]
@sagarpanchal Yes, please see our [autocomplete plugin](https://github.com/oclif/plugin-autocomplete)
