### ISSUE TITLE
CommonJS commands don't work

### ISSUE THREAD

**Issue by mildmojo** [oclif/oclif#1093]
CommonJS commands don't work after following the [instructions](https://oclif.io/docs/esm) for making oclif work with CommonJS. As a side note, I couldn't find any documented flags for switching oclif's generators to output CommonJS instead of Typescript; I assume there's no generator support.

I can't tell if the problem is with the code or the instructions.

## Expected
Running `./bin/dev.js test` should run the command in `src/commands/test.js`.

```bash
$ ./bin/dev.js test
Test success!
```

## Actual
Running `./bin/dev.js test` doesn't detect the command in `src/commands/test.js` and exits with an error.

```bash
$ ./bin/dev.js test
Error: command test not found
    at Config.runCommand (/home/user/myapp/node_modules/@oclif/core/lib/config/config.js:266:19)
    at async Module.execute (/home/user/myapp/node_modules/@oclif/core/lib/main.js:136:5)
    at async /home/user/myapp/bin/dev.js:5:3
```

## Steps to reproduce
1. Run `npx oclif generate myapp` to generate a scaffolded CLI app.
2. Verify it runs using `./bin/run` and `./bin/dev`.
3. Add the following files:

`tsconfig.json` (from https://oclif.io/docs/esm)

```javascript
{
  "compilerOptions": {
    "module": "ES2020",
    "moduleResolution": "node"
  },
  "ts-node": {
    "esm": true
  }
}
```

`bin/run.js` (from https://oclif.io/docs/esm but with `__dirname` fix)

```javascript
#!/usr/bin/env node
// eslint-disable-next-line node/shebang
(async () => {
  const oclif = await import('@oclif/core')
  // Instructions have an error here, suggesting import.meta.url
  // instead of __dirname, which is invalid for CommonJS modules.
  await oclif.execute({type: 'cjs', dir: __dirname})
})()
```

`bin/dev.js` (from https://oclif.io/docs/esm)

```javascript
#!/usr/bin/env node
// eslint-disable-next-line node/shebang
(async () => {
  const oclif = await import('@oclif/core')
  await oclif.execute({type: 'cjs', development: true, dir: __dirname})
})()
```

`src/commands/test.js`

```javascript
const {Command, Flags} = require('@oclif/core');

class Test extends Command {
  async run() {
    console.log('Test success!');
  }
}

module.exports = Test;
```

4. Run `./bin/dev.js test` to try the new command.
5. Observe that the command fails:

```bash
$ ./bin/dev.js test
Error: command test not found
    at Config.runCommand (/home/user/myapp/node_modules/@oclif/core/lib/config/config.js:266:19)
    at async Module.execute (/home/user/myapp/node_modules/@oclif/core/lib/main.js:136:5)
    at async /home/user/myapp/bin/dev.js:5:3
```

## Versions

```bash
$ npx oclif --version
oclif/3.6.1 linux-x64 node-v16.19.0

$ yarn --version
1.22.19
```

**Comment by mdonnalley** [comment]
>CommonJS commands don't work after following the [instructions](https://oclif.io/docs/esm) for making oclif work with CommonJS

@mildmojo Those instructions are for converting your CLI (which is written with CommonJS) to ESM. So if you want to use CommonJS commands then there is no further modifications required after generating the CLI.

But maybe I'm misunderstanding your issue?

**Comment by mildmojo** [comment]
Oh, since the project generator assumes Typescript, I assumed those instructions were for converting your Typescript CLI to ESM/CJS.

My core issue is starting a new oclif project with CommonJS instead of Typescript. I'm trying to establish a development loop where I can edit the code and execute it without needing a build step, like I can on another oclif 1.x project I maintain.

I tried the naive thing first, which was to generate a new project, add a command, and run it with `./bin/dev` (per [your comment on #905](https://github.com/oclif/oclif/issues/905#issuecomment-1216893398)), but it didn't work. 

```bash
$ npx oclif generate myapp
...
Created myapp in /home/user/myapp

$ cd myapp

$ cat > src/commands/test.js << EOF
const {Command, Flags} = require('@oclif/core');

class Test extends Command {
  async run() {
    console.log('Test success!');
  }
}

module.exports = Test;
EOF

$ ./bin/dev test
(node:3813682) [MODULE_NOT_FOUND] ModuleLoadError Plugin: myapp: [MODULE_NOT_FOUND] require failed to load /home/user/myapp/dist/commands/test: Cannot find module '/home/user/myapp/dist/commands/test'
Require stack:
- /home/user/myapp/node_modules/@oclif/core/lib/module-loader.js
- /home/user/myapp/node_modules/@oclif/core/lib/help/util.js
- /home/user/myapp/node_modules/@oclif/core/lib/help/formatter.js
- /home/user/myapp/node_modules/@oclif/core/lib/help/command.js
- /home/user/myapp/node_modules/@oclif/core/lib/help/index.js
- /home/user/myapp/node_modules/@oclif/core/lib/flags.js
- /home/user/myapp/node_modules/@oclif/core/lib/cli-ux/styled/table.js
- /home/user/myapp/node_modules/@oclif/core/lib/cli-ux/styled/index.js
- /home/user/myapp/node_modules/@oclif/core/lib/cli-ux/index.js
- /home/user/myapp/node_modules/@oclif/core/lib/command.js
- /home/user/myapp/node_modules/@oclif/core/lib/index.js
- /home/user/myapp/bin/dev
module: @oclif/core@2.0.7
task: toCached
plugin: myapp
root: /home/user/myapp
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Error: command test not found
    at Config.runCommand (/home/user/myapp/node_modules/@oclif/core/lib/config/config.js:266:19)
```

**Comment by mildmojo** [comment]
I repeated the test in my last comment using oclif v3.11.3, and now it works with a CommonJS command.

```bash
$ npx oclif generate myapp
...

$ cd myapp

$  cat > src/commands/test.js << EOF
const {Command, Flags} = require('@oclif/core');

class Test extends Command {
  async run() {
    console.log('Test success!');
  }
}

module.exports = Test;
EOF

$ ./bin/dev test
Test success!
```
