### ISSUE TITLE
Global flags are not respected

### ISSUE THREAD

**Issue by Disane87** [oclif/oclif#1100]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
*bug* 

What is the current behavior?
-----------------------------
I have two classes, one base class with general flags (log path etc.) and one with specific flags (credentials for services).

What is the expected behavior?
------------------------------
The globals flags and the specific flags should be merged like you've described in your docs: https://oclif.io/docs/global_flags

Actually this isn't working and I don't know why.

My base class:
```ts
import { Command, Flags, Interfaces } from '@oclif/core';
import winston from 'winston';
import { createLogger } from './commands/scrape/amazon/helpers/logger.helper';
import { LogLevel } from './loglevel';


export type Flags<T extends typeof Command> = Interfaces.InferredFlags<typeof BaseCommand['globalFlags'] & T['flags']>

export abstract class BaseCommand<T extends typeof Command> extends Command {
    // add the --json flag
    static enableJsonFlag = true

    protected logger: winston.Logger = null;

    //define flags that can be inherited by any command that extends BaseCommand
    static globalFlags = {
        LogLevel: Flags.enum<LogLevel>({
            summary: 'Specify level for logging.',
            options: Object.values(LogLevel),
            default: LogLevel.info
        }),

        debug: Flags.boolean({ char: `d`, default: true }),
        logPath: Flags.string({ char: `l`, description: `Log path`, default: './logs/' })

    }

    protected flags!: Flags<T>;

    public async init(): Promise<void> {
        await super.init()
        const { flags } = await this.parse(this.constructor as Interfaces.Command.Class)
        this.flags = flags;

        this.logger = createLogger(this.flags?.logLevel || LogLevel.info, this.flags?.logPath || './logs/');

        this.logger.info(`Got flags for plugin ${this.id} -> ${JSON.stringify(flags, null, 4)}`);
    }

    protected async catch(err: Error & { exitCode?: number }): Promise<any> {
        // add any custom logic to handle errors from the command
        // or simply return the parent class error handling
        return super.catch(err)
    }

    protected async finally(_: Error | undefined): Promise<any> {
        // called after run and catch regardless of whether or not the command errored
        return super.finally(_)
    }
}
```

My extended class: 
```ts

import { Flags } from "@oclif/core";
import * as Base from "../../../base.class";

export default class Amazon extends Base.BaseCommand<typeof Amazon> {
    static description = `Scrapes amazon invoices`;
    static summary = 'Used to get invoices from amazon';

    static examples = [
        `<%= config.bin %> <%= command.id %>`,
    ];

    static flags = {
        username: Flags.string({ char: `u`, description: `Username`, required: true, env: "AMAZON_USERNAME" }),
        password: Flags.string({ char: `p`, description: `Username`, required: true, env: "AMAZON_PASSWORD" }),
        fileDestinationFolder: Flags.string({ aliases: [`fileDestinationFolder`], default: `./data/`, description: `Amazon top level domain`, env: "FILE_DESTINATION_FOLDER" }),
        fileFallbackExentension: Flags.string({ aliases: [`fileFallbackExentension`], default: `.pdf`, description: `Amazon top level domain`, env: "FILE_FALLBACK_EXTENSION" }),
        tld: Flags.string({ char: `t`, description: `Amazon top level domain`, default: `de`, env: "AMAZON_TLD" }),
        yearFilter: Flags.integer({ aliases: [`yearFilter`], description: `Filters a year`, env: "YEAR_FILTER" }),
        pageFilter: Flags.integer({ aliases: [`pageFilter`], description: `Filters a page`, env: "PAGE_FILTER" }),
        onlyNew: Flags.boolean({ aliases: [`onlyNew`], description: `Gets only new invoices`, env: "ONLY_NEW", default: false }),
    };

    public async run(): Promise<void> {

        for (const [flag, value] of Object.entries(this.flags)) {
            this.log(`${flag}: ${value}`);
        }

        const options = this.flags;

        ...
    }
}
```

Specific to this code I would expect that the flags `LogLevel` `debug` and `logPath` would be available in the extended class, but thats not the case. Am I missing something? 

At the `init()` of the base class these three flags are always null, why?

**Comment by Disane87** [comment]
> @Disane87 thanks for the issue. What version of `@oclif/core` are you currently using? If you're on v2, you'll need to rename `globalFlags` to `baseFlags`
> 
> For context: https://github.com/oclif/core/blob/main/MIGRATION.md#flags

Oh I guess thats the solution. Will check that and report back :)

**Comment by mdonnalley** [comment]
@Disane87 using the example from the docs,

```typescript
export abstract class BaseCommand<T extends typeof Command> extends Command {
  // add the --json flag
  static enableJsonFlag = true

  // define flags that can be inherited by any command that extends BaseCommand
  static baseFlags = {
    'log-level': Flags.custom<LogLevel>({
      summary: 'Specify level for logging.',
      options: Object.values(LogLevel),
      helpGroup: 'GLOBAL',
    }),
  }

  protected flags!: Flags<T>
  protected args!: Args<T>

  public async init(): Promise<void> {
    await super.init()
    const {args, flags} = await this.parse({
      flags: this.ctor.flags,
      baseFlags: (super.ctor as typeof BaseCommand).baseFlags,
      args: this.ctor.args,
      strict: this.ctor.strict,
    })
    this.flags = flags as Flags<T>
    this.args = args as Args<T>
  }
}
```

I'm able to access the flags defined by both the parent and child classes from within the parent's `init` method

One thing I noticed in the code you provided is that `LogLevel` is in TitleCase in the flag definition but you're trying to access it with camelCase, `flags.logLevel` - so perhaps that's where the issue is?

If you're still running into problems, it would be super helpful if you could create a new repository that recreates the issue(s) so that I can more easily debug it.

**Comment by Disane87** [comment]
Thank you @mdonnalley! I've donme a little sample which demonstrates my issue. The example is really just broken down to the smallest and simplest.

https://github.com/Disane87/oclif-issue-baseflags/

**Comment by mdonnalley** [comment]
@Disane87 Thanks for the repo - super helpful!

If you change the `target` in your tsconfig.json from ES2022 to ES2021 it'll work as expected.

We'll need to investigate more into what's causing it to not work with ES2022 but in the meantime you should be unblocked

**Comment by Disane87** [comment]
Thank you for the fast help! Never thought this would be such a problem

**Comment by jasonk** [comment]
The reason that this doesn't work when targeting ES2022 is because the base `Command` class has static accessors for properties like `flags` and `baseFlags`.  With ES2022 static property declarations are natively supported, so if you have a class like this, for example:

```typescript
export abstract class BaseCommand extends Command {
  static enableJsonFlag = true
  static baseFlags = { ... }
```
When targeting ES2022 it gets emitted just like that, and when the code is interpreted those properties get added to the class with `Object.defineProperty`, so they *replace* those  accessors instead of triggering them.

In ES2021 those declarations aren't natively supported, so the class gets transpiled like this, and the accessors get used:

```javascript
export class BaseCommand extends Command {}
Command.enableJsonFlag = true;
Command.baseFlags = { ... };
```

If you still want to target ES2022 you can make it work by replacing all your static property declarations with a static initialization block:

```typescript
export abstract class BaseCommand extends Command {
  static {
    this.enableJsonFlag = true;
    this.baseFlags = { ... };
  }

```

**Comment by bastiankistner** [comment]
@jasonk your comment should be highlighted on the website. I spent almost a day trying to figure out how to display and use global/base flags and why certain parts are throwing. Changed it to ES2021, which is totally fine, and now I can finally start getting my job done.
