### ISSUE TITLE
Getting all flags and their env variables

### ISSUE THREAD

**Issue by Disane87** [oclif/oclif#1102]
Feature request / help
-----------------------------------------------------
For a project I need to get all flags (with plugins) and their env variables to show them in a list or generate an example .env.

Is this possible of the box?

**Comment by mshanemc** [comment]
(assuming you have oclif/plugin-commands installed) 

`mycli commands --json`

**Comment by Disane87** [comment]
Works like a charm, thank you @mshanemc

**Comment by Disane87** [comment]
At the first glance it works like a charm but at the second I discovered the flags array doesn't contain the `env` property of the flag @mshanemc so this approach wouldn't fit my needs
