### ISSUE TITLE
Packaging and Publishing binded to S3

### ISSUE THREAD

**Issue by xyNNN** [oclif/oclif#111]
Hey folks,

at first I would like to thank you to build something awesome like oclif, I like it very much!
Currently the packaging and publishing process is hard-wired and cannot be changed. 

Is there a possibility to pack and create a pkg installer (tarball, win, or deb package) without the binding to AWS S3?

Thanks in advance!

**Comment by jdxcode** [comment]
of course you can package an installer without using S3. It's only the publishing steps that require S3

**Comment by xyNNN** [comment]
But the pack process requires the configuration for a S3 bucket in the package.json

`oclif-dev: gathering workspace for deepkit-cli to /Users/user/Projects/Project-A/oclif-cli/tmp/oclif-cli
npm notice
npm notice 📦  oclif-cli@1.0.0
npm notice === Tarball Contents ===
npm notice 2.0kB package.json
npm notice 1.0kB .oclif.manifest.json
npm notice 1.7kB README.md
npm notice 122B  bin/run
npm notice 31B   bin/run.cmd
npm notice 152B  lib/commands/app.d.ts
npm notice 929B  lib/commands/app.js
npm notice 259B  lib/commands/init.d.ts
npm notice 1.4kB lib/commands/init.js
npm notice 153B  lib/commands/jobs.d.ts
npm notice 662B  lib/commands/jobs.js
npm notice 285B  lib/commands/login.d.ts
npm notice 1.2kB lib/commands/login.js
npm notice 289B  lib/commands/run.d.ts
npm notice 6.5kB lib/commands/run.js
npm notice 460B  lib/core.d.ts
npm notice 1.5kB lib/core.js
npm notice 813B  lib/home.d.ts
npm notice 2.5kB lib/home.js
npm notice 38B   lib/index.d.ts
npm notice 149B  lib/index.js
npm notice 885B  lib/model/job.d.ts
npm notice 1.5kB lib/model/job.js
npm notice 245B  lib/services/cli.socket.d.ts
npm notice 491B  lib/services/cli.socket.js
npm notice 273B  lib/services/job.socket.d.ts
npm notice 374B  lib/services/job.socket.js
npm notice 1.6kB lib/services/socket.d.ts
npm notice 5.8kB lib/services/socket.js
npm notice === Tarball Details ===
npm notice name:          oclif-cli
npm notice version:       1.0.0
npm notice filename:      oclif-cli-1.0.0.tgz
npm notice package size:  8.7 kB
npm notice unpacked size: 33.4 kB
npm notice shasum:        c2e9f45157fd5837cb42e8ea1f665f8600c3c0ac
npm notice integrity:     sha512-LgQWq3PvCCGee[...]Lf2bbA3vbp4+w==
npm notice total files:   29
npm notice
TypeError: Cannot read property 's3' of undefined`

**Comment by jdxcode** [comment]
ah right, I put a patch in for this but keep in mind without specifying a host or s3 bucket the CLI the users download will have to be reinstalled if users want to update it

**Comment by jdxcode** [comment]
The host can be any host though, doesn't have to be S3.

**Comment by xyNNN** [comment]
Awesome, thank you very much @jdxcode! Will you release a path version for this issue, so I don't have to require the dev-master?

**Comment by jdxcode** [comment]
All these repos use semantic-release so as soon as CI is built it'll cut a release
