### ISSUE TITLE
remove either node_modules or yarn 

### ISSUE THREAD

**Issue by sasha-firsov-bs** [oclif/oclif#1113]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
by running `npx oclif generate my-cli` and selecting `npm` the package.json contains `yarn` as part of `package.json`
```json
    "posttest": "yarn lint",
    "prepack": "yarn build && oclif manifest && oclif readme",
```
When selecting the `yarn` the `npx` command still keeps the `node_modules` forlder inside of project with all dependencies.
Which make a confusion what kind of project been created: yarn or npm?

What is the expected behavior?
------------------------------
The `yarn` in `package.json` replaced with `npm` equivalent.

`oclif/3.6.5 wsl-x64 node-v18.13.0`

OS: Ubuntu on WSL2
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
oclif and OS version.
```

**Comment by mdonnalley** [comment]
@sasha-firsov-bs Thanks for posting the issue. Having `yarn` inside the scripts for npm based CLIs is definitely a bug

Regarding `node_modules`, oclif still assumes yarn v1 which uses `node_modules` so that should still be there even when you select yarn

**Comment by sasha-firsov-bs** [comment]
@mdonnalley , is it possible to test `yarn` major version and decomission `node_modules` for version >1 ?
