### ISSUE TITLE
Drop dependency on `yosay`

### ISSUE THREAD

**Issue by mcmxcdev** [oclif/oclif#1118]
I want to request a *feature*
-----------------------------------------------------

What is the current behavior?
-----------------------------

Oclif depends on `yosay` but its flagged as unmaintained by Socket.dev: https://socket.dev/npm/package/yosay

`yosay` itself then also depends on problematic packages like https://socket.dev/npm/package/pad-component, which is functionality in JS that can be done without a library nowadays.

What is the expected behavior?
------------------------------
Replace old dependencies which are not needed anymore with modern ones or drop them completely.

**Comment by mdonnalley** [comment]
Closed by https://github.com/oclif/oclif/pull/1163
