### ISSUE TITLE
"frame.getFileName is not a function" error when passing `-h` to template hello command

### ISSUE THREAD

**Issue by mattmazzola** [oclif/oclif#112]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
I just created brand new cli with multi command setup such as:
```
npx oclif multi test01
cd test01
./bin/run hello -h
```

What is the expected behavior?
------------------------------
Windows 10 x64
Oclif: 
```
"dependencies": {
    "@oclif/command": "^1.4.20",
    "@oclif/config": "^1.6.17",
    "@oclif/plugin-help": "^1.2.10"
  },
```

See error below. Notice the full `--help` works fine, but the shorter alias `-h` shows some error message.

![image](https://user-images.githubusercontent.com/2856501/39677276-02083134-512d-11e8-8aca-40eb5ac57434.png)

**Comment by jdxcode** [comment]
this is an issue with ts-node and node 10.0.0: https://github.com/nodejs/node/issues/20258
