### ISSUE TITLE
infected with virus?

### ISSUE THREAD

**Issue by linojon** [oclif/oclif#1121]
Hello. I created a windows installer (```oclif pack win``` on WSL Ubuntu), and uploaded the exe to a google drive. 
Then on another machine, I tried to download and run it, and get a message from Windows Defender that the file "is infected with a virus". 
If it is infected, then why/how do i prevent it?
if its not, then how do i prevent this message?
Thanks for any help.

**Comment by peternhale** [comment]
@linojon Were you given any indication of which virus was identified  by Windows Defender?

**Comment by linojon** [comment]
not offhand, i'll try it again. I also see that it says the file is from an "unknown publisher", dont know if thats related on separate, how do i specify the publisher?

**Comment by mdonnalley** [comment]
@linojon you can specify the publisher by setting up windows code signing

To do this you need to provide oclif with three things,
1. a name
2. A windows .pfx file that oclif can pass to [osslsigncode](https://github.com/mtrojnar/osslsigncode)
3. A windows signing password that oclif can pass to osslsigncode

The name and .pfx file are specified in your CLI's package.json, [for example](https://github.com/salesforcecli/cli/blob/main/package.json#L101):

```json
"oclif": {
  "windows": {
      "name": "Salesforce CLI",
      "keypath": "/tmp/windows-signing.pfx"
    }
}
```

The windows signing password is provided via a name spaced `WINDOWS_SIGNING_PASS` environment variable (for example, if your cli is called `foo`, the env var would be `FOO_WINDOWS_SIGNING_PASS`) that should be set when running `oclif pack win`.

For reference, here's [the code that handles windows signing](https://github.com/oclif/oclif/blob/main/src/commands/pack/win.ts#L273) 

As far as obtaining a cert is concerned, I suggest following the [instructions](https://github.com/mtrojnar/osslsigncode#usage) provided by osslsigncode
