### ISSUE TITLE
Dynamic flags?

### ISSUE THREAD

**Issue by linojon** [oclif/oclif#1123]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
flags are declared static.
Unrecognized flags are interpreted as unrecognized args.

What is the expected behavior?
------------------------------
Is there a way to allow arbitrary flags? eg mycli --foo=bar
And/or constrain the list of known flags at runtime?
Likewise, add dynamic flags to the help messages.

**Comment by mdonnalley** [comment]
A possible solution for this is described here: https://github.com/oclif/oclif/issues/1154

Otherwise, we do not currently have the bandwidth to implement a dynamic flags feature
