### ISSUE TITLE
Bug: eslint - typescript support for 4.9.5

### ISSUE THREAD

**Issue by abcdefghiraj** [oclif/oclif#1125]
Do you want to request a *feature* or report a *bug*?
------------------------------
Bug

What is the current behavior?
------------------------------
`oclif generate mycli`
`yarn/npm lint`

```sh
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.9.5

Please only submit bug reports when using the officially supported version.
```

What is the expected behavior?
------------------------------
Newly generated project should not have any warnings.

oclif version : latest (3.7.0 ?)
macOS 13.2.1

**Comment by so1ve** [comment]
This is not a bug, it is a typescript-eslint warning. It does not affect the functionality. To resolve just update your dependencies

**Comment by abcdefghiraj** [comment]
@so1ve I understand that it is not a blocking bug, just a warning. When a software says it is production ready, the expectation is a clean output with no warnings.

**Comment by so1ve** [comment]
Ah, I see. It would be great if oclif update the dependencies in the template.
