### ISSUE TITLE
how to remove "See code" from readme?

### ISSUE THREAD

**Issue by linojon** [oclif/oclif#1128]
hi, is there an easy way to prevent ```oclif readme```from generating the lines with "See code:..." ?

**Comment by cristiand391** [comment]
Hi @linojon 👋🏼 

`oclif readme` will generate that section only if you have the usage/commands/toc tags.

```
oclif readme --help
adds commands to README.md in current directory

USAGE
  $ oclif readme --dir <value> [--multi] [--aliases]

FLAGS
  --[no-]aliases  include aliases in the command list
  --dir=<value>   (required) [default: docs] output directory for multi docs
  --multi         create a different markdown page for each topic

DESCRIPTION
  adds commands to README.md in current directory
  The readme must have any of the following tags inside of it for it to be replaced or else it will do nothing:
  # Usage
  <!-- usage -->
  # Commands
  <!-- commands -->
  # Table of contents
  <!-- toc -->

  Customize the code URL prefix by setting oclif.repositoryPrefix in package.json.
```

**Comment by linojon** [comment]
Yes thanks I realize that. Im including these tags and want the Usage, Description etc sections. But as a customer facing documentation i do not want the last line the gives a link into my code.

**Comment by linojon** [comment]
Eg

"See code: dist/commands/build.ts"

**Comment by cristiand391** [comment]
Ah, I see. I don't think there's a way to disable just that part but just looked at one of my plugins and I'm not getting that in my README:
https://github.com/cristiand391/sf-plugin-api

I'll check back on Monday 👍🏼

**Comment by adamu** [comment]
Setting `repository` in `package.json` to a full URL, rather than (an presumed GitHub) `owner/repo` string seems to remove the code links - and corresponds with @cristiand391's example. I'm not sure if this is by design though.

**Comment by cristiand391** [comment]
I was looking into this yesterday and found the readme doesn't include the "See code" section in my plugin because of a bug in how oclif is getting the command id, here it splits it by `:`:
https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L224

but I set spaces as a topic sep here:
https://github.com/cristiand391/sf-plugin-api/blob/main/package.json#L71.

@adamu I'm not sure if that's correct, but after looking at the code in oclif it seems there are a few cases where you can end up in this scenario.

**Comment by cristiand391** [comment]
Hey all, sorry for the late reply.

I opened a PR to fix `oclif readme` missing the `See code` block in plugins using spaces as the topic separator.

For the original question about removing "See code" from readme, you can follow the suggestion from @adamu and set `pjson.repository` to a full URL or omit it, `oclif readme` will skip it if it's not defined:
https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L210-L211
