### ISSUE TITLE
Oclif's bin/dev is not able to expand tsconfig paths and fails

### ISSUE THREAD

**Issue by jsoneaday** [oclif/oclif#1135]
Do you want to request a *feature* or report a *bug*?
This is a feature request

What is the current behavior?
My app uses tsconfig paths like @mypath: "../../path". But when running bin/dev I get an error like this
(node:7863) [MODULE_NOT_FOUND] ModuleLoadError Plugin: @my-app: [MODULE_NOT_FOUND] require failed to load my-app/src/commands/config/chains/use.ts: Cannot find module '@lib/base'

If the current behavior is a bug, please provide the steps to reproduce.
Current behavior is not a bug

What is the expected behavior?
It appears that bin/dev uses ts-node and triggers a compile, but typescript is not expanding the paths for require imports, so if a secondary script could run that does that it would be great.
I tried switching my package to be a module and use es modules, but that fails too because I get an error that bin/dev needs a file extension. This is the error TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for my-app/bin/dev. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file my-app/package.json caused this "type":"module" context. Try changing my-app/bin/dev to have a file extension
I also tried tsconfig-paths but that does not work because bin/dev does not allow me to inject the -r tsconfig-paths/register when ts-node gets triggered (setting it on the node line inside dev.cmd is ignored)

Please mention your oclif and OS version.
oclif 2.5.2
Mac 13.3 m1
Typescript 5.0.3

**Comment by jsoneaday** [comment]
If I could do something like this in the dev file, to get tsconfig-paths working would be nice

`require('ts-node').register({project}).register({'tsconfig-paths/register'})`

**Comment by kaushals-mecha** [comment]
Install `tsconfig-paths`

Add below changes in dev and run 
```
const project = path.join(__dirname, '..', 'tsconfig.json');

require('ts-node').register({ project });
require('tsconfig-paths').register();
```

**Comment by mdonnalley** [comment]
Looks like there's a solution for this so I'm going to close. Feel free to open a new issue if there's still something that needs to be fixed

**Comment by ceynri** [comment]
For me, i add `DEBUG=*` to run `./bin/dev.js` and notice that cannot find module `tsx/esm/api`:

```sh
oclif:config:ts-path tsconfig: {
  oclif:config:ts-path   compilerOptions: {
  oclif:config:ts-path     paths: { '@/*': [Array] },
  oclif:config:ts-path     lib: [ 'esnext', 'dom', 'dom.iterable', 'scripthost' ],
  oclif:config:ts-path     types: [ 'node', 'webpack-env' ],
  oclif:config:ts-path     baseUrl: '.',
  oclif:config:ts-path     sourceMap: true,
  oclif:config:ts-path     useDefineForClassFields: false,
  oclif:config:ts-path     forceConsistentCasingInFileNames: true,
  oclif:config:ts-path     allowSyntheticDefaultImports: true,
  oclif:config:ts-path     maxNodeModuleJsDepth: 10,
  oclif:config:ts-path     esModuleInterop: true,
  oclif:config:ts-path     skipLibCheck: true,
  oclif:config:ts-path     moduleResolution: 'Node16',
  oclif:config:ts-path     jsx: 'preserve',
  oclif:config:ts-path     strict: true,
  oclif:config:ts-path     module: 'Node16',
  oclif:config:ts-path     target: 'es2022',
  oclif:config:ts-path     rootDir: 'src',
  oclif:config:ts-path     outDir: 'dist',
  oclif:config:ts-path     declaration: true
  oclif:config:ts-path   },
  oclif:config:ts-path   'ts-node': { esm: true }
  oclif:config:ts-path } +0ms
  oclif:config:ts-path Determining path for /Users/ceynri/workspace/xxxx/dist/commands +1ms
  oclif:config:ts-path Could not find tsx. Skipping tsx registration for /Users/ceynri/workspace/xxxx. +0ms
  oclif:config:ts-path Error: Cannot find module 'tsx/esm/api'
  oclif:config:ts-path Require stack:
  oclif:config:ts-path - /Users/ceynri/workspace/magic-runtime/node_modules/.pnpm/@oclif+core@4.0.33/node_modules/@oclif/core/lib/config/ts-path.js
```

So i installed tsx and then i can use `./bin/dev.js`.

But `./bin/run.js` still cannot run because the dist wasn't translate the `@` alias. The solution is add `ts-alias` dependency, `./bin/run.js` is ok too.

```json
{
  "scripts": {
    "build": "shx rm -rf dist && tsc -b && tsc-alias",
  }
}
```
