### ISSUE TITLE
can i create multi cli bin in a single package

### ISSUE THREAD

**Issue by stormslowly** [oclif/oclif#1137]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Not sure,  May be a *feature*

What is the current behavior?
-----------------------------
current oclif package has only one entry in package.json's `bin` field.

What is the expected behavior?
------------------------------
define more than one entries in `bin` fileld.
```json
"bin": {
   "cmd1": "xxx1",
   "cmd2": "xxx2"
}
```

**Comment by WillieRuemmele** [comment]
Hey @stormslowly - we've just added a `binAliases` section, https://github.com/oclif/oclif/blob/main/package.json#L95 This will be aliased to the `oclif.bin` above when you `pack:mac`, `pack:win`, or `pack:deb`... you can add aliases for npm by changing the top-level `bin` to be an object https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin - hopefully those two will solve what you're looking for

**Comment by stormslowly** [comment]
@WillieRuemmele sorry for not making my issure clear.
my global is to make two different functional cli bins  in one oclif projectn.
for example,  i want  bin `gen`  to genrate a seralized file in some format  , and anther  one  `pasre` to parse this kind files.

i know ,i can use the subcommnad way like git ( `mycli  gen`  and  `mycli parse` ) , 
but is there any way to export two different bins ?

**Comment by mdonnalley** [comment]
@stormslowly oclif isn't able to support that. My suggestion would be to have two separate oclif projects and use a monorepo package to manage them
