### ISSUE TITLE
With ESM, `this.configDir` returns `~/.config/ts-node` on static `.run()`

### ISSUE THREAD

**Issue by mtsmfm** [oclif/oclif#1139]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

bug

What is the current behavior?
-----------------------------

`this.configDir` returns `~/.config/ts-node` on static `.run()`

https://github.com/mtsmfm/mynewcli

```
$ git clone https://github.com/mtsmfm/mynewcli
$ cd mynewcli
$ npm install

$ # Make sure it works in commonjs
$ git checkout commonjs
$ bin/dev hello world --foo
configDir /home/mtsmfm/.config/mynewcli
--foo is given
configDir /home/mtsmfm/.config/mynewcli
hello world! (./src/commands/hello/world.ts)

$ # configDir points /home/mtsmfm/.config/ts-node on static `.run`
$ git checkout esm
$ PATH=$(npm bin):$PATH bin/dev.js hello world --foo
configDir /home/mtsmfm/.config/mynewcli
--foo is given
configDir /home/mtsmfm/.config/ts-node
hello world! (./src/commands/hello/world.ts)
```

What is the expected behavior?
------------------------------

Returns `~/.config/mynewcli` even static `.run`

oclif: 3.7.3
OS: Windows 11 (WSL2 ubuntu, 5.15.90.1-microsoft-standard-WSL2)

**Comment by mdonnalley** [comment]
Fixed by https://github.com/oclif/core/pull/759 (currently available in `@ocilf/core@3.0.0-beta.5`)
