### ISSUE TITLE
Verifying shasum for Node.js dist causing `oclif pack` to fail nondeterministically on some Linux distros

### ISSUE THREAD

**Issue by peniqliotuv** [oclif/oclif#1145]
Bug Report 
-----------------------------------------------------
What is the current behavior?
-----------------------------
`oclif` currently fetches the node binary from the official node.js dist alongside the shasums (https://github.com/oclif/oclif/blob/72dafe15a7bc03a594f4db380db932eb8961d21a/src/tarballs/node.ts#L55) and then tries to verify the shasum of the downloaded binary against the list of official shasums.

However, line 66
```
if (platform !== 'win32') await exec(`grep "${path.basename(tarball)}" "${shasums}" | shasum -a 256 -c -`, {cwd: basedir})
```
can actually fail, resulting in the following error:
```
shasum: standard input: no properly formatted SHA checksum lines found
```
I'm not sure if this [StackExchange](https://unix.stackexchange.com/questions/139891/why-does-verifying-sha256-checksum-with-sha256sum-fail-on-debian-and-work-on-u) post is relevant - it's saying that on some linux distros, extra whitespace is treated differently, and if there are two whitespaces between the shasum and the filename, but only one is provided, that the shasum check will fail. 

We've seen this fail on both node16.18.0 and node16.18.1 for arm64.

This is causing our CLI release pipeline to fail nondeterminstically depending on which of the many possible tarballed artifacts we receive from the Node download server.

What is the expected behavior?
------------------------------
The checksum verification should succeed on all distros, all of the time

**Comment by peniqliotuv** [comment]
Another issue here could be that the download stream doesn't complete successfully. I'm not sure if Node will throw an error or not - but I wonder if it's a good idea to add in some retry logic https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#createretrystream ?

**Comment by peniqliotuv** [comment]
@mdonnalley @iowillhoit  sorry for the individual tags, but I saw you are active contributors. 

We run `oclif pack tarballs` in CI to distribute our CLI on release. Around 5% of the time, we get an issue with either the shasum mismatching, or the Node.JS server closing our connection
```
    ReadError: The server aborted pending request
    Code: ECONNRESET
```

We've already implemented retries on our end, but it would be prudent to add a `retry` on the `download`
https://github.com/oclif/oclif/blob/ff00ba0bc9299885b3d89c83d7cede81a29bd6f5/src/tarballs/node.ts#L85

You can accomplish this in one line by using the [async-retry](https://github.com/vercel/async-retry) package. I am happy to put up a PR for this, just let me know.

**Comment by mdonnalley** [comment]
@peniqliotuv sorry for the long delay on this. If you don't mind making the change you need, I'll review and merge a PR for the change as soon as it's ready. Thanks!

**Comment by peniqliotuv** [comment]
@mdonnalley I put up a simple PR. I couldn't find any contribution guidelines, and tests fail locally on publishing because I don't have access to your S3 bucket (probably should be mocked out anyways), but feel free to pull it down and test.

**Comment by mdonnalley** [comment]
@peniqliotuv Thanks for the PR! I'll review and test first thing on Monday morning

**Comment by peniqliotuv** [comment]
Thanks @mdonnalley ! How often do releases get cut?

**Comment by mdonnalley** [comment]
@peniqliotuv No problem - 3.15.1 has your changes
