### ISSUE TITLE
How to generate documentation in a file other than README.md using oclif?

### ISSUE THREAD

**Issue by mhmohona** [oclif/oclif#1146]
I'm trying to generate command documentation using oclif in a file other than the default README.md. 

I've tried running the oclif readme --out OTHER_FILE.md command, but it doesn't seem to work. I get an error message saying Nonexistent flag: --out.

Can someone please advise me on the correct command to use to generate the documentation in a different file, or if there's a workaround to achieve this?

Thank you!

**Comment by mshanemc** [comment]
you'll see the README file is always edited, never created.  It has certain invisible sections that are markdown comments (look at in `raw` on github) that it knows where to write stuff.

If you create another file that exists, and has the right sections, it should work.

**Comment by mhmohona** [comment]
@mshanemc, thank you for your reply! 

So I created another markdown file deleting the readme file with these tags - 
```
# Usage

<!-- usage -->


# Commands

<!-- commands -->
```
and ran `oclif readme` command. It was giving me error - 

> Error: ENOENT: no such file or directory, open '..../README.md'
>     Code: ENOENT

**Comment by tuler** [comment]
I also wanted an option to use another file other than the current directory README.md
I have a documentation website, in another project, and I wanted to generate documentation there.

**Comment by mhmohona** [comment]
Hello @tuler, so I created a readme inside another folder and then ran `oclif readme` command inside that folder, so I got the generated document in that readme and my main readme was unchanged. Thats how i solved my problem.
You can check this PR for more details - https://github.com/asyncapi/cli/pull/556
