### ISSUE TITLE
vite-node incompatible with oclif

### ISSUE THREAD

**Issue by DanHulton** [oclif/oclif#1151]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug.

What is the current behavior?
-----------------------------
I am writing a CLI for a project of mine and I want to be able to include files from that project when running the CLI for certain tasks.  However, since I rune vite (for the UI) and vite-node (for the API) for that project, that means I must be able to run vite-node for the CLI as well.  I have chosen [oclif](https://github.com/oclif/oclif) for the CLI, as it is a fairly popular CLI framework used by major companies to write their CLIs, however it does not run using vite-node.  I get the following error when it attempts to read the `commands` folder and load the individual command files:

```
(node:51441) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: oclif-vite-node-repro [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/danhulton/dev/oclif-vite-node-repro/src/commands/hello/index.ts
module: @oclif/core@2.8.7
task: toCached
plugin: oclif-vite-node-repro
root: /Users/danhulton/dev/oclif-vite-node-repro
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError Plugin: oclif-vite-node-repro [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/danhulton/dev/oclif-vite-node-repro/src/commands/hello/index.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
module: @oclif/core@2.8.7
task: toCached
plugin: oclif-vite-node-repro
root: /Users/danhulton/dev/oclif-vite-node-repro
See more details with DEBUG=*
``` 

I do not know which package is responsible for the error, so I am opening an issue in each project and am cross-linking it here:

["vite-node incompatible with oclif" at vitest-dev/vitest](https://github.com/vitest-dev/vitest/issues/3613)

What is the expected behavior?
------------------------------
The expected behaviour is for the oclif help text to be displayed, including the `hello` topic & command.

A full reproduction can be found at [DanHulton/oclif-vite-node-repro](https://github.com/DanHulton/oclif-vite-node-repro).

This is a minimal install of both oclif and vite-node, as well as the bare minimum amount of changes required to integrate the two (which boil down to changing the shebang to use vite-node and converting oclif to use ESM).

  System:
    OS: macOS 13.4
    CPU: (8) x64 Apple M1 Pro
    Memory: 76.40 MB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 113.0.2
    Safari: 16.5
  oclif:
    Version: 2.8.7

**Comment by mdonnalley** [comment]
@DanHulton Thanks for providing a repository that replicates it 🏆

I've played around with this and I think the issue is that vite-node isn't able to analyze dynamic imports from node_modules (which is what oclif/core is doing when it attempts to import the source typescript files). I think https://github.com/vitejs/vite/issues/14102 might be related (not 100% sure though).

That dynamic import is deeply embedded at this point so I don't think we'll support this going forward. The best workaround I have for you is to compile your code before running `bin/dev.js` and set `settings.enableAutoTranspile = false` to turn off any auto compilation.
