### ISSUE TITLE
Default `.gitignore` content generated using yarn 2+ is missing recommended lines by yarn

### ISSUE THREAD

**Issue by jenkin** [oclif/oclif#1152]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A bug.

What is the current behavior?
-----------------------------
OS Version: `Ubuntu 22.04.2 LTS`.

Node version: `v18.16.0` (npm `v9.5.1`, yarn `v3.6.0`).

Oclif version: `v3.9.1`.

Generate a new project using `npx oclif generate <project-name>` with `yarn` as package manager. Yarn configuration shipped with oclif doesn't support [zero-installs](https://yarnpkg.com/features/zero-installs) (it uses `node_modules` local folder). The default `.gitignore` shipped with oclif doesn't follow the [recommended settings by yarn](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) (see the second code block).

`.gitignore` default content
```
**/.DS_Store
*-debug.log
*-error.log
/.idea
/.nyc_output
/dist
/lib
/package-lock.json
/tmp
node_modules
oclif.manifest.json
```

What is the expected behavior?
------------------------------
The `.gitignore` file generated when using yarn 2+ should contains all recommended lines from yarn.

`.gitignore` proposed content
```
**/.DS_Store
*-debug.log
*-error.log
/.idea
/.nyc_output
/dist
/lib
/package-lock.json
/tmp
node_modules
oclif.manifest.json
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
```

**Comment by capsulecorplab** [comment]
Any particular reason `package-lock.json` is in the `.gitignore`? My understanding was that it shouldn't be ignored as to ensure a "known-to-work" state with the exact same dependency tree https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

**Comment by mdonnalley** [comment]
> Any particular reason `package-lock.json` is in the `.gitignore`? My understanding was that it shouldn't be ignored as to ensure a "known-to-work" state with the exact same dependency tree https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

It's only added if you selected yarn as the package manager. If you select npm, it won't be added
