### ISSUE TITLE
[Feature] Protected flags and commands

### ISSUE THREAD

**Issue by AllanOricil** [oclif/oclif#1157]
Certain CLIs have commands and flags that expose sensitive information that can be used without sudo privileges, such as salesforce's sfdx auth command and its `--verbose` flag. So I was thinking that ocliff could create a new property for both commands and flags that when set to `true` it would prompt users to type in a password. For example, if the `--verbose` flag is configured with `require-password: true`, every command that uses it would ask the client for a password before the command can be executed. The same when `require-password` is configured at command level. 

````bash
sfdx auth:display --verbose --json
password: 
{
...
}
````

The password would be stored in a local or cloud keystore (aws secret manager).

@mshanemc 
@cristiand391

**Comment by cristiand391** [comment]
what use-cases do you envision where this could prevent exposing sensitive info? do you know any CLI doings something like this?

in the Salesforce CLI case, even with this feature there's a ton of ways to can get access to an org/creds (read auth files manually, `sf org open`, etc). Also you risk having to type a password all the time and having to handle additional creds in your CLI.

**Comment by AllanOricil** [comment]
I was thinking that users should have a way to protect their connected environments so that if their computer is accessed by an unauthorized person their orgs would still be protected since it would require a password to decrypt the auth information that is stored in the host.

**Comment by AllanOricil** [comment]
There is probably a npm package to interact with the OS native key stores

**Comment by AllanOricil** [comment]
https://www.npmjs.com/package/sudo-prompt

**Comment by AllanOricil** [comment]
related
https://github.com/forcedotcom/cli/issues/1234

**Comment by AllanOricil** [comment]
would work unless there was also a way to auth to an external authorization service
