### ISSUE TITLE
Typescript compilation failure of tests through nyc.  How to ensure it uses `test/tsconfig.json`?

### ISSUE THREAD

**Issue by mattmazzola** [oclif/oclif#116]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug, but it's more of a question since I'm not familiar with oclif's setup for `nyc`

What is the current behavior?
-----------------------------
I'm attempting to build a CLI to write to the file system and need to know the current working directory and use path join operations.  When I include 'path' and reference 'process' in the commands the commands work fine; however, when attempting to run tests, it does not pick up these types, fails to compile that command, and the tests for the command fail with 'command X not found' even though the command works by testing manually.

Can reproduce by:
```
1. npx oclif multi error-test
2. Run `npm t` to test and see passing
3. Update the hello command to use `path` or `process` and update test assertions if needed
4. Run `npm t` to test again
```
Example error:
```
(node:10600) TSError Plugin: <removed>: ⨯ Unable to compile TypeScript
src\commands\create.ts (2,23): Cannot find module 'path'. (2307)
src\commands\create.ts (26,31): Cannot find name 'process'. (2304)
...
```

Oddly enough, if I manually run `tsc -p ./tsconfig.json` to compile the commands and `tsc -p /test/tsconfig.json` to compile the tests they both compile fine.  `npm run posttest` is also good.  It's only when the compilation is through the `npm test` script that it fails to find the node types.

```
"dependencies": {
    "@oclif/command": "1.4.30",
    "@oclif/config": "1.6.19",
    "@oclif/plugin-help": "1.2.11",
    "tslib": "1.9.1"
  },
```

```
"typescript": "2.8.3"
```

I also tried manually installing `@types/node` as devDependency and that still didn't help.

What is the expected behavior?
------------------------------
I would expect that if tests compile through directly invoking `tsc` on their associated `tscconfig` project, then the `npm test` command similarly should succeed compilation.

Can someone help me understand where the difference is or perhaps what changes I can make to the `test/tsconfig.json` ?

I've tried forcing it to pick up node types by adding `types: ["node"]` but those should have already been included since they are in default `typesRoots`

**Comment by jdxcode** [comment]
I'm not able to reproduce. Here is my `package.json` and command:

```js
{
  "name": "mycli",
  "version": "0.0.0",
  "author": "Jeff Dickey @jdxcode",
  "bin": {
    "mycli": "./bin/run"
  },
  "bugs": "https://github.com/jdxcode/mycli/issues",
  "dependencies": {
    "@oclif/command": "^1",
    "@oclif/config": "^1",
    "@oclif/plugin-help": "^1",
    "tslib": "^1"
  },
  "devDependencies": {
    "@oclif/dev-cli": "^1",
    "@oclif/test": "^1",
    "@oclif/tslint": "^1",
    "@types/chai": "^4",
    "@types/mocha": "^5",
    "@types/node": "^10",
    "chai": "^4",
    "globby": "^8",
    "mocha": "^5",
    "nyc": "^11",
    "ts-node": "^6",
    "tslint": "^5",
    "typescript": "^2.8"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "files": [
    "/bin",
    "/lib",
    "/oclif.manifest.json"
  ],
  "homepage": "https://github.com/jdxcode/mycli",
  "keywords": [
    "oclif"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "oclif": {
    "commands": "./lib/commands",
    "bin": "mycli",
    "plugins": [
      "@oclif/plugin-help"
    ]
  },
  "repository": "jdxcode/mycli",
  "scripts": {
    "postpack": "rm -f oclif.manifest.json",
    "posttest": "tsc -p test --noEmit && tslint -p test -t stylish",
    "prepack": "rm -rf lib && tsc && oclif-dev manifest && oclif-dev readme",
    "test": "nyc mocha --forbid-only \"test/**/*.test.ts\"",
    "version": "oclif-dev readme && git add README.md"
  },
  "types": "lib/index.d.ts"
}
```

```js
import {Command, flags} from '@oclif/command'

export default class Hello extends Command {
  static description = 'describe the command here'

  static examples = [
    `$ mycli hello
hello world from ./src/hello.ts!
`,
  ]

  static flags = {
    help: flags.help({char: 'h'}),
    // flag with a value (-n, --name=VALUE)
    name: flags.string({char: 'n', description: 'name to print'}),
    // flag with no value (-f, --force)
    force: flags.boolean({char: 'f'}),
  }

  static args = [{name: 'file'}]

  async run() {
    const {args, flags} = this.parse(Hello)

    const name = flags.name || 'world'
    this.log(`hello ${name} from ./src/commands/hello.ts`)
    if (args.file && flags.force) {
      this.log(`you input --force and --file: ${args.file}`)
    }
    this.log(process.version)
  }
}
```

**Comment by jdxcode** [comment]
I wonder if it's a windows issue since I'm noticing the hook build is failing on appveyor https://ci.appveyor.com/project/heroku/oclif/build/1.0.337/job/67opa7em3u599mcy

**Comment by jdxcode** [comment]
I put a patch in, but this definitely seems to be a bug in TypeScript as `typeRoots` shouldn't have to be manually specified—especially only for windows.

**Comment by mattmazzola** [comment]
> bug in TypeScript
Yea, that's why I was suspicious as to how `nyc` command is invoking compilation because TypeScript compiles successfully if you do it directly.  I wonder if they're passing some extra flags to override certain compilation options and unintentionally changing typesRoots or excluding global types such as node.

Would be interesting to find a way to debug the nyc and make it pass the `traceResolution` into `tsc`

**Comment by jdxcode** [comment]
this has nothing to do with `nyc`. If you run mocha directly this happens. It's either an issue with `ts-node` or `typescript`.
