### ISSUE TITLE
[Feature] How to determine if a command has been run using alias ?

### ISSUE THREAD

**Issue by jean-smaug** [oclif/oclif#1168]
I couldn't find any solution for my need, but if there is one or a workaround, I take 😄 

Context : 
I'm creating a CLI that is available in the following repo : https://github.com/progressively-crew/cli

What is the current behavior?
-----------------------------

When I run the CLI in production mode, `process.argv` gives me the following results 👇 

![Capture d’écran 2023-08-12 à 11 08 28](https://github.com/oclif/oclif/assets/22884251/cedcbc32-315c-436b-b82e-8af59f0f7866)

In `package.json`, `bin` section is configured to target the `./bin/run` for the base command and for the alias (`progressively` or `psy`)
Is it due to Oclif or it's just that `argv` isn't the proper way to access the initial command ?

What is the expected behavior?
------------------------------

I would like to be able to determine if the command has been executed using the default or the alias.
With my example, instead of having `/Users/mblanc/Localdev/progressively/node_modules/@progressively/cli/bin/run` I would like to have `psy`.

Thanks 😄

**Comment by mdonnalley** [comment]
@jean-smaug Unfortunately, I don't think this is possible. The bin aliases are just symlinks back to the actual bin, so the shell is always going to resolve to the actual bin whenever an alias is used.

**Comment by jean-smaug** [comment]
> @jean-smaug Unfortunately, I don't think this is possible. The bin aliases are just symlinks back to the actual bin, so the shell is always going to resolve to the actual bin whenever an alias is used.

👋 @mdonnalley thanks for answer.
That's also the conclusion I had.

I choose to duplicate the `run` files a workaround and name them `run-alias`.
It isn't perfect but it's working without a high effort.

https://github.com/progressively-crew/cli/blob/master/docs/adr/0001-alias-bin.md#decision

Think we can close the issue 😄
