### ISSUE TITLE
Don't add defender exclusion by default

### ISSUE THREAD

**Issue by jyoung15** [oclif/oclif#1173]
Reopening issue reported in https://github.com/oclif/dev-cli/issues/433, in regards to the following section:

https://github.com/oclif/oclif/blob/31a19ca2ec988b3a036dafe903e2527a96bd79a4/src/commands/pack/win.ts#L85-L87

Some EDR platforms (for example Crowdstrike) will block execution when an application automatically adds an exclusion to Defender.   As stated in the original issue these exclusions can open the system to new attack vectors, and this should be disabled by default.

**Comment by jyoung15** [comment]
Thank you @cristiand391.  Sorry, I did not realize this issue was already discussed for Salesforce CLI.  In my case it was for [boxcli](https://github.com/box/boxcli).  I just tested unchecking that option and it resolved the issue.  Closing this issue.

**Comment by cristiand391** [comment]
Reopened to track this as a feature request:
For CLI devs that generates Windows installer, would you be interested in something like `oclif pack win --no-defender-exclusion`? This could either completely remove the option from the installer or [mark it as unchecked by default](https://stackoverflow.com/questions/16056799/how-can-i-make-a-section-in-nsis-unchecked-by-default).

let us know if you have any opinion on this :)

**Comment by cristiand391** [comment]
added support to disable this option when generating windows installers in oclif v4.0.4:
https://github.com/oclif/oclif/blob/main/CHANGELOG.md#404-2023-11-20
