### ISSUE TITLE
`oclif command` - snake-case not enforced for topics with a dash in the name

### ISSUE THREAD

**Issue by shazron** [oclif/oclif#118]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug. 

What is the current behavior?
-----------------------------
`oclif command foo:bar-baz` does not report an error regarding snake-case needed for the `bar-baz` topic, and creates the files.

Repro:
1. Create a new plugin
2. In the root of the new plugin folder, run `oclif command foo:bar-baz`.

Note that the command and topic is created, even though a dash is not allowed (see below).

What is the expected behavior?
------------------------------
`oclif command foo:bar-baz` **should** report an error regarding snake-case needed for the `bar-baz` topic (and not create the files) as per the `.eslintrc` config. 

If you created a new topic file manually with a dash in it in `src/commands`, eslint will complain because of the eslint rules set.

eslint error: 
```
[eslint] Filename is not in snake case. Rename it to `bah_baz.js`. (unicorn/filename-case)
```

Version
--------
oclif/1.7.50 darwin-x64 node-v8.10.0
macOS X 10.13.4

**Comment by zcei** [comment]
Honestly I feel like the rule should be changed to kebab-case, or at least it should auto-convert kebab-case commands to snake-case file names.

Per the [Heroku CLI style guide - Naming the command](https://devcenter.heroku.com/articles/cli-style-guide#naming-the-command) kebab-case is the preferred multi-word spacing

**Comment by shazron** [comment]
I would definitely prefer kebab-case -- I'm not sure myself what the design decision was to disallow it, perhaps there is a conflict somewhere.

**Comment by jdxcode** [comment]
the linter rule should be removed. Ideally only for these commands, but I don't think there is a way to specify that

**Comment by shazron** [comment]
Thanks for the clarification! So this bug is invalid, since it's more of an eslint config thing (that is unresolved looks like).

**Comment by jdxcode** [comment]
it's not invalid, we need to make a modification to this line https://github.com/oclif/eslint-config-oclif/blob/master/index.js#L19

**Comment by shazron** [comment]
Alright, should I send a PR to remove it then? Thanks.

**Comment by jdxcode** [comment]
sure, but I'm not sure if removing the line will work. You may need to override the rule

**Comment by shazron** [comment]
I ran `eslint` on my source (with a file with a kebab-case name), and it fails, and when I removed that line in my local node_modules version of `eslint-config-oclif` and re-ran eslint, it then passes, so I think it should work. The override works as well.
