### ISSUE TITLE
Blog videos are Private

### ISSUE THREAD

**Issue by jarrodek** [oclif/oclif#1189]
All videos in your blog are private. I am not sure what's the point of having them there while even employees can't see them.

![image](https://github.com/oclif/oclif/assets/3320020/d2082709-6fbb-49ec-8c77-b6b2ed567c77)

**Comment by mdonnalley** [comment]
@jarrodek unfortunately these videos were lost a few years ago when the Heroku youtube channel was migrated to the Salesforce Developer youtube channel. I've tried to track them down but to no avail.
