### ISSUE TITLE
Bug: `oclif readme` broken

### ISSUE THREAD

**Issue by hirasso** [oclif/oclif#1190]
### What is the current behavior?

`oclif readme` doesn't work correctly with typescript projects. It either doesn't output any commands (pre-build) or it outputs incorrect *_See code...* links (post-build).

Let's use the [hello world](https://github.com/oclif/hello-world) template as an example. Installing it locally and then running `oclif readme` will produce incorrect and inconsistent commands docs:

1. When runnning `oclif readme` without having previously built the package, the available commands won't be listed at all (since the script depends on the `oclif.commands` entry in the `package.json` that is (correctly) pointing to the **non-existent dist files** in `/dist/commands`).
2. When first executing `npm run build` (now the `/dist/` folder is present!), `oclif readme` will find the commands, but the links are off, for example: 
> _See code: [dist/commands/hello/index.ts](https://github.com/oclif/hello-world/blob/v0.0.0/dist/commands/hello/index.ts)_

Note the leading `dist/`, but the file extension `.ts`. That file will never exist.

### What is the expected behavior
`oclif readme` should always output the commands with correct source links, pre- and post-build.

### Suggested solution

There needs to be a way to tell oclif where the actual source files are. Maybe something like `oclif.commandsSrc` or an optionally nested object for `oclif.commands` could help:
```json
{
  "oclif": {
    "commands": {
      "dist": "./dist/commands",
      "src": "./src/commands"
    }
  },
}
```

**Comment by mdonnalley** [comment]
@hirasso Thanks for creating this issue. Looks like the `readme` command expects the compiled src directory to be `lib` and will replace `lib` for `src` when generating the command's path. 

I'll create a PR today to make it compatible with `dist`

**Comment by hirasso** [comment]
@mdonnalley did I understand you correctly that `oclif readme` should work correctly if the compiled commands folder is present and called `/lib`? 

Out or curiosity I tested just that: 

- Changed the folder to `/lib`
- ran `npm run build` (compiled code landed in /dist)
- ran `npx oclif readme`

The result looks the same as before to me. One example (for a command called `swup create`):

```
_See code: [lib/commands/create.js](https://github.com/swup/cli/blob/v5.0.1/lib/commands/create.js)_
```

Issues we are having with the above:

- `lib/commands/create.js` could be mangled code, since it's compiled from `/src`
- the version in the URL (`v5.0.1`) is not prepended with a `v` in our package
- `/lib/` should be replaced with `/src/`
- `create.js` should be `create.ts`

Ideally we would be able to output this:

```
_See code: [src/commands/create.ts](https://github.com/swup/cli/blob/5.0.1/src/commands/create.ts)_
```
I noticed that I can use `oclif.repositoryPrefix` in our package.json to remove the `v` from the version, but all the other issues prevail.

```json
{
  "repositoryPrefix": "<%- repo %>/blob/<%- version %>/<%- commandPath %>",
}
```

Just wanted to write this down - no pressure to solve it anytime soon :)

**Comment by hirasso** [comment]
Another, probably simpler-to-implement option would be to completely disable the output of the `_See code: ...` links.

**Comment by mdonnalley** [comment]
@hirasso yes, using `lib` for the compiled directory should fix it (at least it did in the hello-world repo). I would just make sure that you've updated `compilerOptions.outDir` in your tsconfig.json and `oclif.commands` in package.json to `lib` and then recompile your code. 

Let me know if that helps. If not, I can fork your repo and debug it there

**Comment by hirasso** [comment]
I tested it. The output is still this:

```
_See code: [lib/commands/create.js](https://github.com/swup/cli/blob/v5.0.1/lib/commands/create.js)_
```

**Comment by hirasso** [comment]
Works like a charm in `3.17.1`! Thanks so much for your help @mdonnalley ! 🙏
