### ISSUE TITLE
How do I run?

### ISSUE THREAD

**Issue by alper** [oclif/oclif#1192]
Do you run this in development with:

* `oclif`
* `oex`
* `./bin/dev`

Any of the above? What's the flag to pass to run this with `pnpm run`?

**Comment by mdonnalley** [comment]
@alper `./bin/dev` is what you should use to run oclif plugins in development.

**Comment by alper** [comment]
I'm not running plugins? I'm trying to get the CLI to run.

**Comment by mdonnalley** [comment]
@alper can you give me more context on what you're trying to accomplish?

There's no difference between a plugin and a CLI in oclif. So if you've generated a new CLI using `oclif generate`, you just need to `cd` into the directory and you can run it using `bin/dev`.

If you've published that plugin to NPM and then did a `npm install -g` to install it globally, then you'd use the bin you defined in the `bin` field of the package.json
