### ISSUE TITLE
Command descriptions do not show in the CLI help for JavaScript commands

### ISSUE THREAD

**Issue by shazron** [oclif/oclif#120]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Repro:
1. Create a JavaScript-based command in `src/commands` (see example below)
2. Run `./bin/run` (no arguments)
3. Note that in the help the `description` for the command is blank

For a TypeScript-based command, the description **shows**, however.

Example:
```javascript
const {Command, flags} = require('@oclif/command')

class TestCommand extends Command {
  async run() {
    const {flags} = this.parse(TestCommand)
    const name = flags.name || 'world'
    this.log(`hello ${name} from test.js`)
  }
}

TestCommand.description = `
Describe the command here
...
Extra documentation goes here
`

TestCommand.flags = {
  name: flags.string({char: 'n', description: 'name to print'}),
}

module.exports = TestCommand
```

What is the expected behavior?
------------------------------
The help `description` should show for a JavaScript-based command.

Version
-------
oclif/1.7.49 darwin-x64 node-v8.9.4
macOS 10.13.4

**Comment by jdxcode** [comment]
Try using:

```
TestCommand.description = `Describe the command here
...
Extra documentation goes here
```

It only shows the first line

**Comment by shazron** [comment]
Thanks, that works, but how does the CLI grab the help description if you have multiple topics? 

Is there a specific file? I find that it will grab the first help description from a topic, sorted alphabetically ascending (thus alpha.js description is used, not beta.js). I would expect it to grab it from the `index.js` but it doesn't.

**Comment by shazron** [comment]
I see that from the docs it is `The help descriptions will be the description of the first command within a directory.` but I would argue that is a bit intuitive.

**Comment by shazron** [comment]
Also - the generated plugin from the template should put the description on the same line, just as a hint since it puts it on the next line. I will add a PR for this

**Comment by jdxcode** [comment]
You can put the descriptions into `package.json`, is that helpful? I'm not sure I understand the issue

**Comment by shazron** [comment]
Saw that, here's what I'm thinking. If I have this in package.json, the help shows for my command `foo`.

```javascript
{
  "oclif": {
    "topics": {
      "foo": { "description": "Replace bar with foo things" },
    }
  }
}
```

But if I just have the description in `src/commands/foo/index.js`, it doesn't show that help description. I would have intuitively thought that that description would be picked up, instead of needing to specify it in `package.json`.
```
package.json
src/
└── commands/
    └── foo/
        ├── index.js
        ├── bar.js
```
