### ISSUE TITLE
oclif v2   generate plugin   oclif/core is not v2

### ISSUE THREAD

**Issue by mochj12** [oclif/oclif#1202]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

**Comment by mdonnalley** [comment]
@mochj12 The versions of oclif and oclif/core have never been synchronized - oclif has always generated plugins using the latest major version of oclif/core

If you absolutely need a plugin that uses v2, you can reference [plugin-test-core-v2](https://github.com/oclif/plugin-test-core-v2) as an example
