### ISSUE TITLE
Dev mode with hot reload

### ISSUE THREAD

**Issue by PierBJX** [oclif/oclif#1203]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
I would like to know if there was a way to run a dev mode with hot reload. Like this, it would be faster for developing.
Usually, for backend project, I was using `nodemon` but in `oclif`'s provided examples I don't see any dev mode.
 
What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
Currently, I have to run `npm run build` and then run it.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.
I would like to have a dev mode

**Comment by cristiand391** [comment]
`bin/dev` will use ts-node to transpile TS on the fly (vs having to `npm run build` then run `bin/run`)

for watch mode I use the node native watch mode (still experimental), just add `--watch` to the first line of `bin/dev`, then the process will rerun a command after a change:

https://github.com/oclif/oclif/assets/6853656/0b8afc53-994b-44f0-96f2-7b41702e25fa

node watch docs: https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--watch
