### ISSUE TITLE
Faulty library exports

### ISSUE THREAD

**Issue by JonasDoe** [oclif/oclif#1204]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
It's a bug, happening with `"@oclif/core": "^3.6.0"` and `"typescript": "^5.2.2"` (and `commonjs`) under `Ubuntu 22.04.3 LTS`.

What is the current behavior?
-----------------------------
`import { Command } from '@oclif/core'` and similar imports from `'@oclif/core'` will result into this error:
```
node_modules/@oclif/core/lib/cli-ux/stub.d.ts:1:46 - error TS2307: Cannot find module 'sinon' or its corresponding type declarations.

1 import type { SinonSandbox, SinonStub } from 'sinon';
```
I can avoid it be importing the desired elements directly, e.g. with
`import { Command } from '@oclif/core/lib/command'`

What is the expected behavior?
------------------------------
I'ld expect that this dev dependency (?) isn't part of the exposed API.

**Comment by sannysoft** [comment]
Same happening for me with oclif 4.14.9
