### ISSUE TITLE
enableJsonFlag does not work with custom base class

### ISSUE THREAD

**Issue by tylerbutler** [oclif/oclif#1205]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug.

What is the current behavior?
-----------------------------

When a command inherits from a custom base class, even the one from the [oclif docs](https://oclif.io/docs/base_class), the `enableJsonFlag` option causes an error and JSON "spam" when you pass the `--json` flag to that command.

I am able to reproduce this with the latest version of oclif and the BaseCommand from the documentation. I created a project to reproduce it here: <https://github.com/tylerbutler/oclif-repro> The readme has details on the failures and the commands to reproduce them. That project was generated by the oclif generator, and the base class code is from the docs.

As far as I can tell, this regressed in the most recent major version of oclif, but I can't be more precise than that.

What is the expected behavior?
------------------------------

`enableJsonFlag` should work correctly in classes that inherit from a custom base class.

**Comment by mdonnalley** [comment]
@tylerbutler Thanks for pointing this out! This seems to be a documentation error rather than a regression.

Add this line to the `this.parse` call in `BaseCommand`,

```typescript
enableJsonFlag: this.ctor.enableJsonFlag,
```
