### ISSUE TITLE
'exclusive' flag option missing

### ISSUE THREAD

**Issue by matheuskwinter** [oclif/oclif#121]
The [documentation](https://github.com/oclif/oclif.github.io/commit/ba3174a9b987d25ab1c08cb6d78a637a917cb8f8) states that it is already available, but I couldn't find it anywhere.

**Comment by jdxcode** [comment]
what do you mean? that it doesn't work? here is a test that uses it: https://github.com/oclif/parser/blob/a24c135b91d1902ad9d50636444dc2c14d98c25e/test/parse.test.ts#L450

**Comment by matheuskwinter** [comment]
It turns out that I was using a not so recent major release that didn't had the flag option yet, sorry for the false alarm.
