### ISSUE TITLE
Make README.md filename configurable

### ISSUE THREAD

**Issue by moltar** [oclif/oclif#1218]
I wish the name of the file was configurable because it conflicts with another tool that generates a README already. And I wish to store the codegen'ed README in another file, e.g. CLI.md and then either link to it, or include it in the main `README.md`

https://github.com/oclif/oclif/blob/3570d93f5eac061a6b59518bf69a73fb013e1754/src/commands/readme.ts#L175

I am willing to provide a PR.

**Comment by mdonnalley** [comment]
@moltar I'll happily accept a PR for this if you'd like to provide one. Thanks!

**Comment by moltar** [comment]
Would you accept the use of this dependency? https://www.npmjs.com/package/detect-package-manager
