### ISSUE TITLE
`oclif pack win` not working when called via npx

### ISSUE THREAD

**Issue by Amndeep7** [oclif/oclif#1227]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------
When you run `npx oclif pack win` you get `TypeError: undefined is not a function` output to the terminal.

```
$ npx oclif pack win
    TypeError: undefined is not a function
```

You can also see it fails in this run here: https://github.com/mitre/saf/actions/runs/7272624269/job/19815074505

What is the expected behavior?
------------------------------
That command should properly package a given repository.  It works if you build and run it manually.

```
$ ../oclif/bin/run.js pack win
oclif: gathering workspace for saf to /Users/amann/work/saf/cloned-saf/tmp/saf
oclif: will build 2 targets in parallel
oclif: building target saf-v1.3.0-ace473d-win32-x64.tar.gz
oclif: copying workspace ./tmp/saf ./tmp/win32-x64/saf
oclif: building target saf-v1.3.0-ace473d-win32-x86.tar.gz
oclif: copying workspace ./tmp/saf ./tmp/win32-x86/saf
oclif: downloading node-v18.18.2-win-x64
oclif: downloading node-v18.18.2-win-x86
oclif: extracting node-v18.18.2-win-x86
oclif: extracting node-v18.18.2-win-x64
built /Users/amann/work/saf/cloned-saf/dist/win32/saf-v1.3.0-ace473d-x86.exe
built /Users/amann/work/saf/cloned-saf/dist/win32/saf-v1.3.0-ace473d-x64.exe
```

Strangely, `oclif pack macos` works just fine as you can see here: https://github.com/mitre/saf/actions/runs/7272624265/job/19815074353 

```
$ npx oclif --version
oclif/4.1.0 darwin-x64 node-v18.18.2
```

**Comment by mdonnalley** [comment]
@Amndeep7 Can you provide the debug logs when running that command? `DEBUG=* npx oclif pack win`

Thanks!

**Comment by Amndeep7** [comment]
@mdonnalley 

Repo this is being run on: https://github.com/mitre/saf

<details>
<summary>
Debug output
</summary>

```
$ DEBUG=* npx oclif pack win
  config reading core plugin /Users/amann/work/saf/cloned-saf/node_modules/oclif +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/oclif/package.json +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/oclif/oclif.manifest.json +0ms
  config:oclif using manifest from /Users/amann/work/saf/cloned-saf/node_modules/oclif/oclif.manifest.json +0ms
  config reading user plugins pjson /Users/amann/.local/share/oclif/package.json +0ms
  config loadJSON /Users/amann/.local/share/oclif/package.json +0ms
  config loading plugins [
  '@oclif/plugin-help',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-not-found'
] +0ms
  config reading core plugin /Users/amann/work/saf/cloned-saf/node_modules/oclif/node_modules/@oclif/plugin-help +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/oclif/node_modules/@oclif/plugin-help/package.json +0ms
  config reading core plugin /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-warn-if-update-available +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  config reading core plugin /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-not-found +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-not-found/package.json +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config loadJSON /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from /Users/amann/work/saf/cloned-saf/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config:@oclif/plugin-warn-if-update-available using manifest from /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config:@oclif/plugin-not-found using manifest from /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  config config done +0ms
  config start init hook +0ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init start (import) /Users/amann/work/saf/cloned-saf/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init done +1ms
  config init hook done +25ms
  config runCommand pack:win [] +1ms
    TypeError: undefined is not a function
```

</details>

**Comment by mdonnalley** [comment]
@Amndeep7 I think I've found the issue.

You're package-lock has oclif using oclif/core 2.15.0: https://github.com/mitre/saf/blob/139b73ca9f944c9c02dce115818e65cc4c228d86/package-lock.json#L15743

But oclif actually depends on ^3: https://github.com/oclif/oclif/blob/4.1.1/package.json#L11

So I think all you need to do is to regenerate your package-lock.json

**Comment by Amndeep7** [comment]
@mdonnalley Thanks for pointing that out.  I've tried doing that and the error still persists.  I think it's due to `oclif` itself having a dependency on `@oclif/core 2.15.0` via at least `@oclif/plugin-help`.  The latest version of `plugin-help` is 6.0.9 and is using `core` at 3.15.0.  However, the version of `plugin-help` being used in `oclif` is 5.2.14 which is dependent on `core` at 2.15.0.  You can see that `oclif` is actually dependent on both versions of `core`: https://github.com/oclif/oclif/blob/main/yarn.lock#L803.  Manually adding an 'overrides' in the package.json file to force `oclif/core` to 3.16.0 does resolve the issue; however, I'd like to avoid doing that since it seems like a simple enough change to `core`.

**Comment by mdonnalley** [comment]
@Amndeep7 I just merged #1231 which bumps all the `@oclif/` deps to their latest major versions. Can you let me know if v4.1.2 resolves the issue for you? Thanks!

**Comment by Amndeep7** [comment]
@mdonnalley it looks like our CI is passing again using `npx oclif` so seems like a fix to me!  Thanks for the prompt help!

Would it be possible for you to take a look at this pr too: https://github.com/oclif/oclif/pull/1215?  I'll deal with the merge conflicts that arose.  Really what I'd like is for it to run against your CI so that I can confirm that all the tests actually pass (can't run the tests locally since it depends on yall's secrets / AWS).

**Comment by mdonnalley** [comment]
> Would it be possible for you to take a look at this pr too: https://github.com/oclif/oclif/pull/1215?

@Amndeep7 Yes that's on my backlog. Sorry for the delay on that one. That's the kind of change I want to be really be careful with so I've been waiting until I have more time to dedicate towards testing and reviewing it

**Comment by Amndeep7** [comment]
@mdonnalley That's completely fine - I just wanted confirmation that someone was going to take a look at it.  Thank you!
