### ISSUE TITLE
Error running npx oclif-dev pack

### ISSUE THREAD

**Issue by smk508** [oclif/oclif#126]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
When I use npx oclif-dev pack to deploy my CLI tool, I get an np error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kyuubi@0.1.0 prepack: `rm -rf lib && tsc && oclif-dev manifest && oclif-dev readme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cli_tool@0.1.0 prepack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

If I try to run `rm -rf lib && tsc && oclif-dev manifest && oclif-dev readme` in isolation I get the following error:
`node_modules/@types/sinon/index.d.ts(489,36): error TS1005: ';' expected.`

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

Running ubuntu 17.10 with oclif 1.8.0 and node 10.4.

Thanks,
Saad

**Comment by jdxcode** [comment]
this is an issue with the sinon typescript type, not with oclif
