### ISSUE TITLE
Command Injection in lodash.template

### ISSUE THREAD

**Issue by VBeytok** [oclif/oclif#1275]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Command Injection in lodash.template https://security.snyk.io/package/npm/lodash.template/4.5.0

What is the expected behavior?
------------------------------
There is no fixed version for lodash.template 😞 
Oclif version 4.3.4

**Comment by mdonnalley** [comment]
We'll bump the library as soon as lodash fixes it.

**Comment by VBeytok** [comment]
It will probably never happen. The package was last updated and published five years ago, and it seems like they went [bankrupt](https://github.com/lodash/lodash/pull/5649#issuecomment-1722358483)

**Comment by hannahcancode** [comment]
It looks like it's fixed in `lodash`, and the maintainers of lodash suggest not using the per method packages such as `lodash.templates` anymore:
https://lodash.com/per-method-packages
https://github.com/lodash/lodash/issues/5851#issuecomment-2069634388

Would it be possible to move to `lodash`?
