### ISSUE TITLE
Child command description showing up in parent `--help`

### ISSUE THREAD

**Issue by DavidWells** [oclif/oclif#128]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------

I have a sub command (short) `description` showing up at the description of the parent command.

```
 sites      create a site
```

should be:

```
 sites      Handle site operations
```

![image](https://user-images.githubusercontent.com/532272/41444873-a904ba7a-6ffa-11e8-918f-d5fcab441f04.png)

It should be showing:

```
COMMANDS
  functions  Manage netlify functions
  help       display help for netlify-cli
  login      Login to account
  logout     Logout of account
  sites      Handle site operations
```

What is the expected behavior?
------------------------------

The `index.js` of the parent folder should be the message displayed in `--help` not the first child message

PS
------------------------------

Love the project! Looks pretty sweet!

**Comment by DavidWells** [comment]
It looks like folders are read alphabetically and the first description found (in this case `commands/sites/create/index.js` is used instead of the description of `commands/sites/index.js` (the parent)

**Comment by jdxcode** [comment]
I assume there is a `./src/commands/sites/create/index.js` file as well, right?

**Comment by jdxcode** [comment]
I'm not actually seeing this behavior. I made an [example repo here](https://github.com/jdxcode/oclif-help-example) which should have the same setup but it seems to output correctly:

```
$ ./bin/run --help
example multi-command CLI built with javascript

VERSION
  @oclif/example-multi-js/1.8.3 darwin-x64 node-v10.4.1

USAGE
  $ example-multi-js [COMMAND]

COMMANDS
  goodbye  Describe the command here
  hello    Describe the command here
  help     display help for example-multi-js
  sites    sites/index

```

**Comment by jdxcode** [comment]
You might want to check if there is a loose `oclif.manifest.json` hanging around. That can mess things up.

**Comment by jdxcode** [comment]
It's created (and deleted) in the `prepack` step into the root of the CLI. Its purpose is to make it faster once a CLI is released so it doesn't have to `require()` each command to get the help information for all the commands. If it exists in the root the CLI will read that and not what is actually in the commands. It might be named `.oclif.manifest.json` if you used an older version of the generator.

Given that several commands seem to be missing it looks to me like that might be what's going on. Another possibility is it could not be requiring `./commands/sites/index.js`. I assume the command actually works though, right?

**Comment by DavidWells** [comment]
This is the repo https://github.com/DavidWells/cli

I just cloned it down into a separate directory and am seeing the same results when running `/bin/run --help`

**Comment by jdxcode** [comment]
figured it out, it wasn't sorting at all so there was some arbitrary-ness with the command loading. This patch should fix it.

**Comment by DavidWells** [comment]
@jdxcode dude you rock!

Thanks for helping me so quickly 👏

**Comment by jdxcode** [comment]
there could still be some weirdness here between cross-plugin commands. Like if one plugin defined `sites:create` and a later one defined `sites`... I think I'm going to punt on this for now at least unless someone points out odd behavior
