### ISSUE TITLE
Signed .node binaries with oclif

### ISSUE THREAD

**Issue by otaviojacobi** [oclif/oclif#1331]
Hello all! I would like raise a issue we have been facing with oclif for quite a few years and a proposed solution / wip PR (sorry for the slightly long description).

We have a CLI built with oclif, and one issue we face is that we bundle with our CLI with several platform specific .node binaries that are built on our CI, and in order to have them properly signed on macOS we have had to mantain a patch/fork of oclif, which has been a pain to mantain (every bump may contain several changes etc). The reason why this was needed is the following:
1. We build & sign our our `.node` files
2. We call `npm run pack:macos`
3. npm run pack:macos calls `npm install --production` [here](https://github.com/oclif/oclif/blob/main/src/tarballs/build.ts#L147)

 Item 3) disrupts our signed `.node` files as `npm i` will overwrite these files signing. We can't also sign the files afterwards as these wouldn't be packed on the tgz. 

My proposal of improvement here is quite simple, we could add a flag on pack:macos that allows to only `prune` the `node_modules` directory instead of (re)-installing them, this will only delete the not needed dependencies but do require you to have them installed previously. This is also a nice feature as in several CI workflows you might already have node_modules there (from your tests or something else) and `npm prune --production` will run faster than npm i.
Of course, this would also require you to have a node_modules folder and we copy it over similar to what is done to package-lock/shrinkwrap

Here is a very simple PR (still WIP) for validating the idea: https://github.com/otaviojacobi/oclif/pull/1/files

Thanks for all the contribution here! It is great to see oclif evolving :)

**Comment by mdonnalley** [comment]
@otaviojacobi One of the challenges with the `pack` commands is supporting all the package managers (npm, pnpm, yarn 1-4, etc.) and support all the custom things that people want to have happen during the build step.

While a `--prune-only` flag might work for npm users, what would it do for all the others? And then it also opens the door to adding flags for every custom step that user might want. So I think the solution here needs to be more generalizable. 

But I think there might be a way for you to get what you want without any modifications to oclif. There's a [`pretarball` step ](https://github.com/oclif/oclif/blob/4.5.4/src/tarballs/build.ts#L151) that will run whatever you have in the `pretarball` script in your package.json. This gets run after the dependencies are added and before the tarball is created - so if I think it might work for your use case.

**Comment by otaviojacobi** [comment]
> So I think the solution here needs to be more generalizable.

It was my feeling aswell, that's why I actually opened the issue rather than PRing directly.

Thank you! I think using `pretarball` will quite likely do the trick.
