### ISSUE TITLE
Get Flags interface from the extending Command class

### ISSUE THREAD

**Issue by lsliwaradioluz** [oclif/oclif#1347]
**Is your feature request related to a problem? Please describe.**
I am defining flags in my `XYZ extends Command` class. Then, in the class, I can use `this.parse` to get typed flags. I like that.

![image](https://github.com/oclif/oclif/assets/39009379/de684fa7-3e78-4e76-9125-098083f4fd50)

**Describe the solution you'd like**
I would like to use the type of the flags outside of my XYZ class. For example, while defining external utility methods that are imported and used in the XYZ class.

**Describe alternatives you've considered**
At the moment, I can achieve the desired result by importing a deeply nested `OutputFlags` type from `@oclif/core/lib/interfaces/parser.js`.

```ts
import type { OutputFlags } from "@oclif/core/lib/interfaces/parser.js";
import type XYZ from "../../commands/xyz.js";

type Flags = OutputFlags<typeof XYZ.flags>;
```

**Additional context**
Is the way I've shown above the only one? If yes, can types such as `OutputArgs` and `OutputFlags` and their likes be exported directly from `@oclif/core`?

**Comment by mdonnalley** [comment]
You're looking for `Interfaces.InferredFlags`: https://github.com/oclif/core/blob/main/src/interfaces/flags.ts

```typescript
import {Interfaces} from '@oclif/core'
export type Flags = Interfaces.InferredFlags<typeof MyCommand.flags>
```

**Comment by lsliwaradioluz** [comment]
Thank you @mdonnalley
