### ISSUE TITLE
Debug on VSCode ?

### ISSUE THREAD

**Issue by lbngoc** [oclif/oclif#135]
Hi, I try to setup debugging my custom CLI in VS Code but could not get it working.
Could you provide me some instructions ?

**Comment by CallumDenby** [comment]
Hey @lbngoc 

You can debug your CLI in VS Code by creating a `launch.json` file in the `.vscode` folder in your project.

The contents of your `launch.json` file should look something like this

```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/bin/run",
      "args": [
        "--name",
        "Callum",
        "--force",
        "argument"
      ]
    }
  ]
}
```

This will automatically run the CLI with the arguments provided and attach to the process.

**Comment by lbngoc** [comment]
Thank you! It's working great.

**Comment by renewooller** [comment]
Any tips for debugging via ts-node on vscode? /bin/run is javascript

**Comment by renewooller** [comment]
my bad -what you gave above works fine

**Comment by ws93** [comment]
@renewooller How did you get that to work? I have my CLI in typescript and the breakpoint will hit `run()` in `index.ts` but it didn't go into the imported functions inside `run()`

**Comment by bitjson** [comment]
For those landing here later – here's a working configuration for debugging Mocha tests:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug All Tests",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--opts",
        "${workspaceFolder}/test/mocha.opts",
        "--timeout",
        "999999",
        "${workspaceFolder}/test/**/*.test.ts"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Active Test",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--opts",
        "${workspaceFolder}/test/mocha.opts",
        "--timeout",
        "999999",
        "${file}"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

**Comment by zrrtcs** [comment]
I just use the default JavaScript Debug Terminal and `run node --inspect ./bin/run`
![image](https://user-images.githubusercontent.com/1638687/133194059-2d243944-49dd-4b3e-adb0-2e849dc8e811.png)

**Comment by calebAtIspot** [comment]
@bitjson the starter template doesn't have a mocha.opts file, what are the contents of that file?

**Comment by calebAtIspot** [comment]
Nevermind, I figured it out how to run the tests in VSCode: https://github.com/oclif/oclif/issues/997
