### ISSUE TITLE
No such file error `installer.exe` for Windows pack command

### ISSUE THREAD

**Issue by jonaslagoni** [oclif/oclif#1375]
**Is this a bug with the oclif CLI? Or the oclif framework?**

Oclif CLI

**Describe the bug**
We recently upgraded the Oclif dependencies to the newest version, but are running into build problems on Windows with errors such as below (all other pack commands works):
```
$ npm run pack:windows

> @asyncapi/modelina-cli@4.0.0-next.27 pack:windows
> oclif pack win

oclif: gathering workspace for modelina to F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\modelina
oclif: will build 2 targets in parallel
oclif: building target modelina-v4.0.0-next.27-981823c-win32-x64.tar.gz
oclif: copying workspace F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\modelina F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\win32-x64\modelina
oclif: building target modelina-v4.0.0-next.27-981823c-win32-x86.tar.gz
oclif: copying workspace F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\modelina F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\win32-x86\modelina
    Error: ENOENT: no such file or directory, stat 'F:\project-to-be-named\generator-model-sdk\modelina-cli\tmp\windows-x86-installer\installer.exe'
    Code: ENOENT
```

This is across own machine and GitHub CI environment, and I have looked through all the issues here and in core to try and figure out what the problem could be...

Checkout the CI run logs here: https://github.com/asyncapi/modelina/actions/runs/8647305531/job/23708459005

**To Reproduce**

1. Clone https://github.com/asyncapi/modelina/tree/next/
2. Run: `npm ci`
3. Run: `npm run build:prod`
4. Run: `cd modeline-cli`
5. Run: `npm run pack:windows`
6. See the error

**Expected behavior**
I expected it to successfully pack the CLI for Windows.

**Your Environment (please complete the following information):**

- Full project: https://github.com/asyncapi/modelina/tree/next/modelina-cli
- `oclif` version: `^4.8.5`
- OS & version: `Windows 11 Pro` and CI running `Windows Server 2022`
- Node: `v18.16.0`
- 7-Zip: `24.04 (x64)`
- NSIS: `2.51`
- grep (GNU grep): `3.1`
- Shell/terminal & version: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Additional context**
I have tried looking through all the open and closed issues here and under core, with no luck of related issues and everything worked with the old Oclif version.

I am kinda out of ideas what to check or try by now, any suggestions are appreciated 🙏

**Comment by mdonnalley** [comment]
@jonaslagoni What version of oclif was working for you?

Also, after running `npm run build:prod`, I don't have a `modeline-cli` directory:

```
PS C:\Users\circleci> git clone https://github.com/asyncapi/modelina.git
Cloning into 'modelina'...
remote: Enumerating objects: 15708, done.
remote: Counting objects: 100% (3710/3710), done.
remote: Compressing objects: 100% (1151/1151), done.
remote: Total 15708 (delta 2962), reused 2880 (delta 2508), pack-reused 11998
Receiving objects: 100% (15708/15708), 14.86 MiB | 8.59 MiB/s, done.
Resolving deltas:   7% (781/11133)
Resolving deltas: 100% (11133/11133), done.
Updating files: 100% (1434/1434), done.
PS C:\Users\circleci> cd modelina
PS C:\Users\circleci\modelina> npm ci
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated @hyperjump/json-schema-core@0.28.5: This package was rolled into @hyperjump/json-schema as of v1.0.0

added 995 packages, and audited 996 packages in 3m

146 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\circleci\modelina> npm run build:prod

> @asyncapi/modelina@3.4.7 build:prod
> npm run build:cjs && npm run build:esm && npm run build:types


> @asyncapi/modelina@3.4.7 build:cjs
> tsc


> @asyncapi/modelina@3.4.7 build:esm
> tsc --project tsconfig.json --module ESNext --outDir ./lib/esm


> @asyncapi/modelina@3.4.7 build:types
> tsc --project tsconfig.json --declaration --emitDeclarationOnly --declarationMap --outDir ./lib/types

PS C:\Users\circleci\modelina> cd modeline-cli
cd : Cannot find path 'C:\Users\circleci\modelina\modeline-cli' because it does not exist.
At line:1 char:1
+ cd modeline-cli
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\circleci\modelina\modeline-cli:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

```

**Comment by jonaslagoni** [comment]
https://github.com/asyncapi/cli is the reference project that it Modelina CLI was created from, and I then upgraded to the newest Oclif dependencies here: https://github.com/asyncapi/modelina/pull/1923/files#diff-3e00a0703dfe8d8964cdf85488ae649b3b8a5febaf94319e05fbf9c2b58dab0c

It had:
- "oclif": "^3.7.3"
- "@oclif/core": "^1.26.2",
- "@oclif/plugin-not-found": "^3.1.1",

I see that the [AsyncAPI CLI is running the following successfully](https://github.com/asyncapi/cli/blob/f040d758807e86019e85f9387c07b50077007a5b/package.json#L39):
- "oclif": "^4.2.0",

So it might be `@oclif/core` that is the problem 🤔

**Comment by mdonnalley** [comment]
Okay, here's what I've found. The `makensis` step fails silently (I know, not great) with this:

```
makensis tmp/windows-x86-installer/modelina.nsi

Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "tmp/windows-x86-installer/modelina.nsi" (ACP)
File: failed opening file ".\client\node_modules\@asyncapi\modelina\modelina\node_modules\@asyncapi\modelina\modelina\node_modules\@asyncapi\modelina\modelina\node_modules\@asyncapi\modelina\windows-x64-installer\bin\modelina"
Error in script "tmp/windows-x86-installer/modelina.nsi" on line 33 -- aborting creation process
```

Looking at the provided file path, I'm wondering if you've introduced some sort of circular dependency? [This](https://github.com/asyncapi/modelina/blob/next/modelina-cli/package.json#L10) in particular looks suspicious to me

**Comment by mdonnalley** [comment]
>Anyway I can make it show that silent fail?

Unfortunately, not. I got that by manually running `npm pack:windows` followed by `makensis tmp/windows-x86-installer/modelina.nsi`

**Comment by jonaslagoni** [comment]
Changing the dependency to one of the released versions indeed fixed the problem, guess the problem lies with `makensis` since both Linux and MacOS builds works completely fine 🤔 

Thanks for taking a look @mdonnalley 🙇 Dont see how this is an Oclif problem so closing the issue 🙂
