### ISSUE TITLE
Node v20.12.2 breaks windows CLI

### ISSUE THREAD

**Issue by arthurfiorette** [oclif/oclif#1376]
https://nodejs.org/en/blog/release/v20.12.2#2024-04-10-version-20122-iron-lts-rafaelgss

https://github.com/nodejs/node/commit/69ffc6d50d disabled execution of `.cmd` and `.bat` files with `child_process.spawn`, which breaks oclif's `dev.cmd` and `bin.cmd` scripts to be run on windows.

**Comment by arthurfiorette** [comment]
I managed to fix it by simply removing both `.cmd` files. I'm not sure if they previously served a specific purpose or were just there to simplify compatibility with Windows; more information is needed.

[Here's the PR if someone wants](https://github.com/kitajs/kitajs/pull/423/files)

**Comment by drewbitt** [comment]
Also `18.20.2` and `21.7.3`

**Comment by arthurfiorette** [comment]
not stale

**Comment by mdonnalley** [comment]
@arthurfiorette if it's not stale, can you answer my original question:

>can you elaborate on what's not working? Is it that windows users aren't able to execute bin/dev.cmd and bin/run.cmd locally? Or is it that the windows installer (created by oclif pack win) doesn't work?

**Comment by arthurfiorette** [comment]
Oh sorry!

After node v20.12.2, nodejs enable execution of .cmd files only under a flag. This means that all package managers (npm, yarn, pnpm...) also cannot execute `.cmd`. I didn't testes with the `oclif pack win` command, but locally it cannot be executed.

You can simply test this out by switching to `v20.12.2`+ and creating a new CLI.

**Comment by mdonnalley** [comment]
@arthurfiorette how are you running the .cmd files?

I'm not able to repro with these steps
- install node 20.12.2
- `oclif generate my-cli`
- `cd my-cli`
- `bin\dev.cmd hello world`

My understanding of the node change is that it only applies to spawning `.cmd` and `.bat` but there's no where in newly generated CLIs where we spawn the .cmd files.

**Comment by mdonnalley** [comment]
@arthurfiorette What kind of fix do you have in mind here? I don't think there's anything addressable here since we're just providing the .cmd files - it's other people's responsibility to use them correctly

**Comment by arthurfiorette** [comment]
In windows, when there's a `dev.js` and `dev.cmd`, the `cmd` file is preferred over the `.js`, so it will break forever until we start shipping new versions without the `.cmd` files.
