### ISSUE TITLE
error isbinaryfile@5.0.2: The engine "node" is incompatible with this module. Expected version ">= 18.0.0". Got "16.15.1"

### ISSUE THREAD

**Issue by mochj12** [oclif/oclif#1382]
install user plugins  show this error
 how to resolve  it？

env： node 16.15.1

expect use node 16+

**Comment by JensAstrup** [comment]
Node 16 support ended ~7 months ago, and looking at the tests that run here I suspect ofclif doesn't support LTS versions any longer than would be expected

**Comment by kurtaking** [comment]
TL;DR - @mochj12, I don't think you are going to get `oclif` to work with Node 16. 

> Node 16 support ended ~7 months ago, and looking at the tests that run here I suspect ofclif doesn't support LTS versions any longer than would be expected

@JensAstrup, you are right and that's indicated by the `engines.node` value in [package.json file](https://github.com/oclif/oclif/blob/7e2a62401053061f189404b34b3670013c8f72b5/package.json#L71). The engines field defines what version of node the package can run on.
