### ISSUE TITLE
Node package recommendation question

### ISSUE THREAD

**Issue by bcomnes** [oclif/oclif#140]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Documentation "bug" possibly.

What is the current behavior?
-----------------------------

It is advised that one can simply add the node package to the deps, and users will be running the latest node.  This doesn't seem totally correct though.

> You can add the node package to your CLI to ensure users are on Node 8.

This will only be true when your cli is run from a script field or a tool like npx, not when installed globally or used through the shebang bin file.

What is the expected behavior?
------------------------------
The current wording makes it sound like a generalized solution when it isn't.  Perhaps we should clarify where this works and doesn't work?

**Comment by sourabh1031** [comment]
@jdxcode please review my previous pr so that i can send pr for this one.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
