### ISSUE TITLE
example: negative tests

### ISSUE THREAD

**Issue by whitlockjc** [oclif/oclif#142]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
I want to be able to write negation tests, something that executes a command that fails argument/flag validation and then use `stderr` _(or `stdout`)_ as part of the test to ensure my argument/flag definitions are as expected.  This could be me not doing things right, or not finding the right documentation, but I don't see this in any documentation or the examples.

What is the current behavior?
-----------------------------
Unfortunately, any type of negation test _(not passing a required argument)_ does not populate `stderr` or `stdout` and I end up with something like this when using `expect(ctx.stderr)`:

```
AssertionError: expected '' to include '...'
```

Here is an example:

```js
// ...
  test.stderr()
    .command(['validate'])
    .exit(2)
    .it('require LOCATION argument', ctx => {
      expect(ctx.stderr).to.contain('Error: Missing 1 required arg:')
      expect(ctx.stderr).to.contain('location  The path/URL to the OAS document being validated')
      expect(ctx.stderr).to.contain('See more help with --help')
    })
// ...
```

What is the expected behavior?
------------------------------
I would expect that any invocation of my command would populate `stdout` and/or `stderr`, even the ones that go down the error path.  _(This seems to happen for missing required arguments and too many arguments.)_

**Comment by whitlockjc** [comment]
It also seems that if you attempt to write a test for `--help`, that `exit(0)` is required in your `test` chain whereas a successful invocation of the command without `--help` does not.  That is unexpected as well.

**Comment by whitlockjc** [comment]
Example of the above:

```js
// ...
test.stdout()
    .command(['validate', '--help'])
    .exit(0) // I'm not sure why this is required as it's not for non-help command invocations
    .it('print expected output', ctx => {
      expect(ctx.stdout).to.equal(helpOutput)
    })
// ...
```

**Comment by whitlockjc** [comment]
And now that I've stopped trying to do negation tests, I'm seeing that when mocking `stderr` and `stdout`, different invocations of the same test produce different results.  Sometimes the test passes due to the test output matching as expected and others there are no content in `stderr` and/or `stdout` and the tests fail because `'' !== expectedOutput`.  I'm really wondering if `@oclif/test` is working as expected.

**Comment by whitlockjc** [comment]
I ended up moving away from `@oclif/test` and writing my own function for driving my CLI for testing: https://github.com/whitlockjc/oval/blob/master/test/commands/validate.test.js  This isn't one of those _"Nevermind, I moved away from this"_ but more an example of what I wanted to do and how I ended up doing it.

**Comment by SeyZ** [comment]
+1
@whitlockjc can you share your workaround code?

**Comment by whitlockjc** [comment]
If you look at [executeOval](https://github.com/whitlockjc/oval/blob/master/test/commands/validate.test.js#L44) in the link above, you'll see that instead of using the `oclif` test suite, I wrote my own executor so that I could test all scenarios, successful and failing.

**Comment by philsturgeon** [comment]
Sorry to bump, but is everyone just using the workaround from @whitlockjc or is there another solution.

**Comment by adrianthedev** [comment]
I feel that there should be a proper `stderr` object here to test.

**Comment by the-glima** [comment]
I've also moved away from `@oclif/test` (and Mocha) for the same reason as @whitlockjc.
I'm using Jest instead, now I'm able to test negative tests: https://martianwabbit.com/2018/05/25/testing-oclif-with-jest.html

**Comment by sthuber90** [comment]
@whitlockjc Is test coverage working for the command with your solution? Also are you able to stub or mock methods that are part of a command with your method?

**Comment by whitlockjc** [comment]
@sthuber90 The approach I'm taking is documented above.  It working just fine.

**Comment by RasPhilCo** [comment]
We use fancy-test's `catch` https://www.npmjs.com/package/fancy-test#catch

**Comment by Dylanlan** [comment]
I also ran into this issue using mocha, and would appreciate built-in `stderr` functionality.

The workaround from @whitlockjc seems to use exec from `child_process` on a hardcoded path to the `bin` folder, which I'd personally prefer not to do, and also would rather not switch to jest. 

For now I've just been testing errors by running the commands programmatically, which also doesn't seem ideal: https://oclif.io/docs/running_programmatically

**Comment by RasPhilCo** [comment]
I'd test it this way:
```
  test
  .stderr()
  .command(['validate'])
  .catch(ctx => {
    expect(ctx.message).to.contain('Missing 1 required arg:')
    expect(ctx.message).to.contain('location  The path/URL to the OAS document being validated')
    expect(ctx.message).to.contain('See more help with --help')
  })
  .it('requires LOCATION argument')
```

**Comment by sthuber90** [comment]
I use jest for testing and the following worked well enough for me:
``` javascript
  let stdout: string[]
  let stderr: string[]

  beforeEach(() => {
    stdout = []
    stderr = []

    jest.spyOn(process.stdout, 'write').mockImplementation(val => stdout.push(val) > -1)
    jest.spyOn(process.stderr, 'write').mockImplementation(val => stderr.push(val) > -1)
    jest.spyOn(console, 'error').mockImplementation(val => stderr.push(val) > -1)
    jest.spyOn(console, 'log').mockImplementation(val => stdout.push(val) > -1)
    jest.spyOn(console, 'info').mockImplementation(val => stdout.push(val) > -1)
    jest.spyOn(console, 'warn').mockImplementation(val => stdout.push(val) > -1)
  })
  
  test('run test that fails', async () => {
    try {
      await run()
    } catch (err) {
      expect(err.oclif.exit).toBe(1)
      expect(stderr.toString()).toBe('Ups')
      expect(stdout.toString()).toBe('')
    }
  })
```

**Comment by oleoneto** [comment]
@RasPhilCo 's approach seems to be the way to get this to work correctly without using any other external test suite. Also, if your linter complains about passing `ctx` to `catch`, you could just rename the argument to `error`.

**Comment by dreadnautxbuddha** [comment]
> I'd test it this way:
> 
> ```
>   test
>   .stderr()
>   .command(['validate'])
>   .catch(ctx => {
>     expect(ctx.message).to.contain('Missing 1 required arg:')
>     expect(ctx.message).to.contain('location  The path/URL to the OAS document being validated')
>     expect(ctx.message).to.contain('See more help with --help')
>   })
>   .it('requires LOCATION argument')
> ```

Thanks @RasPhilCo . After hours of looking for solutions, this worked for me.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
