### ISSUE TITLE
Snake-case for long flag names

### ISSUE THREAD

**Issue by beshanoe** [oclif/oclif#144]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

Sometimes I need to define a flag with a long name, and I use camelCase for the flag name, but I would like it to be used in CLI as snake-cased. I think it's quite common usecase. For example
```ts
import {Command, flags} from '@oclif/command'

export default class Hello extends Command {
  static description = 'hello command'

  static flags = {
    help: flags.help({char: 'h'}),
    someLongFlagName: flags.boolean({ snakeCase: true }), // Or it can be formatFn
  }

  async run() {
    const {args, flags} = this.parse(Hello)
    // ...
  }
}
```
```
$ ./bin/run hello -h
hello command

USAGE
  $ ff-cli-test hello

OPTIONS
  -h, --help          show CLI help
  --some-long-flag-name
```

**Comment by jdxcode** [comment]
Why not just make it snake cased everywhere?

**Comment by beshanoe** [comment]
@jdxcode you mean like this?
```ts
import {Command, flags} from '@oclif/command'

export default class Hello extends Command {
  static description = 'hello command'

  static flags = {
    help: flags.help({char: 'h'}),
    'some-long-flag-name': flags.boolean(),
  }

  async run() {
    const {args, flags} = this.parse(Hello)
    if (flags['some-long-flag-name']) {
      // ...
    }
    // ...
  }
}
```
It's just not convenient to use and looks ugly :)
Anyway, having at least formatting function would be already good for such cases

**Comment by jdxcode** [comment]
Sorry but I don't agree that it looks ugly. This is the right approach IMO

**Comment by jdxcode** [comment]
I'm going to close as this isn't even possible with typescript
