### ISSUE TITLE
oclif-dev pack:win Command doesn't work

### ISSUE THREAD

**Issue by rishianand06** [oclif/oclif#145]
Do you want to request a *feature* or report a *bug*?    bug
-----------------------------------------------------

What is the current behavior?
-----------------------------
I am not able to build windows installer. 

Used **oclif-dev pack:win** command. 
First it gave error for makensis. So I installed NSIS on my windows machine.
Then error of **tar** command not found. So installed tar on my machine.

then following command is failed:

**tar -xzf D:/workdir/CLI/CloudGateway-Cli/tmp/test/cloud-gateway-cli-0.0.1.tgz**

`Error logs:`
> oclif-dev pack:win

oclif-dev: gathering workspace for testto D:\workdir\CLI\CloudGateway-Cli\tmp\test
tar (child): Cannot connect to D: resolve failed

gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now
Error: Command failed: C:/windows/system32/cmd.exe /q /s /c "tar -xzf D:/workdir/CLI/CloudGateway-Cli/tmp/test/cloud-gateway-cli-0.0.1.tgz"
    at makeError (D:/workdir/CLI/CloudGateway-Cli/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (D:/workdir/CLI/CloudGateway-Cli/node_modules/execa/index.js:277:16)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloud-gateway-cli@0.0.1 test: `oclif-dev pack:win`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloud-gateway-cli@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qgr9sm\AppData\Roaming\npm-cache\_logs\2018-08-01T10_41_21_603Z-debug.log

What is the expected behavior?
------------------------------
It should create MSI or EXE for my CLI.

Please mention your oclif and OS version.
 @oclif/dev-cli: "1.15.4"
My Machine - Windows 10

**Comment by Ceridan** [comment]
I have exactly same problem. Any workaround here?

--
@oclif/dev-cli: "1.22.0"
Windows 10

**Comment by rishianand06** [comment]
@Ceridan No man, I haven't found any solution for that. Finally I have to make npm package only.

**Comment by RasPhilCo** [comment]
Can't reproduce locally yet, what node version are you running?

**Comment by Ceridan** [comment]
@RasPhilCo My setup:

@oclif/dev-cli: "1.22.0"
Windows 10
Nodejs: 10.16.0 LTS

**Comment by DanRYoung** [comment]
As a workaround, I was able to generate a windows installer using the [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10#install-your-linux-distribution-of-choice). I installed WSL Ubuntu and the requisite packages used by `oclif-dev pack:win` (i.e. [installed nodejs](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions), and packages `sudo apt install nsis p7zip-full`). Using WSL, the installer builds just fine, and successfully installs on a Windows machine.

**Comment by chriso86** [comment]
Has this code base been abandoned?

It appears that this is because this command was probably only built and tested within a Linux environment, so it's likely not designed to run in Windows. Like DanRYoung mentioned above, you can successfully run this within a Linux environment.
Ironic as that may be.

**Comment by yanxiaodi** [comment]
Thanks @DanRYoung . Your post helps.👍
