### ISSUE TITLE
Fail to generate new CLI due to missing eslint file

### ISSUE THREAD

**Issue by Fryuni** [oclif/oclif#1470]
**Describe the bug**

Generating a brand-new CLI using `oclif generate` is failing with a missing eslint file.

**To Reproduce**

1. Run `yarn dlx oclif generate dctl`
2. Press enter on all questions to proceed
3. See error `Error: ENOENT: no such file or directory, open '.eslintignore.ejs'`

![image](https://github.com/oclif/oclif/assets/11063910/60a334b5-d62c-4ce5-99e7-077f7761c2b7)

Also tried with `pnpm dlx` and `npx`, and selecting `yarn` and `pnpm` as package manager. The same error shows up

**Expected behavior**

A new CLI should be generated

**Your Environment (please complete the following information):**

- `oclif` Version: 4.13.16
- OS & version: MacOS Sonoma
- Shell/terminal & version: zsh 5.9 (x86_64-apple-darwin23.0)

**Comment by mdonnalley** [comment]
@Fryuni I'm not able to reproduce this on my end. 

That `.eslintignore.ejs` [file](https://github.com/oclif/oclif/blob/main/templates/cli/shared/.eslintignore.ejs) should be included in the [templates](https://github.com/oclif/oclif/tree/main/templates) directory that oclif ships. So I'm wondering if you've got a bad install of oclif that didn't include that templates directory?

**Comment by mdonnalley** [comment]
@Fryuni I just published a new version that adds some debug logs. I'm hoping that that might help us out. 

can you try with oclif 4.14.0 and set the DEBUG env var to `oclif:*`
