### ISSUE TITLE
Customize options for oclif readme generate

### ISSUE THREAD

**Issue by WillDelish** [oclif/oclif#1479]
**Is your feature request related to a problem? Please describe.**
I am making a CLI tool that won't be on npm (just greating tarballs), so having the npm instructions to install in the `Usage` section of the generated `README.md` creates the wrong instructions for a user

**Describe the solution you'd like**
I would like to have the option to remove the `Ussage` part of `README.md` or provide my own custom string.

**Describe alternatives you've considered**
I could try using `sed` command in the prepack to just remove the npm install line before executing the `oclif tarballs`. I've looked around the docs and I see there's a way to override the `Usage` section for commands, but doesn't seem like there's a way to override the `npm install -g` section.

**Comment by mshanemc** [comment]
the instructions for that are here:
https://github.com/oclif/oclif/blob/15159fe7507203f557df18c870b3883198402c23/src/commands/readme.ts#L8

If you delete the 
`# Usage
`
from your README you should be able to avoid that OR manually set whatever you want
