### ISSUE TITLE
[Feature] flag.string passed but without value, aka `flags.booleanstring`

### ISSUE THREAD

**Issue by Alber70g** [oclif/oclif#148]
*feature* 
---------

I'd like to have a feature where I can make a `flag` be a:

1. `boolean` when not passed or passed without value (but with the option to have a default string value), or a 
2. `string` when passed with value.

Example:
```ts
public static flags = {
    dryRun: flags.booleanstring({
      char: "d",
      default: "bower-package.tar.gz",
      description:
        "When passed, it only creates a package but does not publish. " + 
        "You can provide a filename. " +
        "Default filename (when flag is passed) is 'bower-package.tar.gz'",
    }),
  };
```

Usage:
```bash
mycli
# dryRun === false

mycli --dryRun
# dryRun === 'bower-package.tar.gz'

mycli --dryRun='thepackage.tar.gz'
# dryRun === 'thepackage.tar.gz'
```

The second option is currently not possible.

**Comment by jdxcode** [comment]
It's not possible to build a flag parser that can do this while also supporting arguments the way we do

**Comment by Alber70g** [comment]
Which type of argument will not work the way you do?

**Comment by jdxcode** [comment]
if you had something like `mycli --dryRun foobar` it's impossible to know if `foobar` is a value for the flag or if it's another argument

**Comment by Alber70g** [comment]
What would be an alternative? Two flags?

**Comment by jdxcode** [comment]
yeah and that's a better UX design anyways. It's really confusing to have a flag behave in 2 different ways like that
