### ISSUE TITLE
Undeclared dependency

### ISSUE THREAD

**Issue by arcanis** [oclif/oclif#150]
Just tried oclif, and noticed that the `bin/run` script is using an undeclared dependency (`@oclif/errors`). It works because of the hoisting, but is susceptible to break.

**Comment by jdxcode** [comment]
This is not an issue

**Comment by arcanis** [comment]
I work on a JS package manager. I understand this is not an issue which causes a breakage **now**, but I can tell you this is an issue nonetheless, and it is susceptible to break 🙂 

> [...] avoid having it downloaded twice.

I'm not sure I understand, it won't cause it to be downloaded twice. In most scenarios the package managers will see that both packages can be satisfied by the same version and will deduplicate the package.

But that's moot anyway: if you depend on something not listed in your dependencies, expect it to break down the line.

**Comment by HosseinAgha** [comment]
@jdxcode,  
I wanted to ask your opinion on the [previous comment](https://github.com/oclif/oclif/issues/150#issuecomment-413890956).  
NodeJS package managers are evolving and they are starting to detect many important bugs that used to work correctly.  
Based on npm dependency spec you should add the packages that you `require` at runtime to your `package.json`'s `dependencies` or `peerDependencies` fields.  
You are currently relying on the `npm` or `yarn` hoisting mechanism for your package to work correctly which may break your package in the future versions of yarn and npm.  
To understand my point please take a look at the next generation node package managers and how they'll take the responsibility of dependency resolution:  
  - https://yarnpkg.com/lang/en/docs/pnp/
  - https://blog.npmjs.org/post/178027064160/next-generation-package-management
