### ISSUE TITLE
documentation site is down

### ISSUE THREAD

**Issue by ccfiel** [oclif/oclif#1500]
<img width="806" alt="SCR-20240728-ejtw" src="https://github.com/user-attachments/assets/62e74079-1a6b-4aef-b3a0-0f54330296c6">

**Comment by mdonnalley** [comment]
@ccfiel `ERR_CONNECTION_RESET` probably indicates that it's an error on your side. Maybe a misconfigured DNS or proxy server?

Either way, I'm able to access the site now. I'm going to close this for now.
