### ISSUE TITLE
-h doesn't work, only --help

### ISSUE THREAD

**Issue by AllanOricil** [oclif/oclif#1535]
**Is this a bug with the oclif CLI? Or the oclif framework?**

oclif framework

**Describe the bug**

![image](https://github.com/user-attachments/assets/fb5f5da2-d715-4b19-b00c-33ff90180646)

**To Reproduce**

1. Create an oclif project with v4
2. build it
3. link it
4. run `mycli -h`
5. verify it does not work
6. run `mycli --help`
7. verify it works

**Expected behavior**

-h flag should work

**Your Environment (please complete the following information):**

oclif/4.0.3 darwin-arm64 node-v18.18.0

GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

**Additional context**

```json
"dependencies": {
    "@oclif/core": "^4",
    "@oclif/plugin-help": "^6",
    "prettier": "^3.3.3"
  },
  "devDependencies": {
    "@oclif/prettier-config": "^0.2.1",
    "@oclif/test": "^3",
    "@types/chai": "^4",
    "@types/mocha": "^10",
    "@types/node": "^18",
    "chai": "^4",
    "eslint": "^8",
    "eslint-config-oclif": "^5",
    "eslint-config-oclif-typescript": "^3",
    "eslint-config-prettier": "^9.1.0",
    "husky": "^9.1.5",
    "lint-staged": "^15.2.0",
    "mocha": "^10",
    "oclif": "^4.9.0",
    "shx": "^0.3.4",
    "ts-node": "^10.9.2",
    "typescript": "^5"
  },
```

**Comment by mdonnalley** [comment]
By design, `-h` does not trigger help output. This gives developers the freedom to use that flag for other purposes. But if you want it to trigger help, then you can set the `additionalHelpFlags` in the oclif section of the package.json

https://oclif.io/docs/configuring_your_cli
