### ISSUE TITLE
Override Command name

### ISSUE THREAD

**Issue by hassankhan** [oclif/oclif#156]
What is the current behavior?
-----------------------------
Currently, `oclif` uses the file name for the command.

What is the expected behavior?
------------------------------
It would be nice if we could specify the name of the command within the Command class instead of using the file name.

Please mention your oclif and OS version:
`@oclif/command`: `1.5.0`
OS: darwin-x64 node-v8.11.1 (macOS High Sierra 10.13.6)

**Comment by jdxcode** [comment]
can you give a reason why?

**Comment by hassankhan** [comment]
I guess its not a major thing, but currently we have `src/commands/hello.ts` which default exports a class called `HelloCommand`. Our TSLint rules require that the [default export should match the file name](https://palantir.github.io/tslint/rules/match-default-export-name/), so it would be nice if `oclif` supported that use-case.

**Comment by jdxcode** [comment]
sorry but this would be difficult and I just don't think that's a compelling enough reason

**Comment by ivawzh** [comment]
Firstly, thanks for the awesome lib! 

I want to be able to group commands with special symbols. For examples:

```
db:create
db:migrate
db:drop
```
or

```
@db/create
@db/migrate
@danger/drop
```

I know there are `alias` at the moment, but they show the names in `--help` list as what I desire 😞
