### ISSUE TITLE
Load user plugins from a path instead of package.json

### ISSUE THREAD

**Issue by hassankhan** [oclif/oclif#157]
What is the current behavior?
-----------------------------
Currently, user plugins can only be loaded from a consuming project's `package.json` field.

What is the expected behavior?
------------------------------
It would be really awesome if we could specify a path to load plugins from instead.

Please mention your oclif and OS version.
`@oclif/command`: `1.5.0`
OS: darwin-x64 node-v8.11.1 (macOS High Sierra 10.13.6)

**Comment by jdxcode** [comment]
can you give more of an explanation of what you're looking to do? Is the plugins-plugin what you're after?

**Comment by hassankhan** [comment]
Essentially I wanted my CLI users to be able to load commands from a given folder, for example `app/Commands` in their project root. My CLI would also generate command stub classes there and I was hoping that I could then dynamically load them without having to update the `package.json` in the user's project. 

I didn't know about the `plugin-plugins` package, however since the "commands" I want to load are more project-specific than shareable, I'm not 100% sure it works for the use-case I had in mind. Still, it's definitely neat 👍
