### ISSUE TITLE
Use globs to exclude file types from being loaded as commands

### ISSUE THREAD

**Issue by hassankhan** [oclif/oclif#158]
What is the current behavior?
-----------------------------
Currently, all files specified under `oclif.commands` in `package.json` are loaded as commands. Unfortunately, this kind of breaks if you use co-located test files (i.e. `command.ts` and `command.spec.ts` in the same folder).

What is the expected behavior?
------------------------------
It would be really nice if `oclif.commands` supported glob patterns so we could include/exclude files from being loaded as commands.

Please mention your oclif and OS version.
`@oclif/command`: `1.5.0`
OS: darwin-x64 node-v8.11.1 (macOS High Sierra 10.13.6)

**Comment by jdxcode** [comment]
go ahead and put a PR in to add `.spec.ts`, we have similar logic for `.test.ts` already: https://github.com/oclif/config/blob/master/src/plugin.ts#L140
