### ISSUE TITLE
`oclif readme` generates broken README when extending `Help` class with constructor

### ISSUE THREAD

**Issue by kanadgupta** [oclif/oclif#1610]
**Is this a bug with the oclif CLI? Or the oclif framework?**

The `oclif` CLI

**Describe the bug**

`oclif readme` generates a broken README (i.e., ANSI codes everywhere) when extending `Help` class with a constructor.

**To Reproduce**

1. Generate a new CLI with `oclif generate`
2. Extend the default `Help` class, including a constructor ([example](https://github.com/kanadgupta/oclif-readme-test/blob/c91b70206725f213b05f17e0667f6f9c66200da7/src/help.ts))
3. Add the `helpClass` property to the `oclif` config ([example](https://github.com/kanadgupta/oclif-readme-test/blob/c91b70206725f213b05f17e0667f6f9c66200da7/package.json#L51))
4. Regenerate the README by running the following:

```
npm run build
npx oclif readme
```
5. Observe how the README appears broken due to all the ANSI codes ([example](https://github.com/kanadgupta/oclif-readme-test/commit/c91b70206725f213b05f17e0667f6f9c66200da7))

**Expected behavior**

I would expect the README to not contain ANSI codes

**Your Environment (please complete the following information):**

- `oclif` Version: 4.15.24
- OS & version: macOS 15.1
- Shell/terminal & version `zsh 5.9 (arm64-apple-darwin24.0)`
- Node version: v20.18.0

**Additional context**

N/A

**Comment by mdonnalley** [comment]
@kanadgupta if you change your example to this, it will work:

```typescript
import type {HelpOptions} from '@oclif/core/interfaces'

import {type Config, Help} from '@oclif/core'

export default class MyHelpClass extends Help {
  constructor(config: Config, opts?: Partial<HelpOptions>) {
    super(config, {...opts, hideAliasesFromRoot: true})
  }
}
```

The ansi characters were showing up because you weren't passing in the provided `opts` to super - which means that the `stripAnsi` option that the readme generator provides [here](https://github.com/oclif/oclif/blob/4.15.28/src/readme-generator.ts#L183) was ignored
