### ISSUE TITLE
Cannot run tests in a generated project in a Lerna/Yarn Workspaces repository

### ISSUE THREAD

**Issue by hassankhan** [oclif/oclif#162]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Report a bug.

What is the current behavior?
-----------------------------

I used the Oclif project generator to create a project, then moved it inside my [monorepo project][link-serverlize]. I also replaced the test tooling with Jest, which meant I could no longer use the test helpers. To get around this, I added a spy on `process.stdout.write()` and then [run the command][link-test]. If I remove the `catch` block, I receive the following error: 

```bash
TypeError: globby.sync is not a function
    at Plugin.get commandIDs [as commandIDs] (/[PROJECT_ROOT]]/node_modules/@oclif/config/lib/plugin.js:75:28)
    at Plugin._manifest (/[PROJECT_ROOT]]/node_modules/@oclif/config/lib/plugin.js:150:28)
    at <anonymous>

```

I've ensured that `globby` is definitely installed, and if I copy the same project outside of the monorepo and run `yarn`, it works fine.

[link-serverlize]: https://github.com/serverlize/serverlize
[link-test]: https://github.com/serverlize/serverlize/blob/develop/packages/cli/src/commands/hello.spec.ts

What is the expected behavior?
------------------------------

It should without throwing a `TypeError`.

@oclif/command: 1.5.0
@oclif/config: 1.7.0
Node: 8.11.4
Yarn: 1.9.4 
macOS: 10.13.6

Related issues?
---------------

This _might_ be related to #134

**Comment by jdxcode** [comment]
Sorry but this is an issue with your project not with oclif.

**Comment by hassankhan** [comment]
Thanks for the diagnostic help, I guess
