### ISSUE TITLE
Feature request: don't assume every project will be stored on Github

### ISSUE THREAD

**Issue by unikitty37** [oclif/oclif#174]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A feature.

What is the current behavior?
-----------------------------
When creating a new app (for example: `npx oclif single testapp`) I am prompted for Github owner and repository name.

What is the expected behavior?
------------------------------
I should be asked which service I am using before being asked for the owner username; at the least, I should be given a choice of Github, Bitbucket, GitLab, as well as an option to specify a private server (Github Enterprise, GitLab-CE etc — I guess this would require the base URL to the instance as a followup question).

A "none of the above" option which leaves `bugs`, `homepage` and `repository` blank might be useful, too.

In a totally ideal world, I would be able to set my default as an environment variable, or in a .rc file somewhere, so the defaults are correct each time.

The `repository` entry in the generated `package.json` should be explicit in specifying the server:

Server|repository
------|----------
Github|github:unikitty37/testapp
Github Enterprise|https://github.example.com/unikitty37/testapp
Bitbucket|bitbucket:unikitty37/testapp
GitLab|gitlab:unikitty37/testapp
GitLab-CE|https://gitlab.example.com/unikitty37/testapp

The `bugs` and `homepage` entries should default to the correct format for the services concerned (which should be a case of just replacing `github.com` with the service root — GitLab projects in a group will have an extra layer between username and app name, but that's probably more complication than needed, at least for an initial release…)

Currently, this can be worked around by manually editing `package.json` after the fact, but that's a fair bit of extra work for people not using Github. Github could remain the default service selection, meaning Github users have only one extra press of the Enter key in the app generation workflow.

I might be able to look at implementing this at some point in the future, but I'm a bit snowed under at the moment; would there be interest in adding this?

oclif 1.12.1; Mac OS X 10.14 (18A391)

**Comment by jdxcode** [comment]
I agree this would be ideal. I'm also reasonably ok with the status quo as all this does is set the field in package.json and create URLs to the code in the readme and fixing won't be trivial. That readme code should also work with gitlab/etc. (right now it just hides the url if it isn't github.com)

I'd happily accept a PR thiugh

**Comment by moulikcipherX** [comment]
hello @jdxcode ,
I have made changes in my local repository for this issue.
But I don't know how to check my changes?

**Comment by Raiondesu** [comment]
Why ask for all these different things at all? Isn't it easier to just accept a repository URL?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
