### ISSUE TITLE
Use lerna instead of so many repositories

### ISSUE THREAD

**Issue by pksunkara** [oclif/oclif#176]
Generally, when people are writing something like this, due to different repositories for each npm package needed, the common convention is to use lerna because otherwise it will be hell for maintainers once the project grows a bit.

We at @storybooks use it. You can use git-subtree to merge all the repos into a single monorepo without losing any git history. I am willing to help you guys out with it if needed.

**Comment by jdxcode** [comment]
I'm not interested in moving to a monorepo
