### ISSUE TITLE
[Feature Request] community plugins?

### ISSUE THREAD

**Issue by natzcam** [oclif/oclif#178]
[Feature Request]

Is there any are where we can shamelessly plugin a custom plugin? I made a very simple one, that might be useful to someone else.

https://github.com/natzcam/conf-cli

**Comment by jdxcode** [comment]
Sure! go ahead and create a new list for community plugins here:
https://github.com/oclif/oclif.github.io/blob/docs/docs/plugins.md#useful-plugins
