### ISSUE TITLE
any sense in porting oclif to Python?

### ISSUE THREAD

**Issue by barkanido** [oclif/oclif#180]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Just ask a question.

What is the current behavior?
-----------------------------
this project depends on nodejs, right?

What is the expected behavior?
------------------------------
Do you think that there is any sense in porting oclif to python, to make it more 'native' in Linux systems?

**Comment by jdxcode** [comment]
We're very happy with node.

**Comment by mwoods79** [comment]
@barkanido you should read the FAQ https://oclif.io/docs/faqs#why-node it references an article about the history of the Heroku CLI https://blog.heroku.com/evolution-of-heroku-cli-2008-2017

Also, making a CLI that is more 'native' on Linux might not a good move for our Windows and MacOS users.
