### ISSUE TITLE
Display help when no parameters given

### ISSUE THREAD

**Issue by unikitty37** [oclif/oclif#183]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Request a feature.

What is the current behavior?
-----------------------------
If a command is run without providing any parameters, it does not display the help.

What is the expected behavior?
------------------------------
oclif 1.12.4; Mac OS X 10.13.6 (17G65)

It should be possible to have a command display its help as the default behaviour. While this can probably be manually added to the command (but I'm struggling to find how to do it — see below :) it would be handy to be asked if I want this when I'm creating the command.

If the documentation tells you how to trigger the help manually, I apologise, but I haven't managed to find it.

I've tried this:

```js
import HelpCommand from '@oclif/plugin-help/lib/commands/help'

async run() {
    if (process.argv.length <= 2) {
      HelpCommand.run()
      process.exit()
    }

    const {argv: files, flags} = this.parse(Mkvshrink)

    …
}
```

but the help does not display. The idea is to display the help if the user has just typed the command in without any parameters, since it doesn't do anything useful in that case.

**Comment by ken-centrality** [comment]
`this._help()` doesn't seem to exist in the `Command` class. How do we achieve this in version 3?

**Comment by smeijer** [comment]
`this._help` does also not exist in hooks. I'd like to show help from the `command_not_found` hook. Is that something we can do?

**Comment by smeijer** [comment]
Oh sweet, we can just import `{ run }` from the entry file, and invoke that. Don't mind me 😅 .

```ts
// hooks/not-found.ts
import { run } from '../index'

export default async function notFound(this: any) {
  await run(['help'])
  process.exit(0)
}
```

**Comment by mon-jai** [comment]
For `@oclif/core` v2+, use the following instead,

```js
// "Root index" command
await new (await loadHelpClass(config))(config).showHelp([])

// Sub-command
await new (await loadHelpClass(config))(config).showHelp(["sub-command-name"])
```

Borrowed from: https://github.com/oclif/plugin-help/blob/6.0.12/src/commands/help.ts
