### ISSUE TITLE
Support for space-separated subcommands

### ISSUE THREAD

**Issue by borekb** [oclif/oclif#186]
Hi, we're building a CLI on oclif and first let me thank you for it: it's an awesome project and I wish we knew about it earlier :) Really great stuff!

One thing that's important for us is to have space-separated subcommands ("topics") like many other CLIs, e.g., `git`, `npm`, `wp`, `docker`, `kubectl`, `gcloud`, ... I was a bit surprised that oclif doesn't support them and then found this [FAQ](https://oclif.io/docs/faqs#why-does-oclif-use-colon-separated-commands-can-it-support-space-separated):

> Short answer is that space-separated will never be supported. Longer answer is it's not possible with the way we support topics and arguments.
>
> The major issue has to do with topic-commands. In oclif, we support topics as commands such as heroku config. There are other commands underneath heroku config like heroku config:get. If we used space separated arguments, this could be heroku config and heroku config get. However if heroku config also expected an argument, there would be no way for the command parser to tell whether or not the second argument is a command or an argument.
>
> Some CLIs don't support topic-commands which is how this is possible for those.
>
> We also feel that using colon-separated arguments is better CLI UX anyways. It helps the user know which arguments are the command and which are arguments to that command. It helps them find what they need in the help more directly.

Is there any way you would reconsider? CLIs with space-separated subcommands are common, not causing any issues in practice & oclif is an awesome CLI framework that could support this pattern. If you agree, we could explore how to support it and contribute the functionality back.

**Comment by jdxcode** [comment]
I won't be able to spend any time on it myself. I may be able to look into it a bit though to see what could be done here.

I think we would need to modify the main command from @oclif/command to use some custom logic instead of using config.runCommand(). OR we could modify config.runCommand() to take an array. Ditto for config.findCommand() I think.

That's just from my memory though. If I get some time to dig in I can come up with a more fleshed out plan.

If we were to do this I'd prefer to add the functionality in via a plugin. I don't think that's possible today, but we could probably add simple primitives to make it possible.

**Comment by borekb** [comment]
We have a working version internally, it is a small change in two packages: `@oclif/command` and `@oclif-config`. I guess we should open two separate pull requests, right?

**Comment by jdxcode** [comment]
glad to hear you were able to figure it out! yeah, it'll require 2 PRs

**Comment by borekb** [comment]
Pull requests submitted:

- https://github.com/oclif/command/pull/51
- https://github.com/oclif/config/pull/64

Any feedback appreciated :)

**Comment by borekb** [comment]
Colons are also hardcoded in packages like @oclif/dev-cli (at least the `readme` command) or @oclif/plugin-help. There would most likely need to be a config value in `package.json` as mentioned in https://github.com/oclif/config/pull/64#issue-230771879.

**Comment by RasPhilCo** [comment]
https://github.com/RasPhilCo/oclif-plugin-spaced-commands

I wanted to see if we could do this via a hook and we can (mostly-ish). This has the advantage of not needing to touch oclif manifests but comes with its own issues to be addressed if we go this route. Anyhow, consider this a spike and not a decision.

To try it out, as it's not published, follow these steps:

In your project package.json --
1) Add this line as a depenency
`"@oclif/plugin-spaced-commands": "rasphilco/oclif-plugin-spaced-commands",`
2) Add this line to oclif plugins
` "@oclif/plugin-spaced-commands",`

Then install and compile the plugin:
```
$ yarn
$ cd node_modules/@oclif/plugin-spaced-commands
$ yarn 
$ yarn prepare
$ rm -fr node_modules
$ cd ../../../
$ ./bin/run
```

**Comment by borekb** [comment]
@RasPhilCo Thanks for a detailed example. Monkey-patching is always an option though I have to say I'd prefer built-in support by oclif :) For example, currently, the [Introduction](https://oclif.io/docs/introduction.html) section in the docs is slightly misleading as you can't really model `git` in oclif (without resorting to monkey-patching or similar). I believe that adding support for space-separated commands to core would be a natural thing to do, especially since it doesn't seem to have many downsides.

**Comment by jdxcode** [comment]
If it's possible to be implemented via a plugin we won't be modifying the core. Adding the plugin should be the way to get this functionality.

**Comment by borekb** [comment]
Quite a few places seem to hardcode the colon, see for example [this search](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/oclif+%22%27:%27%22#9) (it's quick and dirty but already reveals usages in dev-cli, plugin-not-found and others). Can these, even theoretically, be monkey-patched by a plugin if the set of plugins used by a CLI is not known ahead of time?

I think it would be easier if each occurrence of `:` would be replaced by something like `this.config.commandSeparator`. This would still be a colon by default but I'd be able to customize it easily. It's a backwards-compatible change and maybe a 100 LoC patch across all the official packages, or slightly more with tests.

**Comment by tianlizhao** [comment]
Is there a good solution?

**Comment by lots0logs** [comment]
@jdxcode @RasPhilCo 

![bump](https://user-images.githubusercontent.com/4675662/52545817-156c6580-2d80-11e9-827f-a76cf885b657.gif)

**Comment by jdxcode** [comment]
@RasPhilCo is planning on looking at this a bit more at some point but we don't have an ETA or anything. It's definitely not as simple as just merging a PR. We want to make sure we support this the right way so we don't have to change anything later, but it is a goal of the project

**Comment by tcf909** [comment]
@jdxcode Do you or @RasPhilCo have any more details or feedback that might help someone in the community contribute to your efforts?

From what I can tell the plugin route has some issues that can't be overcome (Like plugins of plugins), since the space plugin itself is having to overwrite prototype functions (but can't guarantee that it will be able to do that for other plugins).

oclif is an awesome project, but this one thing kind of separates it from the pack. Hoping to get some direction from you guys so others don't waste their time trying to contribute for not.

**Comment by RasPhilCo** [comment]
I'm currently working on a rewrite of help. But to give some direction, for anyone wanting to take a shot:

1. oclif developers could declare something like `"usesSpacedCommands": true` in oclif's config in package.json.
2. Feel free to leverage what I've written in plugin-spaced-commands or come up with some other implementation entirely. (I build a tree and do tree search through ARGV but there could be a better way.)
3. Whatever implementation, it must work with plugin-help, plugin-which, plugin-not-found, plugin-plugins, plugin-commands.
4. Spaced commands will likely be incompatible with plugin-autocomplete as its now, but that's ok. We just need to make people aware of that fact.
5. We don't need an abstracted solution that will take any command delimiter (there are not a ton of valid characters anyhow).

**Comment by bodawei** [comment]
To be clear, I certainly support the notion of oclif itself being able to support subcommands delimited by spaces.  In the mean time, I created a shallow fork of the parts of oclif I need to supports spaces ( https://github.com/bodawei/alto-clif , https://github.com/bodawei/alto-command and https://github.com/bodawei/alto-plugin-help ).  I look forward to being able to replace the with pure oclif in the future.

**Comment by DavidWells** [comment]
Any updates on this? We'd also prefer a spaced sub command approach.

Thanks!

**Comment by yanivlllev** [comment]
Any updates on this?

**Comment by yanivlllev** [comment]
Any updates on this? Have anyone tried @RasPhilCo's [solution](https://github.com/oclif/oclif/issues/186#issuecomment-439596271) lately? I tried but encountered some typescript errors while trying to do `yarn`

**Comment by LassiterJ** [comment]
_

> "The major issue has to do with topic-commands. In oclif, we support topics as commands such as heroku config. There are other commands underneath heroku config like heroku config:get. If we used space separated arguments, this could be heroku config and heroku config get. However if heroku config also expected an argument, there would be no way for the command parser to tell whether or not the second argument is a command or an argument."

_

I have been implementing my own "topics" using the chain of responsibility design pattern.  

Lets say I have a new oclif multi-command app called mynewcli.
In my case, the first command is what I would consider the "topic".
$mynewcli [TOPIC] [COMMAND]

Topics take the preceding command, passes any following args to it, and executes the command. In my implementation, which is still in it's early stages, the only difference between a topic and a command is the location in the chain. This way, there is no need for oclif to determine if the second argument is a command or an arg because it treats them as the same.

Am I going down the wrong path here? Is there something i'm not seeing that will make me regret this design?

_Let me know if I need to make any clarifications_

**Comment by kmalfroid** [comment]
Any updates on this? We'd also prefer a spaced subcommand approach. Looking at most CLI tools, spaced subcommands are much more common. We don't want to force users to get used to a new approach using colons.

Thanks!

**Comment by Canuckaholic** [comment]
I know this is an old thread, but we recently implemented oclif and also wanted to use spaces instead of colons. Seems like developers get stuck in their ways and don't want to learn a new paradigm. *shrug* 

I installed https://github.com/tiagonapoli/oclif-plugin-spaced-commands which is a fork of RasPhilCo's plugin. It seems to work out of the box for commands, except that I noticed it didn't capture all of the colons in the help outputs, so I created a PR to override some more of the help methods:

https://github.com/tiagonapoli/oclif-plugin-spaced-commands/pull/5

**Comment by jmccann** [comment]
Another way I've seen to handle this is https://github.com/adobe/aio-cli/blob/master/src/index.js which extends `Command` with bits to allow spaces which you then reference in `run` (https://github.com/adobe/aio-cli/blob/master/bin/run)

I had found this from a blog at https://medium.com/adobetech/how-to-easily-create-clis-using-oclif-and-how-we-did-it-for-the-adobe-i-o-cli-e9eb888e9ec6

**Comment by Gi60s** [comment]
I don't know if this is genius or idiocy, but one option is the scan the commands directory to identify the potential commands then map space-separated commands to colon-separated commands and call the run function after mapping to the oclif command style.

## How to Make OCLIF Accept Spaces Instead of Colons

**First**

Create a file named `space-separated.js` and put it in your `bin` directory. Here is the code:

```js
const package = require('../package.json')
const fs = require('fs/promises')
const path = require('path')

const useTypeScript = 'typescript' in package.dependencies
const commandsDirectory = useTypeScript
  ? (package.oclif.commands || './lib/commands').replace('lib', 'src') 
  : package.oclif.commands || './lib/commands'

// This function does the following:
// 1. Traverse the commands directories and find out which commands exist
// 2. Create a translation map of spaces to colon seperated commands
// 3. Parse the arguments to determine which command was called (using spaces)
// 4. Convert the command to the colon seperated equivalent
// 5. Return the arguments as oclif expects it
module.exports = async function () {
  // create a commands with spaces to commands with colons map by traversing the commands directory
  const commandsMap = {}

  await findCommandsViaFileStructure(path.resolve(__dirname, '..', commandsDirectory), [], commandsMap)

  // add the help commands for each command to the map
  const helplessKeys = Object.keys(commandsMap)
  helplessKeys.forEach(key => {
    commandsMap['help ' + key] = 'help ' + commandsMap[key]
  })

  // find the spaced command and translate to colon command
  const commands = Array.from(process.argv).slice(2)
  const tail = []
  let args = commands.slice(0)
  while (commands.length > 0) {
    const key = commands.join(' ')
    const match = commandsMap[key]
    if (match === undefined) {
      tail.unshift(commands.pop())
    } else {
      args = match.split(' ').concat(tail)
      return args
    }
  }

  // if the command wasn't found then return original args
  return Array.from(process.argv).slice(2)
}

async function findCommandsViaFileStructure (dirPath, prefix, commandsMap) {
  const fileNames = await fs.readdir(dirPath)
  const length = fileNames.length
  let hasCommandFile = false
  for (let i = 0; i < length; i++) {
    const fileName = fileNames[i]
    const fullPath = path.resolve(dirPath, fileName)
    const stats = await fs.stat(fullPath)
    const newPrefix = prefix.slice(0)
    newPrefix.push(fileName)

    if (stats.isDirectory()) {
      const dirHasCommandFile = await findCommandsViaFileStructure(fullPath, newPrefix, commandsMap)
      if (dirHasCommandFile) {
        hasCommandFile = true
        commandsMap[newPrefix.join(' ')] = newPrefix.join(':')
      }
    } else if (stats.isFile() && /\.[jt]s$/.test(fileName)) {
      const last = newPrefix.length - 1
      newPrefix[last] = newPrefix[last].replace(/\.[jt]s$/, '')
      commandsMap[newPrefix.join(' ')] = newPrefix.join(':')
      hasCommandFile = true
    }
  }

  return hasCommandFile
}
```

**Second**

Edit your `bin/run` file to look like this:

```js
#!/usr/bin/env node
const command = require('@oclif/command')
const spaced = require('./space-separated')

spaced()
  .then(args => command.Main.run(args))
  .then(require('@oclif/command/flush'))
  .catch(require('@oclif/errors/handle'))
```

## How to Customize the Help to Show Spaces

If you also want to customize the help to make it use spaces then you can do these two steps:

**Step 1**

Edit the `oclif` object in your `package.json` to include a custom `helpClass`. Something like this:

```json
{
  ...
  "oclif": {
    "commands": "./lib/commands",
    "bin": "my-app",
    "helpClass": "./lib/help",
    "plugins": [
      "@oclif/plugin-help"
    ]
  },
}
```

**Step 2**

Create a file in your `lib` (or `src` if using TypeScript) directory called `help.js` (or `help.ts`) with the following code. Note that if you're using JavaScript you'll have to remove the Types data and probably change the imports to requires.

```ts
import CommandHelp from '@oclif/plugin-help/lib/command'
import { renderList } from '@oclif/plugin-help/lib/list'
import RootHelp from '@oclif/plugin-help/lib/root'
import { compact } from '@oclif/plugin-help/lib/util'
import { default as chalk } from 'chalk'
import indent = require('indent-string')
import stripAnsi = require('strip-ansi')
const wrap = require('wrap-ansi')

import Help from '@oclif/plugin-help'
import { Command, Topic } from '@oclif/config'
import { error } from '@oclif/errors'

const ROOT_INDEX_CMD_ID = ''
const { bold } = chalk

function getHelpSubject(args: string[]): string | undefined {
  for (const arg of args) {
    if (arg === '--') return
    if (arg === 'help' || arg === '--help' || arg === '-h') continue
    if (arg.startsWith('-')) return
    return arg
  }
}

export default class MyHelpClass extends Help {
  // acts as a "router"
  // and based on the args it receives
  // calls one of showRootHelp, showTopicHelp,
  // or showCommandHelp
  showHelp(args: string[]): void {
    const subject = getHelpSubject(args)
    if (!subject) {
      const rootCmd = this.config.findCommand(ROOT_INDEX_CMD_ID)
      if (rootCmd) this.showCommandHelp(rootCmd)
      this.showRootHelp()
      return
    }

    const command = this.config.findCommand(subject)
    if (command) {
      this.showCommandHelp(command)
      return
    }

    const topic = this.config.findTopic(subject)
    if (topic)  {
      this.showTopicHelp(topic)
      return
    }

    error(`command ${subject} not found`)
  }

  // display the root help of a CLI
  showRootHelp(): void {
    let rootTopics = this.sortedTopics
    let rootCommands = this.sortedCommands

    console.log(this.formatRoot())
    console.log('')

    if (!this.opts.all) {
      rootTopics = rootTopics.filter(t => !t.name.includes(':'))
      rootCommands = rootCommands.filter(c => !c.id.includes(':'))
    }

    if (rootTopics.length > 0) {
      console.log(this.formatTopics(rootTopics))
      console.log('')
    }

    if (rootCommands.length > 0) {
      rootCommands = rootCommands.filter(c => c.id)
      console.log(this.formatCommands(rootCommands))
      console.log('')
    }
  }

  // display help for a topic
  showTopicHelp(topic: Topic): void {
    const name = topic.name
    const depth = name.split(':').length

    const subTopics = this.sortedTopics.filter(t => t.name.startsWith(name + ':') && t.name.split(':').length === depth + 1)
    const commands = this.sortedCommands.filter(c => c.id.startsWith(name + ':') && c.id.split(':').length === depth + 1)

    console.log(this.formatTopic(topic))

    if (subTopics.length > 0) {
      console.log(this.formatTopics(subTopics))
      console.log('')
    }

    if (commands.length > 0) {
      console.log(this.formatCommands(commands))
      console.log('')
    }
  }

  // display help for a command
  showCommandHelp(command: Command): void {
    const name = command.id
    const depth = name.split(':').length

    const subTopics = this.sortedTopics.filter(t => t.name.startsWith(name + ':') && t.name.split(':').length === depth + 1)
    const subCommands = this.sortedCommands.filter(c => c.id.startsWith(name + ':') && c.id.split(':').length === depth + 1)

    const title = command.description && this.render(command.description).split('\n')[0]
    if (title) console.log(title + '\n')
    console.log(this.formatCommand(command))
    console.log('')

    if (subTopics.length > 0) {
      console.log(this.formatTopics(subTopics))
      console.log('')
    }

    if (subCommands.length > 0) {
      console.log(this.formatCommands(subCommands))
      console.log('')
    }
  }

  // the default implementations of showRootHelp
  // showTopicHelp and showCommandHelp
  // will call various format methods that
  // provide the formatting for their corresponding
  // help sections;
  // these can be overwritten as well

  // the formatting responsible for the header
  // displayed for the root help
  formatRoot(): string {
    const help = new RootHelp(this.config, this.opts)
    return help.root()
  }

  // the formatting for an individual topic
  formatTopic(topic: Topic): string {
    const name = topic.name
    const depth = name.split(':').length
    const subTopics = this.sortedTopics.filter(t => t.name.startsWith(name + ':') && t.name.split(':').length === depth + 1)
    const commands = this.sortedCommands.filter(c => c.id.startsWith(name + ':') && c.id.split(':').length === depth + 1)

    const usage = [bold('USAGE')]
    if (subTopics.length > 0) {
      usage.push(indent(wrap(`${this.config.bin} ${spaces(topic.name)} TOPIC`, this.opts.maxWidth - 2, {trim: false, hard: true}), 2))
    }
    if (commands.length > 0) {
      usage.push(indent(wrap(`${this.config.bin} ${spaces(topic.name)} COMMAND`, this.opts.maxWidth - 2, {trim: false, hard: true}), 2))
    }

    let description = this.render(topic.description || '')
    const title = description.split('\n')[0]
    description = description.split('\n').slice(1).join('\n')
    let output = compact([
      title,
      usage.join('\n'),
      description && ([
        bold('DESCRIPTION'),
        indent(wrap(description, this.opts.maxWidth - 2, {trim: false, hard: true}), 2),
      ].join('\n')),
    ]).join('\n\n')
    if (this.opts.stripAnsi) output = stripAnsi(output)
    return output + '\n'
  }

  // the formatting for a list of topics
  protected formatTopics(topics: Topic[]): string {
    if (topics.length === 0) return ''
    const body = renderList(topics.map(c => {
      return [
        minLen(c.name.split(':').pop(), 8),
        c.description && this.render(c.description.split('\n')[0]),
      ]
    }), {
      spacer: '\n',
      stripAnsi: this.opts.stripAnsi,
      maxWidth: this.opts.maxWidth - 2,
    })
    return [
      bold('TOPICS'),
      indent(body, 2),
    ].join('\n')
  }

  // the formatting for a list of commands
  formatCommands(commands: Command[]): string {
    if (commands.length === 0) return ''

    const body = renderList(commands.map(c => {
      return [
        minLen(c.id.split(':').pop(), 8),
        c.description && this.render(c.description.split('\n')[0]),
      ]
    }), {
      spacer: '\n',
      stripAnsi: this.opts.stripAnsi,
      maxWidth: this.opts.maxWidth - 2,
    })

    return [
      bold('COMMANDS'),
      indent(body, 2),
    ].join('\n')
  }

  // the formatting for an individual command
  formatCommand(command: Command): string {
    const help = new CommandHelp(command, this.config, this.opts)
    return help.generate()
      .replace(new RegExp(command.id, 'g'), spaces(command.id))
  }
}

function minLen (value: string | undefined, length: number): string {
  if (value === undefined) value = ''
  value += ' '.repeat(length - value.length)
  return value
}

function spaces (value: string): string {
  return value.replace(/:/g, ' ')
}
```

**Comment by RodEsp** [comment]
This is now supported as part of the upcoming `oclif@v2` release.
You can enable it by using https://github.com/oclif/core and adding the `topicSeparator` property to your oclif config as seen in our example repo, https://github.com/oclif/hello-world/blob/main/package.json#L51.
