### ISSUE TITLE
tsconfig.json is parsed as JSON

### ISSUE THREAD

**Issue by borekb** [oclif/oclif#189]
What a strange title :)

I was surprised why changes in my TypeScript commands are not picked up by a CLI. It turns out it's because I added trailing comma to my `tsconfig.json` (which is perfectly fine from TypeScript's perspective) and, probably, oclif parses it as JSON, at least that's what `DEBUG=*` seems to suggest.

It's a relative edge case but I thought I'd report it.

**Comment by ORESoftware** [comment]
On this note, a `tsconfig.js` file would be nice - would nice to have a .js based configuration instead of .json, for a lot of reasons include unnecessary errors like trailing commas.

**Comment by jdxcode** [comment]
this is fixed now (I think)
