### ISSUE TITLE
Show falsy default values in help

### ISSUE THREAD

**Issue by fvictorio** [oclif/oclif#192]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Report a bug.

What is the current behavior?
-----------------------------

Create a command with arguments. Make one of those arguments be a falsy value (like `0` or the empty string `''`). Then run `your-tool your-command --help`. The arguments section of the help doesn't show the default value.

What is the expected behavior?
------------------------------
I would expect the default values to be shown, even if they are falsy.

I can provide a MWE if it's needed. Thanks!

**Comment by jdxcode** [comment]
do you mean the arg name or the description?

**Comment by fvictorio** [comment]
I mean the default value in the argument description. My particular case is this:

```
USAGE
  $ eth randomAddress [AMOUNT] [PREFIX]

ARGUMENTS
  AMOUNT  [default: 1] Can be specified to generate a list of addresses.
  PREFIX  Generates a random address with the given prefix.
```

`PREFIX` has the empty string as default value, but it's not shown. To check if the problem was that it was falsy, I changed the `AMOUNT` default value to 0, and the default wasn't shown either.

Maybe this is by design, but in my opinion the default value should be shown if it's not undefined.

**Comment by jdxcode** [comment]
ah ok, so I think we just need to change [this](https://github.com/oclif/plugin-help/blob/0777d50bc5ebd2aa19ad9fad45555e2a109f86d4/src/command.ts#L98) to `if ('default' in a)`

**Comment by fvictorio** [comment]
Yes, that fixes it, although it looks a little weird:

```
ARGUMENTS
  AMOUNT  [default: 1] Can be specified to generate a list of addresses.
  PREFIX  [default: ] Generates a random address with the given prefix.
```

It's better if I add a `JSON.stringify`:

```
  AMOUNT  [default: 1] Can be specified to generate a list of addresses.
  PREFIX  [default: ""] Generates a random address with the given prefix.
```

but I don't know if that may cause other issues.

**Comment by jdxcode** [comment]
we could probably use `util.inspect()`

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
