### ISSUE TITLE
[FEATURE] -vvv for leveled verbosity?

### ISSUE THREAD

**Issue by SamuelMarks** [oclif/oclif#193]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
Closest I can do it so far is:
```typescript
verbosity: flags.string({ char: 'v', description: 'verbosity', multiple: true }),
```

Then:
```typescript
const verbosity = flags.verbosity == null ? 0 : flags.verbosity.length;
```

Which makes `-vv` and `-vvvvvvvvvvv` work, but not `-v`.

What is the expected behavior?
------------------------------
Would like a solution that would work for `-v` also. This is a common use-case for CLI applications, e.g.: `ssh` works like this.

**Comment by jdxcode** [comment]
I actually had this in place at one point to allow boolean flags to return an integer of how many times it was specified. It could be brought back, maybe as an option, right here: https://github.com/oclif/parser/blob/master/src/parse.ts#L169

The reason I took it out was that it being an integer was slightly surprising behavior and we quit using debug "levels" inside oclif in favor of "tags"—so I wasn't using it myself anymore.

**Comment by SamuelMarks** [comment]
Thanks for the analysis. Would be handy to have this feature returned.

**Comment by KnisterPeter** [comment]
@jdxcode It would be awesome to have this

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by sergei-dyshel** [comment]
For those stumbling on this issue and wondering how is that most robust CLI parser for JS doesn't support such trivial feature, here's a hacky way to achieve that:
```ts
export function countFlag(
  options?: Partial<Omit<BooleanFlag<number>, "allowNo" | "default" | "parse">>,
) {
  return Flags.boolean<number>({
    ...options,
    parse: (input, context, opts) => {
      let count = 0;
      for (const arg of context.argv) {
        if (arg === "--" + opts.name) count++;
        if (opts.char) {
          const match = new RegExp(`^-(${opts.char}+)`).exec(arg);
          if (match) count += match[1].length;
        }
      }
      return Promise.resolve(count);
    },
  });
}
```

It supports both `--verbose` and `-vvv` forms and even partially supports GNU single-character flag sequences like `-vvffile`. This is enough for 99% of cases.
