### ISSUE TITLE
Result of Command#run method hasn't catch method 

### ISSUE THREAD

**Issue by ikokostya** [oclif/oclif#196]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

bug

What is the current behavior?
-----------------------------

Return type of [`Command#run`](https://github.com/oclif/config/blob/30866966afc0f8e6eb6870ac0c218bac8548129f/src/command.ts#L70) method is declared as `PromiseLike<any>`, but in TypeScript standard library `PromiseLike` type [hasn't](https://github.com/Microsoft/TypeScript/blob/cd6d2fdc18a2511275d4443886b7de5a17906146/src/lib/es5.d.ts#L1366) `catch` method. So, the following example (which is slightly modified example from [documentation](https://github.com/oclif/command#usage)) is not compiled:

```ts
import {Command, flags} from '@oclif/command';
import {handle as handleError} from '@oclif/errors';

class Test extends Command {
    async run() {}
}

Test
    .run()
    .catch(handleError);  // Error: Property 'catch' does not exist on type 'PromiseLike<any>'.
```

What is the expected behavior?
------------------------------

No compilation errors.

Versions:

* OS: Linux
* nodejs: 8.14.0
* `@oclif/command`: 1.5.6 
* typescript: 3.2.1

`tsconfig.json` configuration:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "esnext",
        "lib": ["es2018"],
        "strict": true,
        "noEmitOnError": true,
        "types": ["node"],
        "sourceMap": true,
        "rootDir": "src"
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by jeremiegirault** [comment]
as a workaround I used: `.then(() => {}, handleError)`

**Comment by chadian** [comment]
Agreed, that is definitely the easiest solution. It actually used to be typed to `Promise` but was changed to`PromiseLike` here: https://github.com/oclif/command/pull/47 in response to this oclif issue https://github.com/oclif/oclif/issues/154. This allows it to be compatible with Promise libraries with the trade-off being that you can't use `catch`.

These should work:
```js
.then(onFulfilled, onRejected);
```
or (@ onFulfilled  onRejected)
```js
.then(successHandler)
.then(null, errorHandler); // similar to .catch(errorHandler)
```
