### ISSUE TITLE
Feature: Support for semantic-releases

### ISSUE THREAD

**Issue by ryanwilsonperkin** [oclif/oclif#201]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
[Semantic Releases](https://github.com/semantic-release/semantic-release) recommends that you leave your version number in the `package.json` set to something like 0.0.0 and let it manage it for you when publishing new releases. This seems to conflict with `@oclif/dev-cli` publishing package numbers based on your `package.json` version number, and also generating links in the README based on it.

What is the expected behavior?
------------------------------
Do you know of anyone successfully using `@oclif/dev-cli` together with Semantic Releases. If it's not currently possible, would this be a feature you would consider supporting?

**Comment by jdxcode** [comment]
I have a [package](https://github.com/oclif/semantic-release) here that used to work with semantic-release, but something seemed to have changed in semantic-release that caused everything to quit working.

We already have `OCLIF_NEXT_VERSION` to set the version with an environment variable. Perhaps if somehow that was set to the new version name before semantic-release runs this could work again.

**Comment by l5x** [comment]
Something like this in `release.config.js` should work

```js
module.exports = {
  branch: 'master',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/npm',
    [
      '@semantic-release/exec',
      {
        prepareCmd: 'oclif-dev manifest && oclif-dev readme'
      }
    ],
    [
      '@semantic-release/git',
      {
        assets: ['README.md'],
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
      }
    ],
    '@semantic-release/github'
  ]
}
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
