### ISSUE TITLE
[Feature] - Progress bar

### ISSUE THREAD

**Issue by justinlevi** [oclif/oclif#202]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

Would be great if oclif had a progress bar instead of just the spinner. 

Was looking at this: 
https://github.com/visionmedia/node-progress

**Comment by sourabh1031** [comment]
@justinlevi i would like to work on this. can you please give some reference as a help to solve the issue

**Comment by ewhipp** [comment]
I think this has been implemented https://github.com/oclif/cli-ux/commit/ed1523c4484dfc43b4cd9eef3e09f5a6ad6f3bd1
