### ISSUE TITLE
Feature: Add support for scoped commands

### ISSUE THREAD

**Issue by nparsons08** [oclif/oclif#207]
Feature Request:

Currently, when attempting to add a subcommand to achieve the following:

`$ ./bin/run *chat* messages:send`

It thinks that I want `chat:messages` when in fact that is not a command.

Ideally, this should allow for a subcommand such as `$ ./bin/run *chat* messages:send` or `$ ./bin/run *feed* create:new --arg "foo"` where the first command is a directory within the commands folder.

The ideal directory structure would look like this:

```
/src
    /commands
        /chat
            foo.js
            bar.js
       /feed
           foo.js
           bar.js
```

This will allow for a _mono_ repo if you will.

Is it possible to currently achieve this? Even at the plugin level?

Thank you!

**Comment by rhwood** [comment]
How is this different than [Topics](https://oclif.io/docs/topics)?

**Comment by nparsons08** [comment]
@rhwood exactly what I was looking for. Just needed a nudge in the right direction – must have missed this in the docs somehow. Thanks!
