### ISSUE TITLE
[Feature Request] Repl mode

### ISSUE THREAD

**Issue by Stefanwullems** [oclif/oclif#209]
We are currently maintaining an app built with Vorpal but it is suboptimal because it's not being maintained and it's doesn't provide the same level of Typescript support that Oclif does. 

The only thing that's keeping us from switching to Oclif is that fact that it does not have an inbuilt way to go into repl mode (At least I have not found it). It would be highly appreciated if you could take a look at it.

**Comment by jdxcode** [comment]
This is definitely not a direction we'll ever go for this project, sorry

**Comment by ccorcos** [comment]
Seems like a reasonable request for the multi-command to leave you in a namespaced  repl.

**Comment by sisou** [comment]
I just found https://www.npmjs.com/package/oclif-plugin-repl, which I am trying out now. Works well with the multi-command scaffold setup.

**Comment by KaKi87** [comment]
Hello,
Is there any alternative for this ?
Thanks
