### ISSUE TITLE
GSoC 2019 Participation

### ISSUE THREAD

**Issue by sourabh1031** [oclif/oclif#212]
I want to work on the project to create linter of oclif project under gsoc 2019
Please help me getting started with good first issue so that i get the project workflow. Also please do mention communication channel so that i can further discuss my ideas and learn from the team.

**Comment by elbandito** [comment]
Thank you for your interest in the Google Summer of Code, @sourabh1031.  There's a formal process for applying and participating.  See this [link](https://summerofcode.withgoogle.com/how-it-works/) for more details.

**Comment by RasPhilCo** [comment]
@sourabh1031 you can discuss ideas further at https://spectrum.chat/oclif. Applications open March 25th.

**Comment by sourabh1031** [comment]
@elbandito @RasPhilCo thanks for the help i have already introduced myself in the community . i think the team is little busy.

**Comment by sourabh1031** [comment]
I want to work on this issue to get started with the workflow
https://github.com/oclif/oclif/issues/55

**Comment by rmeena840** [comment]
Hi, My name is Ravindra Kumar Meena. I am also GSoC 2019 Aspirant. As @sourabh1031 is working on oclif linter so, please let me know the other projects suitable for GSoC. Thanks

**Comment by jdxcode** [comment]
nobody is working on the linter yet

**Comment by rmeena840** [comment]
Thanks for attending the issue ASAP. Can anyone please share the list of available projects for GSoC? Thanks

**Comment by sourabh1031** [comment]
Hello @rmeena840 i am proposing to work on the project. For more project ideas you can visit the link shared above by @elbandito  .

**Comment by moulikcipherX** [comment]
@jdxcode Hello Sir, I am working on the linter I need some suggestions for my project proposal.
Please share the communication channel where we can contact.

**Comment by jdxcode** [comment]
we're not able to meet with potential candidates individually. That would not be fair to everyone.

**Comment by moulikcipherX** [comment]
What will be the procedure for the same?

**Comment by RasPhilCo** [comment]
Hey everyone!

I wanted to provide some clarity on GSoC participation as the website leaves some information out.

First, thanks so much in your interest in working on oclif with us! We love this project and we're excited to work with one of you during GSoC.

Remember, this is an open-source project and we accept feature PR's and bug fixes from contributors all the time. If you want to work on something or fix something, we will happily review your PR.

That being said, if you want to work with us via GSoC, submit an application with your project idea starting March 25th. We have one idea listed here - https://github.com/salesforce/gsoc#oclif--oclifoclif - but you can submit any idea!  Per GSoC, we are allowed to accept one applicant for the summer.

Right now, we are able to answer questions and explain our expectations. But we can't come up with a project idea/application for you. Your application should show *your* ideas on what you'd like to accomplish with your project. If you would like to talk publicly, you can reach us in our Spectrum chat channel: https://spectrum.chat/oclif (Mon-Fri, 9am-5pm PST). If you would like to talk privately please email the contact here: https://github.com/salesforce/gsoc#contact-information (Mon-Fri, 9am-5pm PST). If you have already emailed us this past week, we will get back to you on Monday.

If your application is not selected for GSoC, it doesn't mean it is a bad idea! We can only select one proposal for GSoC and if yours is not selected consider submitting it to oclif via a PR. A small caveat being: if your idea is the _same_ as our GSoC student, it is only fair that we prioritize their project.

Hope that clears things up!

**Comment by RasPhilCo** [comment]
GSoC has a proposal template and guide:

https://google.github.io/gsocguides/student/writing-a-proposal

**Comment by sourabh1031** [comment]
@elbandito @RasPhilCo @jdxcode why do we actually need to make linter for ocif. because there is a linter available for typescript as [tslint](https://www.npmjs.com/package/tslint)

**Comment by moulikcipherX** [comment]
@RasPhilCo @jdxcodr @elbandito 
I have shared my proposal draft on email so can you please review it by providing feedback comment on the proposal.

**Comment by moulikcipherX** [comment]
@RasPhilCo @jdxcode @elbandito
I have shared my proposal draft on email so can you please review it by providing feedback comment on the proposal.

**Comment by imshubhamsingh** [comment]
@RasPhilCo @jdxcode @elbandito I have shared my proposal draft, please review it by providing feedback comment on the proposal.
