### ISSUE TITLE
Customize help/usage information for multi commands?

### ISSUE THREAD

**Issue by bitjson** [oclif/oclif#213]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Feature

What is the current behavior?
-----------------------------

I may be missing some documentation or configuration option – is it possible to customize the help output for the top-level command of a multi-command CLI?

Right now I'm getting:
```
$ foo
Description from package.json.

VERSION
  @foo/cli/0.0.0 darwin-x64 node-v10.15.1

USAGE
  $ foo [COMMAND]

COMMANDS
  bar           bar description
```

What is the expected behavior?
------------------------------

Is it possible to customize this output at all? Commands within the project can also provide information under `DESCRIPTION` and `EXAMPLE` headings. Can I provide a more extensive description and examples for the top-level command somehow?

This is an amazing project, it's already compressing days (or weeks) of work into minutes. (E.g. I've [fought with autocomplete in the past](https://github.com/tj/commander.js/issues/385), and this implementation is just perfect.) Thank you very much!

**Comment by jdxcode** [comment]
it's not currently possible to customize it much further. We could add this by turning [this code](https://github.com/oclif/plugin-help/blob/master/src/command.ts#L37-L44) into a [template](https://github.com/oclif/plugin-help/pull/35) though.

**Comment by bitjson** [comment]
I'd love to be able to customize it – would you be interested in a PR to do that? 

To make sure I understand the spec, does that mean I would be adding a customized template string into `package.json` to replace the entire help output of the command? (And if so, what would an example template look like to add a `DESCRIPTION` heading?)

**Comment by jdxcode** [comment]
yeah, I showed an example of where we added a template that should be enough to get started. The template for this will likely be a bit more complicated.

**Comment by RasPhilCo** [comment]
You can now customize your help output via a custom Help class: https://oclif.io/docs/help_classes#custom-help
