### ISSUE TITLE
oclif-dev pack:macos does not include hooks

### ISSUE THREAD

**Issue by Olyve** [oclif/oclif#223]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Reporting a bug in the packing of the cli.

What is the current behavior?
-----------------------------
I used the generator to generate a new hook that should hook into the `init` hook. When I pack up the cli tool for macos and install it, I tried checking the version of the tool and received an error saying that the files for the hook could not be found.

What is the expected behavior?
------------------------------
I am running oclif/config@1.12.12 on macos 10.14.3

Output from command:
![Screen Shot 2019-04-04 at 12 25 31 PM](https://user-images.githubusercontent.com/1574010/55582595-c46c5400-56d4-11e9-8b7d-b3e99d4deeb1.png)

Relevant package.json info:
![Screen Shot 2019-04-04 at 12 26 28 PM](https://user-images.githubusercontent.com/1574010/55582639-e36ae600-56d4-11e9-8677-1f7ab4d7884c.png)

**Comment by sgalizia** [comment]
More importantly, none of the commands I created work at all after packaging up the cli tool. That kind of defeats the whole purpose of it if it only works in development haha. I tried doing this with the macOS installer and installing manually with the tar file and neither method has worked at all for any commands I created.

![Screen Shot 2019-04-04 at 1 52 25 PM](https://user-images.githubusercontent.com/1574010/55587738-e53aa680-56e0-11e9-80ef-574b606025fb.png)

**Comment by sgalizia** [comment]
Upon further investigation, the `tsc -b` portion of the scripts is not being run and I am not sure why. Triggering a manual build and the packing it up works as intended.

**Comment by vxsx** [comment]
I've had this exact error and what worked for me was to change the `tsc -b` to `tsc -b -f` (f stands for force). It seems like tsc would only compile the project if something is changed, and i don't know where that cache is

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
