### ISSUE TITLE
Generating README on Windows uses backslashes in GitHub URLs

### ISSUE THREAD

**Issue by OscarScholten** [oclif/oclif#224]
Hi,

I'm working on a Windows machine, and noticed a bug where the generated code paths and URLs in the README contain backslashes rather than forward slashes. I've generated a new plugin using:

> npx oclif plugin mynewplugin

The README then contains:

> `_See code: _[_src\commands\hello.ts_](https://github.com/OscarScholten/mynewplugin/blob/v0.0.0/src\commands\hello.ts)`

Note the backslashes in the GitHub links, both in the name and the actual URL.

It's rather easy to post process this, but it would be great to have this fixed in oclif.

The generated plugin is using these versions:

> Oscar@DESKTOP-VB20TL2 MINGW64 ~/tmp/oclif/mynewplugin
> $ npm list --depth=0 | grep oclif
> mynewplugin@0.0.0 C:\Users\Oscar\tmp\oclif\mynewplugin
> +-- @oclif/command@1.5.12
> +-- @oclif/config@1.12.11
> +-- @oclif/dev-cli@1.21.3
> +-- @oclif/plugin-help@2.1.6
> +-- @oclif/test@1.2.4
> +-- @oclif/tslint@3.1.1
> 

Cheers, Oscar

**Comment by nvuillam** [comment]
I have exactly the same issue !
If we generate a PR, will it be accepted ?
I see lots of pending PR ...

**Comment by nvuillam** [comment]
Corrected in PR https://github.com/oclif/dev-cli/pull/133
Will be realeased when maintainers will have validated the PR :)

Meanwhile  @OscarScholten , you can just add :  
 `p = p.replace(/\\/g, '/') // Replace windows '\' by '/'`
 just before
 `return p` 
at the end of function `commandPath(plugin, c)` in file : 
`YOURROOTPROJECTFOLDER\node_modules\@oclif\dev-cli\lib\commands\readme.js`


(check the update here : https://github.com/oclif/dev-cli/pull/133/files )

**Comment by rjwut-chg** [comment]
This has been fixed with [this PR](https://github.com/oclif/dev-cli/pull/266).

**Comment by rjwut-chg** [comment]
@RasPhilCo @nvuillam This issue can be closed.

**Comment by nvuillam** [comment]
Agreed, but not sure i have the rights to do that :(

**Comment by rjwut-chg** [comment]
Sooo, who does?

**Comment by nvuillam** [comment]
Probably @RasPhilCo  :)
