### ISSUE TITLE
Cannot make a base class with flags and a derived command with args

### ISSUE THREAD

**Issue by fvictorio** [oclif/oclif#225]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Report a bug

What is the current behavior?
-----------------------------

I can't create a base class that parses flags and a derived command that parses arguments

What is the expected behavior?
------------------------------

I expect to be able to do this.

```
  "@oclif/command": "^1",
  "@oclif/config": "^1",
  "@oclif/plugin-help": "^2",
  "tslib": "^1"
```

---

I started a project with `npx oclif multi mynewcli` with typescript enabled. Then I created a base class:

```typescript
import Command, {flags} from '@oclif/command'

export default abstract class Base extends Command {
  static flags = {
    verbose: flags.boolean()
  }

  print(message: string) {
    const { flags } = this.parse(Base)
    if (flags.verbose) {
      this.log(message)
    }
  }
}
```

Then I created a command that uses this base class:

```typescript
import {Command, flags} from '@oclif/command'

import Base from '../base';

export default class Hello extends Base {
  static args = [{name: 'message'}]

  async run() {
    const {args} = this.parse(Hello)

    this.print(args.message)
  }
}
```

After that, I ran `yarn prepack` and then I did `./bin/run hello --verbose foo` and I got this error:

```
 ›   Error: Unexpected argument: foo
 ›   See more help with --help
```

It seems like oclif thinks `--verbose` is the argument, and gets confused after that.

**Comment by fvictorio** [comment]
FWIW, I also tried adding the base class flags to the derived command:

```typescript
export default class Hello extends Base {
  static flags = {
    ...Base.flags
  }

  ...
```

**Comment by kmannislands** [comment]
Also ran into this when trying to introduce something like 'global flags' which is probably a pretty common use-case IMO

**Comment by QWp6t** [comment]
This is how I do it, which seems to be working for me so far...
```ts
import {Input} from '@oclif/parser';
/* ... */
  async init() {
    const { args, flags } = this.parse(<Input<any>>this.constructor);

    this.args = args;
    this.flags = flags;
  }
```

And then in extended classes, I make sure I have the following...
```ts
import Command from '../command';
/* ... */
  static args = [
    ...Command.args,
  ]

  static flags = {
    ...Command.flags,
  }
```
(where `Command` is my base class)

It's important to note that the static `args` and `flags` properties **MUST** be specified on the extended class (even if the extended class doesn't add any new args or flags), and then you can inherit them using the spread operator as shown above.

**Comment by trevorr** [comment]
I ended up with something like this to get everything working with Typescript 3.7.3 in a mostly default configuration:

```ts
// src/base.ts
import { Command, flags } from '@oclif/command';
import { Input, OutputArgs, OutputFlags } from '@oclif/parser';

export default abstract class BaseCommand extends Command {
  static flags = {
    help: flags.help({ char: 'h' })
  };

  static args = [{ name: 'file', required: true }];

  protected parsedArgs?: OutputArgs<any>;
  protected parsedFlags?: OutputFlags<typeof BaseCommand.flags>;

  async init(): Promise<void> {
    const { args, flags } = this.parse(this.constructor as Input<typeof BaseCommand.flags>);
    this.parsedArgs = args;
    this.parsedFlags = flags;
  }
}
```

```ts
// src/command/derived.ts
import { OutputFlags } from '@oclif/parser';
import BaseCommand from '../base';

export default class Derived extends BaseCommand {
  static flags = {
    ...BaseCommand.flags,
    /* ... */
  };

  static args = [
    ...BaseCommand.args,
    /* ... */
  ];

  async run(): Promise<void> {
    const { /* ... */ } = this.parsedFlags as OutputFlags<typeof Derived.flags>;
    const { /* ... */ } = this.parsedArgs!;
  }
}
```

**Comment by weynhamz** [comment]
For javascript.

```javascript
// src/base.js
const { Command, flags: Flags } = require('@oclif/command');

const fs = require('fs-extra');
const path = require('path');

class BaseCommand extends Command {
  async init() {
    const { flags } = this.parse(BaseCommand);

    let configFile = null;

    if (flags.config) {
      configFile = path.resolve(flags.config);
    } else {
      configFile = path.join(this.config.configDir, 'config.json');
    }

    if (!fs.existsSync(configFile)) {
      throw new Error('Can not find the config.json');
    }

    this.flags = flags;
  }
}

BaseCommand.flags = {
  config: Flags.string({ description: 'The config.json file', required: false }),
};


module.exports = BaseCommand;
```

```javascript
// src/command/sub.js
const { flags: Flags } = require('@oclif/command');

const BaseCommand = require('../base');

class SubCommand extends BaseCommand {
  async run() {
    const { flags } = this.parse(this.constructor);

    this.flags = flags;

    const url = this.flags.url;
  }
}

SubCommand.flags = {
  ...BaseCommand.flags,
  url: Flags.string({ description: 'URL', required: true }),
};

module.exports = SubCommand;
```

**Comment by manh-gntvn** [comment]
My solution: 
> to `this.parse` method, use `this.ctor` instead of class itself.

in any command classes

```ts
const { flags, args } = this.parse(this.ctor as typeof <ThisClass>)
```

Examples:

Base command:
```ts
const { flags, args } = this.parse(this.ctor as typeof BaseCommand)
```
Sub class (command)
```ts
const { flags } = this.parse(this.ctor as typeof FirebaseMediaImport)
```

**Comment by xakraz** [comment]
> For javascript.
> 
> ```js
> // src/base.js
> const { Command, flags: Flags } = require('@oclif/command');
> 
> class BaseCommand extends Command {
>   async init() {
>     const { flags } = this.parse(BaseCommand);
> 
>     this.flags = flags;
>   }
> }
> 
> BaseCommand.flags = {
>   config: Flags.string({ description: 'The config.json file', required: false }),
> };
> 
> 
> module.exports = BaseCommand;
> ```
> 
> ```js
> // src/command/sub.js
> const { flags: Flags } = require('@oclif/command');
> 
> const BaseCommand = require('../base');
> 
> class SubCommand extends BaseCommand {
>   async run() {
>     const { flags } = this.parse(this.constructor);
> 
>     this.flags = flags;
> 
>     const url = this.flags.url;
>   }
> }
> 
> SubCommand.flags = {
>   ...BaseCommand.flags,
>   url: Flags.string({ description: 'URL', required: true }),
> };
> 
> module.exports = SubCommand;
> ```

@weynhamz I haven't managed to make it work with `args` ... any tips ?
Thanks !

**Comment by rannn505** [comment]
Hey all, 

As mentioned here in previous comments, the solution is quite simple, when calling `this.parse` method on the base (parent) Command class use `this.constructor` as argument instead of the class type (as done in regular commands).
```js
import { Input } from '@oclif/parser';
....
const { args, flags } = this.parse(this.constructor as Input<typeof BaseCommand.flags>);
```

The true problem here is that the example in the [documentation](https://oclif.io/docs/base_class) does not highlight the importance of doing this nor does it provide an example in typescript.

**Comment by hectorvp** [comment]
> Hey all,
> 
> As mentioned here in previous comments, the solution is quite simple, when calling `this.parse` method on the base (parent) Command class use `this.constructor` as argument instead of the class type (as done in regular commands).
> 
> ```js
> import { Input } from '@oclif/parser';
> ....
> const { args, flags } = this.parse(this.constructor as Input<typeof BaseCommand.flags>);
> ```
> 
> The true problem here is that the example in the [documentation](https://oclif.io/docs/base_class) does not highlight the importance of doing this nor does it provide an example in typescript.

@rannn505 , I got this working by using this.constructor instead of class name, but didn't get purpose why it works in this way.

Check this ts snippet
```ts
class Person {
  age: number;

  constructor(a: number){
    this.age = a;
  }

  compare(){
    console.log(this.constructor === Person);
  }
}

new Person(2).compare();
```

Compare method will print true.

**Comment by william-will-angi** [comment]
Also experiencing this issue. I am currently doing this in the base class in order to avoid typescript compilation issues:
```
const {flags} = this.parse(this.constructor as any) as any;
```

**Comment by FatalMerlin** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

@0xdevalias I hope it's okay to copy your message, as I 100% agree with it.
