### ISSUE TITLE
How to access config outside the command class?

### ISSUE THREAD

**Issue by hzchirs** [oclif/oclif#226]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

I have an util class to interact with XDG directories.
Is there any way to access `this.config.dataDir`, `this.config.configDir` outside the command class?

Thanks!

**Comment by mikelieser** [comment]
Have the same (basic) question right now. I guess you need to pass `this.config` from commands/hooks to your lib classes :( Did you find a better solution?

**Comment by toti1212** [comment]
I have the same issue :confused: I had to workaround creating a singleton instance that can delegate all the responsibilities and other logic but initialized with `this.config` in the `constructor`. Share if can find a better solution

**Comment by toti1212** [comment]
Maybe the correct way is to get a `config.json` file and read it 🤔 
Heres the [custom-user-configuration doc](https://oclif.io/docs/config#custom-user-configuration)

**Comment by mikelieser** [comment]
What I do now is this...

**create a new oclif init hook**

`oclif hook set-global-config --event=init`

**src/hooks/init/set-global-config.js**
```
module.exports = async function(opts) {
  global.config = opts.config;
}
```

Now you can access the oclif config hash from everywhere by just calling `global.config` like this.

**src/lib/my-custom-class.js**
```
module.exports = class MyCustomClass {
  constructor() {
    this.configDir = global.configPath.configDir;
  }
}
```
**src/commands/hello.js**

```
const { Command } = require("@oclif/command");
const MyCustomClass = require("../lib/my-custom-class");

class HelloCommand extends Command {
  async run() {
    const customClass = new MyCustomClass();
  }
}
```

**Comment by hzchirs** [comment]
Hi, I currently use another approach to achieve this (use [Custom Base Class](https://oclif.io/docs/base_class))

```javascript
// src/base.js
const Command = require('@oclif/command').Command
const MyCustomClass = require("../lib/my-custom-class")

class Base extends Command {
  async init() {
    this.custom = _initMyCustomClass()
  }

   _initMyCustomClass() {
     return new MyCustomClass(this.config)
   }
}


// src/commands/hello.js

const Base = require("../base")

class HelloCommand extends Base {
  async run() {
     console.log(this.custom) // can access this.custom here..
  }
}
```
