### ISSUE TITLE
Getting a stack trace when passing Error to this.error

### ISSUE THREAD

**Issue by AlexanderOMara** [oclif/oclif#229]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

Calling the following produces a stack trace:
```
this.error(new Error('testing'));
```

```
Error: testing
    at Update.run (.../src/commands/test.ts:47:14)
    at Update._run (.../node_modules/@oclif/command/lib/command.js:35:31)
```

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

Expected no stack trace as documented here: https://oclif.io/docs/commands

> These errors are friendly and won't show a traceback unless debugging is enabled with...

The environment variables that are supposed to enable it are not enabled (also `this.config.debug` is `0`).

Versions:
@oclif/command: 1.5.13
@oclif/config: 1.12.12
@oclif/plugin-help: 2.1.6
macOS: 10.14.4
Node: v12.0.0 and v11.14.0

```ts
import {flags, CommandBase} from '@oclif/command';

export default class Test extends CommandBase {
	public static description = 'test command';

	public static examples = [];

	public static flags = {
		help: flags.help({char: 'h'})
	};

	public static args = [];

	public async run() {
		const {args, flags, argv} = this.parse(Test);

		this.warn(new Error('testing')); // no stack trace

		// this.error('testing'); // no stack trace

		this.error(new Error('testing')); // stack trace
	}
}
```

On a side note, simply throwing an error also produces a stack trace. I'm not sure if it's supposed to however, as I can't find documentation on this.

**Comment by rizzlesauce** [comment]
I have the same issue. The issue appears to be in how CLIError wraps existing Error objects (https://github.com/oclif/errors/blob/v1.2.2/src/errors/cli.ts). It seems to not wrap the Error at all, actually, instead returning the original Error from the constructor. In this way, the error will not be able to render like other CLIError objects do. I think I have developed a fix.

**Comment by rizzlesauce** [comment]
I created a pull request: https://github.com/oclif/errors/pull/19

**Comment by RasPhilCo** [comment]
Hm, why not: 
```
this.error(err.message)
```
What are you solving for?

**Comment by l3omtz** [comment]
Has this been resolved? 
And how would you test that @RasPhilCo ?
I'm currently stuck where I can't seem to test that the error message is showing. 
I can do an exit code and that passes. but I need to test that the error message is the right one.
Any help would be great

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by bhuynhdev** [comment]
Coming back to this issue to ask if there is a way to disable the error trace. For example, I am using option `Args.file({exists: true})` and if an error occurs, the entire stack trace is printed, which is not user friendly.

**Comment by arielweinberger** [comment]
Any news regarding this issue?
