### ISSUE TITLE
Support documentation for `strict = false` command arguments

### ISSUE THREAD

**Issue by mattgibson** [oclif/oclif#234]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature.

What is the current behavior?
-----------------------------
If I specify `strict = false` and use `argv` to access whatever variable length string of arguments the user provides, there is no way to document this. The README doesn't mention that there is an arbitrary list of arguments accepted and if I specify this manually by editing the command form e.g.

```
USAGE
  $ fd start [SERVICES...]

ARGUMENTS
  SERVICES...  a list of service names
```

Then it gets overwriten next time I run `npx oclif command` to add a new one.

What is the expected behavior?
------------------------------
(@oclif/command@1.5.13 on macOS) That I can add documentation similar to that for flags with multiple arguments, which will show up in the README and when using the `--help` flag.

**Comment by xavdid** [comment]
@mattgibson did you find a solution to this? My only idea right now is to declare the optional arg and then try and parse it out. I've got the following:

```ts
export class MyCLI extends Command {
  static strict = false

  static args = [
    {name: 'firstArg', required: true},
    {name: 'secondArg'},
  ]

  async run() {
    this.log(this.args)
    this.log(this.argv)
  }
}
```

expected:

```
$ mycli a b c
{ firstArg: 'a', secondArg: [ 'b', 'c' ] }
[ 'a', 'b', 'c' ]
```

actual:

```
$ mycli a b c
{ firstArg: 'a', secondArg: 'b' }
[ 'a', 'b', 'c' ]
```

If I leave off `secondArg`, then it doesn't show up in `--help`, which is a bummer.


cc @RasPhilCo

**Comment by RasPhilCo** [comment]
Added an issue in plugin-help to have it there also.

@xavdid looks like the parser could handle that more clearly, but I'll have to dig in deeper.

**Comment by xavdid** [comment]
Thanks a bunch! let me know if there's anything I can do to help

**Comment by RasPhilCo** [comment]
@xavdid would this be something you're able to investigate in @oclif/parser? I just haven't had time yet.

**Comment by aexvir** [comment]
any update on this?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
