### ISSUE TITLE
Using `default` with `multiple` in flags does not return an array

### ISSUE THREAD

**Issue by quantumkid** [oclif/oclif#235]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Report a bug.

What is the current behavior?
-----------------------------

When using `default` with a `string` flag that takes multiple arguments (`multiple: true`) the value that's returned in `flags.myOption` is a string rather than a string array.

Minimal example:

```
import {Command, flags} from '@oclif/command'

export default class TestMultipleDefault extends Command {
  static description = 'My test command'

  static flags = {
    foo: flags.string({
      char: 'f', 
      description: 'test flag',
      multiple: true,
      default: 'a'
    })
  }

  async run() {
    const {args, flags} = this.parse(TestMultipleDefault)

    this.log(`${typeof flags.foo}: ${JSON.stringify(flags.foo)}`)
  }
}
```

Examples:

```
> ./bin/run
=> string: "a"

> ./bin/run -f a
=> object: ["a"]
```

What is the expected behavior?
------------------------------

I would expect passing no flags would set the default for `flags.foo` to `["a"]` instead of `"a"`. This would mean that I could expect to do things like `flags.foo.join(', ')` or submit it to a `POST` endpoint that expects an array in the JSON body.

oclif version `oclif/1.13.1 darwin-x64 node-v10.15.3`, Mac OS X 10.14.4.

**Comment by sukima** [comment]
I would expect this to be the case because you specifically asked the default to be a string: `default: 'a'` if you wanted to default to an array then wouldn't you want `default: ['a']` ?

**Comment by quantumkid** [comment]
Hmm, so that does work, but Typescript throws an error when I set `default: ['a']` because it expects a `string` (or undefined) in the `default` field. It does compile and run though.

**Comment by sukima** [comment]
> Typescript throws an error...because it expects a [`string | undefined`] in the `default` field

That sounds like a bug to me.

**Comment by quantumkid** [comment]
Will be solved by https://github.com/oclif/parser/pull/56
