### ISSUE TITLE
flags with default produce wrong TypeScript type

### ISSUE THREAD

**Issue by sukima** [oclif/oclif#236]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

**Bug**

What is the current behavior?
-----------------------------

```ts
function doSomethingWithAString(baz: string) { /* ... */ }

export default MyCommand extends Command {
  public static readonly description = 'blah blah';
  public static readonly args = [];
  public static readonly flags = {
    'foo-bar': flags.string({
      char: 'f',
      description: 'Yadda yadda',
      default: 'FOOBAR'
    })
  };
  public async run() {
    let { flags } = this.parse(MyCommand);
    let foobar = flags['foo-bar']; // TS thinks this is type <string | undefined>
    // foobar will always be a string due to the default above
    doSomethingWithAString(foobar); // Fails
    // Type <string> is not type <string | undefined>
  }
}
```

What is the expected behavior?
------------------------------

The result of a property on `flags` after a `this.parse` should match the type provided for by `default`.

```json
"@oclif/parser": "3.7.2"
```

MacOS 10.14.5 (18F132)
Please mention your oclif and OS version.

**Comment by RasPhilCo** [comment]
Good suggestion. This might be as easy as updating these lines:  https://github.com/oclif/parser/blob/master/src/parse.ts#L203 & thttps://github.com/oclif/parser/blob/master/src/parse.ts#L206.
