### ISSUE TITLE
Switch TSlint to ESlint.

### ISSUE THREAD

**Issue by VictorioBerra** [oclif/oclif#242]
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

All TSLint features are starting to get ported over to ESLint, can we add a help wanted tag for this task to switch the yeoman stuff all over to ESLint?

**Comment by moulikcipherX** [comment]
Thank you @VictorioBerra for the update.
We are working on it so we will consider it.
@elbandito

**Comment by THPubs** [comment]
They have already deprecated tslint: https://github.com/palantir/tslint/issues/4534

**Comment by RasPhilCo** [comment]
This will be shipped this fall.
