### ISSUE TITLE
Generate project `README.md` manually?

### ISSUE THREAD

**Issue by janpio** [oclif/oclif#243]
I want to regenerate the `README.md` manually after I updated the description in the command file.

By installing https://github.com/oclif/dev-cli globally, I seem to be able to regenerate the README by using `oclif-dev readme`. But as this process also works when creating a new command, I seem to already have this but couldn't find a way to access it.

Is this part of the normal `oclif` CLI somehow?

**Comment by RasPhilCo** [comment]
` ./node_modules/.bin/oclif-dev readme`

**Comment by janpio** [comment]
Ok, `@oclif/dev-cli` is a devDependency of this package, so you can call its binary by default.

Might it be worth adding a new `readme` script?

**Comment by RasPhilCo** [comment]
It's part of the prepack script but feel free to modify your scripts as you see fit.

**Comment by leonstafford** [comment]
Where `./node_modules/.bin/oclif-dev readme` wouldn't work for me (`Error: command readme not found`)

The following worked:

`./node_modules/@oclif/dev-cli/bin/run readme`

**Comment by architgarg** [comment]
You can run this 
```npm run veriosn```

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
