### ISSUE TITLE
Documentation for manifest?

### ISSUE THREAD

**Issue by VictorioBerra** [oclif/oclif#244]
I have checked the official docs, the github readme for oclif, and the readme for oclif-dev-cli and there is no information on the manifest file, what it does, how it works, why its needed, etc.

I see its baked into the examples too which makes it even more confusing.

**Comment by lorenzleutgeb** [comment]
Yeah, very strange. A [code search for "manifest" in TypeScript files of this repo](https://github.com/oclif/oclif/search?l=TypeScript&q=manifest) returns no results. I removed the invocation of `oclif-dev manifest ...` from `package.json` after generating it with `oclif ...`.

**Comment by RasPhilCo** [comment]
In short, to speed up the CLI. The manifest is a cache of the CLI's commands that can be read quicker than loading into memory all of the CLI's command files.

**Comment by lorenzleutgeb** [comment]
> In short, to speed up the CLI. The manifest is a cache of the CLI's commands that can be read quicker than loading into memory all of the CLI's command files.

Interesting. Could you please point us to the specific location of the code that does this? Just out curiosity.

**Comment by RasPhilCo** [comment]
Which bit, manifest generation or manifest reading?

**Comment by lorenzleutgeb** [comment]
> Which bit, manifest generation or manifest reading?

Preferably both.

**Comment by RasPhilCo** [comment]
Generation: https://github.com/oclif/dev-cli/blob/master/src/commands/manifest.ts
Reading: https://github.com/oclif/config/blob/d84a238cb7b4410a112138a2d957579afcf3875a/src/plugin.ts#L199
