### ISSUE TITLE
Support for pipe

### ISSUE THREAD

**Issue by torres-roberto** [oclif/oclif#245]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature - piping! Is Passing stdout from one cmd to another cmd supported?

**Comment by RasPhilCo** [comment]
Not yet. I want to get to this later this year.

**Comment by halcarleton** [comment]
Are there any workarounds until pipes are officially supported?

**Comment by torres-roberto** [comment]
I love oclif so much I might have to buckle up and contribute to this project.

**Comment by jorge0136** [comment]
Especially given the best practice advocated for [here](https://oclif.io/docs/running_programmatically), I would really love to see piping supported.

**Comment by RasPhilCo** [comment]
Great! I'd start by looking into how parser consumes flag input and look at how we could incorporate stdin.

**Comment by cyrfer** [comment]
I found `oclif` today when i needed to make a cli which handles a data from a pipe.

Is it possible with the current API to at least make a custom hack to consume stdin in any subcommand?

For example, a developer can support a flag like `--from-stdin` with code like:
http://logan.tw/posts/2015/12/12/read-lines-from-stdin-in-nodejs/

**Comment by RasPhilCo** [comment]
As as hack, use `Flag.parse` to read stdin from a boolean flag and set the stdin string value you want to another hidden string flag.

**Comment by endquote** [comment]
@RasPhilCo Do you have a working example of this technique? I'm trying to figure it out too.

**Comment by charlex** [comment]
I am also looking for a solution to this.

**Comment by aviggiano** [comment]
I'd like to see this too @RasPhilCo

**Comment by srlowe** [comment]
+1 for this feature.   @RasPhilCo Would also be interested to understand the specifics of your workaround!

**Comment by srlowe** [comment]
@endquote , @aviggiano Did either of you figure this oclif/stdin hack out?

**Comment by Yukaii** [comment]
Our CLI tool [codimd-cli](https://github.com/hackmdio/codimd-cli) supports pipeline input. 

I made pipe reading to a small promise based module: https://github.com/hackmdio/codimd-cli/blob/f4779995ad2a05aab676bcefa471df8886710624/src/read-stdin-stream.ts#L1-L21. 

```ts
const readPipe: () => Promise<string | undefined> = () => {
  return new Promise(resolve => {
    const stdin = process.openStdin()
    stdin.setEncoding('utf-8')

    let data = ''
    stdin.on('data', chunk => {
      data += chunk
    })

    stdin.on('end', () => {
      resolve(data)
    })

    if (stdin.isTTY) {
      resolve('')
    }
  })
}

export default readPipe
```


Then check pipeline input when the cli starts: https://github.com/hackmdio/codimd-cli/blob/f4779995ad2a05aab676bcefa471df8886710624/src/index.ts#L18-L20

```ts
  async run() {
    const pipeString = await readStdin()

    if (pipeString) {
       // blah blah blah
    } else {
       // blah blah blah
    }
  }
```

The command would look like:

```bash
cat README.md | codimd-cli
```

(https://github.com/hackmdio/codimd-cli#codimd-cli-piping-mode)

**Comment by aviggiano** [comment]
@Yukaii nice solution, but can you pipe multiple `codimd-cli` commands too?

I'd like to see a solution that allows me to

`mycli command1 | mycli command2 | mycli command3`

**Comment by Yukaii** [comment]
Yes, this would work. I just created a sample repository.

The `hello` command writes everything piped-in to stdout.

https://github.com/Yukaii/pipe-demo/blob/182ea821acc6c52a5482537de85c7001e2056e61/src/commands/hello.ts#L26-L32

So if you run:

```
echo 'Hello World' | ./bin/run hello | ./bin/run hello
```

Then you get `Hello World` printed on screen.

![Screen Shot 2020-03-26 at 11 32 53 PM](https://user-images.githubusercontent.com/4230968/77665098-23983800-6fba-11ea-95df-7ba237804f24.png)

**Comment by aviggiano** [comment]
This is wonderful 😍 

Congrats on that implementation, I'll definitely use that

**Comment by GavinRay97** [comment]
I used the example docs to create an abstract base class that consumes a streamed `stdin` buffer during `init()`:

```ts
import Command from '@oclif/command'

async function read(stream: NodeJS.ReadStream) {
  const chunks: Uint8Array[] = []
  for await (const chunk of stream) chunks.push(chunk as Uint8Array)
  return Buffer.concat(chunks).toString('utf8')
}

export default abstract class StdinReceivingCommand extends Command {
  static stdin: string

  async init() {
    StdinReceivingCommand.stdin = await read(process.stdin)
  }
}
```

```ts
import { flags } from '@oclif/command'
import StdinReceivingCommand from './baseClass'

class MyCommand extends StdinReceivingCommand {
  static description = 'describe the command here'

  static flags = {
    // add --version flag to show CLI version
    version: flags.version({ char: 'v' }),
    help: flags.help({ char: 'h' }),
  }

  static args = [{ name: 'files' }]

  async run() {
    const { args, flags } = this.parse(MyCommand)

    console.log('GOT ARGS: ', args)
    console.log('GOT FLAGS: ', flags)
    console.log('Got piped input', MyCommand.stdin)

    const name = flags.name ?? 'world'
    this.log(`hello ${name} from ./src/index.ts`)
  }
}

export = MyCommand
```

![image](https://user-images.githubusercontent.com/26604994/89846864-61a08d80-db50-11ea-85a3-02364291213d.png)

And I'm  just curious whether this is the recommended approach or if the work should actually be done in `@oclif/parser`?

If so, if you just slurp `process.stdin` somewhere during the execution of this:

https://github.com/oclif/parser/blob/master/src/parse.ts

And save the value on some key in the parse result object, it should be good right?

**Comment by Radiergummi** [comment]
@RasPhilCo is stdin processing included in or planned for [`@oclif/core`](/oclif/core)?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
