### ISSUE TITLE
Ability to override / customize --version output

### ISSUE THREAD

**Issue by kabirbaidhya** [oclif/oclif#254]
Hi, is there an ability to override / customize the `--version` output? I want to keep it pretty simple with just cli name and version. 

Right now it reads like this - it gets the `name` from `package.json` and there's no way I can change it.
![image](https://user-images.githubusercontent.com/3315763/60362173-f81ef780-99ff-11e9-8807-4ea656f34e34.png)

Is it possible - I couldn't find anything in the docs / issues yet?

Came across [this issue](https://github.com/oclif/oclif/issues/213) so far - is this related too? 

BTW, can do a PR if this is not yet possible. Thanks.

**Comment by RasPhilCo** [comment]
Yeah, --version is baked into `Main`. Let's use this issue as a feature request to decouple them.

**Comment by kabirbaidhya** [comment]
@RasPhilCo OK. Is this already being worked on? If not, I'd be willing to work on it and do a PR.

**Comment by zhawtof** [comment]
Wondering how developers working on teams running multiple OS and node versions get around this problem?

If a Mac developer runs `oclif-dev readme` she'll produce a different README.md than a Linux developer.

This seems to be breaking the KISS principle in my opinion. I did not ask to know what OS or node I am running yet the `--version` command gives it to me.

Would love to hear the reasons why this was included and to see if they could be considered for removal?

**Comment by RasPhilCo** [comment]
It's helpful for us to know what version of node users are running for support.

**Comment by RasPhilCo** [comment]
If it's annoying to you regarding the README, remove the version handlebars to stop it auto-generating.

**Comment by rubenaeg** [comment]
For anyone running into this issue, you can implement a workaround in two ways, at least that's what I found. The examples are written in TypeScript, but it obviously works in JavaScript as well.

#### 1. Export custom Command class overwriting `_version()`.
```js
import { Main as MainCommand } from '@oclif/command';
import { LoadOptions } from '@oclif/config';

class BaseCommand extends MainCommand {
    _version() {
        console.log('Your fancy version output here.');
	return this.exit(0);
    }
}

function run(argv = process.argv.slice(2), options?: LoadOptions) {
    return BaseCommand.run(argv, options);
}

export { run };
```

This emulates a command class, which derives from the Main class from `@oclif/command/main`. The only thing you need to overwrite is the `_version()` property, as all version output will be printed out here. It's important to return `this.exit(0)`, else oclif will continue executing it's middleware. The last thing you need to do now is to import the `run` property in your `bin/` folder and execute it.

```js
#!/usr/bin/env node

const { run } = require('path-to-your-own-command-class');

run()
    .then(require('@oclif/command/flush'))
    .catch(require('@oclif/errors/handle'));
```

This also works with async operations, however it is way more complex, so I won't include it in this comment.

#### 2. Use Lifecyce Hooks

The cleaner option is to just use the already provided hook functionality.

```js
export default async function hook() {
  if (['-v', '-V', '--version', 'version'].includes(process.argv[2])) {
    console.log('Your fancy version output here.');
    return process.exit(0);
  }
}
```

Add the hook to your oclif config (more on that [here](https://oclif.io/docs/hooks)) and you're good to go!

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
