### ISSUE TITLE
Question: How to override a plugin so that it is hidden by default?

### ISSUE THREAD

**Issue by tcf909** [oclif/oclif#267]
I apologize in advance for the open issue. I'm looking at the easiest way to hide a plugin (like help and autocomplete) without forking the plugins (just to set the static property hidden).

I want the plugin functionality, but just don't need it show in the menu by default (--all would be fine).

Any guidance would be appreciated.

Thank you.

**Comment by RasPhilCo** [comment]
Interesting. Yeah, plugins are pretty much "as-is".

**Comment by tcf909** [comment]
@RasPhilCo Thanks for the response. We'll go ahead and just patch the plugins for now -- but the extensibility aspect via configuration (+overrides) is something to think about for the future.

I understand you guys built this for your own use, but as more people get ahold of it, might be nice to standardize on the "configuration" mindset you have with a couple of things already (like topic descriptions). 

Since you are already reading package.json, anything stored in there is almost zero cost. You could include things like separator delimiter, but also overrides for plugin settings.

Totally get this has to work for Heroku first, but I bet you could get a lot out of the community if you flexed a little bit to support broader use cases.

The work you guys have already done is awesome. Hoping to help take it one step further.

Thanks again for your response.
