### ISSUE TITLE
Question: What are TS type for "flags" and "args"?

### ISSUE THREAD

**Issue by ozum** [oclif/oclif#268]
Hi,

I searched for docs and issues but couldn't find an answer. Using TS, I want to pass `args` and `flags` to other methods/functions, but couldn't find how to type them.

```ts
export default class Hello extends Command {
  async run() {
    const {args, flags} = this.parse(Hello);
    this.someMethod(args, flags);
  }

  //           ⤹     ⤹ What type should be those?
  someMethod(args, flags): void {
    // ...
  }

  //                 ⤹                  ⤹ I assumed something like that is exported, but not.
  someOther(args: Args<Hello>, flags: Flags<Hello>): void {
    // ...
  }

  //           ⤹  I want to avoid manually typing for every function.
  someMore(flags: { force: boolean, opt1: string, opt2: string }  ): void {
    // ...
  }
}
```

What are the proper types for `args` and `flags`, without repeating the code by manually adding types for every function.

Many thanks.

**Comment by RasPhilCo** [comment]
The types are defined here https://github.com/oclif/parser/blob/master/src/parse.ts#L24-L25

Generically, they are something akin to  `{[key: string]: string | boolean | number}`.

**Comment by ozum** [comment]
It is not something general like `{[key: string]: string | boolean | number}`. Otherwise type errors cannot be detected as seen screenshots below.

![Screen Shot 2019-07-20 at 07 00 30](https://user-images.githubusercontent.com/1497060/61573733-15555c00-aabc-11e9-8b5c-653f8442fe80.png)

![image](https://user-images.githubusercontent.com/1497060/61573689-847e8080-aabb-11e9-807c-dfee4c348cf3.png)

Also I saw `parse.ts`, but,
1. In `parse.ts`, I can only imagine a very indirect way such as `ReturnType<X.Y<Z>>`, which I couldn't find anyway.
2. `parse.ts` is not one of the dependencies in `package.json` created/updated by generator, so it seems not encouraged to import a type from `parse.ts`.

There should be some direct way to import that type that I miss, otherwise as a feature request it is a good idea to add those types.

**Comment by ukcrpb6** [comment]
Something like the following works, note that there is no further type information for Args available from oclif types.

```typescript
interface Args { [name: string]: any };

type Options<T> = T extends Parser.Input<infer R>
  ? Parser.Output<R, Args>
  : any;

type Flags<T> = Options<T>['flags'];

export default class Hello extends Command {
  // ...
  someOther(args: Args, flags: Flags<typeof Hello>): void {
    // ...
  }
}
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by mdornseif** [comment]
With oclif 4 something like this gives decent results:

`type Tflags = OutputFlags<typeof Hello.flags>`
