### ISSUE TITLE
[question] Clarity around code re-use

### ISSUE THREAD

**Issue by xavdid** [oclif/oclif#274]
I was reading [this doc about running commands programatically](https://oclif.io/docs/running_programmatically#sharing-code-with-modules) and wanted a little clarification around the following example:

```ts
// ./src/display_config_vars.ts

async function displayConfigVars(app: string) {
  const config = await api.get(`/apps/${app}config-vars`)
  for (let [key, value] of Object.entries(config)) {
    this.log(`${key}=${value}`) // <-- where does `this` come from?
  }
}

// ./src/commands/release.ts

import {displayConfigVars} from '../display_config_vars'

export class HerokuRelease extends Command {
  static flags = {
    app: flags.string({required: true})
  }

  async run() {
    const {flags} = this.parse(HerokuRelease)
    await this.doRelease(flags.app)
    await displayConfigVars(flags.app)
  }
}
```

in the `displayConfigVars` function, what does the `this` refer to? Is there an implied `export class DisplayConfigVars extends Command` wrapping it?

I'm having the issue that I want to break code into little functions, but also want that code to take advantage of helpful utils on `@oclif/command`. 

In any case, can we amend that example to contain a full working code?

**Comment by RasPhilCo** [comment]
You can't abstract to a function outside the class with the reference to `this` unless you then use `.bind`. If you want to share code between commands, you likely want a [base class](https://oclif.io/docs/base_class).

**Comment by xavdid** [comment]
Right, that's why the existing docs (copied above) are confusing. `display_config_vars.ts` references `this`, but doesn't seem to be wrapped in a command.

**Comment by RasPhilCo** [comment]
Ah I see what you're saying, let's make that a working example. Happy for a PR.

**Comment by xavdid** [comment]
Yeah, happy to! i just don't know what the "correct" answer is. Is it to make a `DisplayConfigVarsCommand`, mark it as hidden, and call `DisplayConfigVarsCommand.run()`? Because that's what looks to be discouraged at the bottom of that doc.

**Comment by xavdid** [comment]
@RasPhilCo @jdxcode just wanted to follow up - do y'all have an idea of the best way to approach this?

**Comment by RasPhilCo** [comment]
My first thought:

```
import ux from 'cli-ux'

async function displayConfigVars(app: string, logger = ux.log) {
  const config = await api.get(`/apps/${app}config-vars`)
  for (let [key, value] of Object.entries(config)) {
    logger(`${key}=${value}`) // <-- where does `this` come from?
  }
}

```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
