### ISSUE TITLE
Would like to be able to add a "default" command when no command is given

### ISSUE THREAD

**Issue by jemilox** [oclif/oclif#277]
I'd like to request a feature.
-----------------------------------------------------

What is the current behavior?
-----------------------------
When you run ./bin/run you automatically get a help menu.

What is the expected behavior?
------------------------------
I'd like to assign functionality to that base menu when a command is not run. Basically I'd like to assign a default command that runs.

**Comment by rizzlesauce** [comment]
I have implemented this feature. I'll submit a pull request shortly.

**Comment by jemilox** [comment]
Wow, awesome sauce, thanks! We will definitely be using this!

**Comment by BinaryBen** [comment]
The PR doesn't seem to have been merged. `oclif command index` works to replace the help menu being shown though. Include what you like in there.

See https://oclif.io/docs/running_programmatically for running another command if needed.

**Comment by rizzlesauce** [comment]
> The PR doesn't seem to have been merged. `oclif command index` works to replace the help menu being shown though. Include what you like in there.

@BinaryBen I'm not familiar with `oclif command index`. Could you point me to an example or documentation?

**Comment by BinaryBen** [comment]
> > The PR doesn't seem to have been merged. `oclif command index` works to replace the help menu being shown though. Include what you like in there.
> 
> @BinaryBen I'm not familiar with `oclif command index`. Could you point me to an example or documentation?

I don't think there is documentation. But create a command called index (I suspect this is what is trying to be achieved by adding default - it already exists, it's just called index), and add a custom help output there.

**Comment by rizzlesauce** [comment]
@BinaryBen I tried to make the index command in the commands folder. It didn't appear to be recognized. Maybe it only works in the context of topics?

**Comment by BinaryBen** [comment]
It's working fine for me.

In your project directory, run `$ oclif command index` then (assuming you have linked it to your bin file via `npm link`), `$ projectname` without any other arguments. 

It should print the basic "hello world from [...] /projectname/src/commands/index.js" message. I'm using Oclif v1.15.2 in the project I'm using it in. 

You should be able to put what you like in the run() function...

**Comment by rizzlesauce** [comment]
@BinaryBen I followed your instructions and still didn't get the expected results. It just shows the help screen when I run the command without args--it doesn't show the hello world message. Which version of \@oclif/command do you have in your dependencies section of package.json? I'm using my own forked variant of v1.5.19 (latest version). And thank you for your help!

**Comment by avf** [comment]
I also tried following @BinaryBen's instructions, didn't work for me either.

I don't quite understand what running `/bin/run` does. I mean, it seems to call `.run` on the `@oclif/command` default package export, which then somehow finds all the commands in the `commands` folder. But I don't understand where the main entrypoint in MY code is (before any of the commands get executed). The file `src/index.ts`, doesn't seem to ever be executed.  It was created by running the initial generator with `oclif multi`.

When running `oclif command index`, the file `src/commands/index.ts` is created, which *is* being treated special in some way. For example, it's not included in the help, and its usage is correctly added to the readme. However, the command is never executed, neither with `./bin/run index`, nor just `./bin/run`. So maybe this is just a bug?

@rizzlesauce Did you figure out a way to make this work?

**Comment by snowyu** [comment]
I think we need a simple way to redirect a command if command not found.
Could the `command_not_found` hook do such thing?

**Comment by snowyu** [comment]
Saddy the hook can not return a value.

https://github.com/oclif/config/blob/db13f7ee111399af912eda945b3d1f597c4debe4/src/config.ts#L353-L356

So only way I have found :

```ts
import {CLIError, error, exit, warn} from '@oclif/errors'
import {Hook, Config, Command} from '@oclif/config'
import Debug from '@oclif/config/lib/debug'

const debug = Debug();

// replace the runCommand method
Config.prototype.runCommand = async function runCommand(this: Config, id: string, argv: string[] = []) {
  debug('runCommand %s %o', id, argv)
  let c = this.findCommand(id)
  // add codes here 
  if (!c) {
    c = this.findCommand('default') // or change to your default command id here.
    argv.unshift(id)  // push back the id as argument 
  }
  if (!c) {
    await this.runHook('command_not_found', {id})
    throw new CLIError(`command ${id} not found`)
  }
  const command = c.load()
  await this.runHook('prerun', {Command: command, argv})
  const result = await command.run(argv, this)
  await this.runHook('postrun', {Command: command, result: result, argv})
}


```

**Comment by snowyu** [comment]
PR is here: https://github.com/oclif/config/pull/139

**Comment by NicolasReibnitz** [comment]
The way I dealt with this is by using the bin/run file to check if there are any arguments to the process. If not, I add one myself. Only then the whole require('@oclif/command').run() stuff is executed.

Something like
```javascript
#!/usr/bin/env node

if (process.argv.length === 2) {
  process.argv[2] = 'somedefaultcommand';
}

require('@oclif/command')
  .run()
  .then(require('@oclif/command/flush'))
  .catch(require('@oclif/errors/handle'));
```
Granted, it's a bit hacky, but it works for now.
I just hope that there are no edge cases where that bin/run file doesn't run. But I can't see how.

Are there any reasons that speak against this approach?

And while we are at it: what DOES that src/index.js file do? Seems like nothing. At least not in a multicommand project. But I might be wrong about that, of course.

**Comment by RasPhilCo** [comment]
I've shipped root index command functionality -  i.e. src/commands/index.ts - in the latest versions of:
- config v1.17.0
- command v1.8.0
- plugin-help v3.2.0

It supports flags/args & command help while maintaining root cli help output. 

Give it a shot! And let me know if you see anything weird.

```
$ ./bin/run
Running src/commands/index command!
```

**Comment by RasPhilCo** [comment]
I find this behavior confusing to users but, nevertheless, If you want to alias an existing command to also be the root index command:

```
static aliases = [''] // empty strings, which is the ID of src/commands/index.ts
```

**Comment by jbournonville** [comment]
> I find this behavior confusing to users but, nevertheless, If you want to alias an existing command to also be the root index command:
> 
> ```
> static aliases = [''] // empty strings, which is the ID of src/commands/index.ts
> ```

I've tried this but it's not working with `"@oclif/core": "^1.16.4"`, still have the help screen

**Comment by f1729** [comment]
> > I find this behavior confusing to users but, nevertheless, If you want to alias an existing command to also be the root index command:
> > ```
> > static aliases = [''] // empty strings, which is the ID of src/commands/index.ts
> > ```
> 
> I've tried this but it's not working with `"@oclif/core": "^1.16.4"`, still have the help screen

This isn't working to me too with `"@oclif/core": "^1.16.5"` , is there anything we can do to achieve the same? @RasPhilCo

**Comment by f1729** [comment]
@jbournonville I found this and is working. 

https://github.com/oclif/oclif/issues/835#issuecomment-1055103139

**Comment by sergei-dyshel** [comment]
This method (adding `default`) doesn't work anymore. I was removed in eaf5a8692c85d37b1c1728230a851151a895704f.

@mdonnalley 
Is there a way to accomplish this now?

**Comment by sergei-dyshel** [comment]
Nevermind, found the solution here: https://github.com/oclif/oclif/discussions/1494#discussioncomment-10150320.
