### ISSUE TITLE
Question: test with tap and plain javascript

### ISSUE THREAD

**Issue by Eomm** [oclif/oclif#280]
Hi,
I would like to test a oclif multiple CLI with `tap` and written in JavaScript

I would ask if the path I'm following is right or there are further consideration that I'm missing because I have a strange behaviour.

My tests looks like:

```
const { test } = require('tap')

const Command = require('../../src/index')

test('subscribe', async t => {
  const exec = Command.run(['sub', '-h'])
  try {
    await exec
  } catch (error) {
    console.log({ error })
    console.log(error.oclif.exit)
  }
})
```

the `Command` object is the `index.js` file that has been generated by oclif cli.

This works and fits my need, but it is not clear to me why the `run` method throws always an exception with exit code `0`. I expect that the promise resolves successfully.

Is it right or there is something wrong with my code?

This is the console output:

```
{ error:
  { Error: EEXIT: 0
      at Object.exit (kingdis\node_modules\@oclif\errors\lib\index.js:18:11)
      at Subscribe.exit (kingdis\node_modules\@oclif\command\lib\command.js:54:36)
      at Subscribe._help (kingdis\node_modules\@oclif\command\lib\command.js:126:21)
      at Subscribe.catch (kingdis\node_modules\@oclif\command\lib\command.js:89:25)
      at Subscribe._run (kingdis\node_modules\@oclif\command\lib\command.js:48:29) oclif: { exit: 0 }, code: 'EEXIT' } }
0
```

**Comment by RasPhilCo** [comment]
Looks like your class Subscribe is throwing at line 48.

**Comment by Eomm** [comment]
It should not be called at all: in the test script I'm calling the default help command - via `-h` flag (and it works, I see the correct stdout), but then the promise is rejected.

Here all the code
https://github.com/Eomm/kingdis/tree/first-impl
(you need a local redis to run it if you would like)

**Comment by RasPhilCo** [comment]
I'll pull this down tomorrow and take a look.

**Comment by StarpTech** [comment]
@eomm you have to import the exact command `../command/sub.js` not the index file.

**Comment by Eomm** [comment]
> @Eomm you have to import the exact command `../commands/sub.js` not the index file.

I didn't found how to instantiate it:

```
const { test } = require('tap')
const Command = require('../../src/commands/subscribe')
const { Config } = require('@oclif/config')

test('instance', t => {
  const x = new Command(['-h'], new Config())
  x.run()
  t.pass()
})

// Cannot read property 'channel' of undefined
//      const channels = this.flags.channel
//     --------------------------------^
```

Thank you @RasPhilCo for your check, I added the help test only because my first error was to overwrite the `-h` parameter 😆

I will follow the `help` command rewrite since I would like to customize some value like the example of assignment (for example from: `-d, --db=db              redis db` to `-d, --db=12              redis d` 

> Fancy test was written to make testing oclif command's (and command errors) easier

I will try to use it directly with tap, I'm a big fan of `node my.test.js` 😅

**Comment by StarpTech** [comment]
@eomm as described in the docs. There is a static method.
```js
import ImportAlgoliaCommand from '../src/commands/myCommand'
await ImportAlgoliaCommand.run([flags])
```

**Comment by Eomm** [comment]
I didn't get it!
Thank you @StarpTech it works
