### ISSUE TITLE
Optional arguments overriden with subsequent boolean flag

### ISSUE THREAD

**Issue by tedconn** [oclif/oclif#287]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

I'm pretty sure this is a bug although I can probably change my argument to be a flag without too much hassle.

What is the current behavior?
-----------------------------

Given a command:

```javascript
class TestCommand extends Command {
  static flags = {
    isTest: flags.boolean({
      description: "Do a dry run"
    })
  };

  static args = [
    { name: 'dir', required: false, description: 'The root directory' },
  ];

  async run() {
    console.log(this.parse(TestCommand));
  }
}
```

if I run `mycli test --isTest=true` this will log:

```
{ 
  args: { dir: "true" },

  flags: { isTest: true }
}
```

Notice that the arg `dir` is set to `true`. Although the flag is properly set.

What is the expected behavior?
------------------------------
The expected behavior is that the optional argument is not defined as an argument in the above example.

**Comment by tedconn** [comment]
After further digging it seems like passing boolean flags as `=true` isn't supported?

**Comment by RasPhilCo** [comment]
Correct, just as switches.
