### ISSUE TITLE
Cannot generate manifest when using baseUrl and paths in TypeScript's tsconfig.json

### ISSUE THREAD

**Issue by yndc** [oclif/oclif#288]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
I think this is more of a feature request to support `baseUrl`and `paths` in `tsconfig.json`.

What is the current behavior?
-----------------------------
I am currently using `baseUrl`and `paths` in my `tsconfig.json` for development convenience (removing the need to do relative imports). At the moment one single import inside commands folder that uses the `paths` prefix will throw an error when trying to generate the manifest through `oclif-dev manifest`.

The error as follows:
```
Error Plugin: oclif-issue: Cannot find module '~/other'
Require stack:
- /Users/yondercode/dev/node/oclif-issue/src/commands/hello.ts
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/config/lib/plugin.js
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/config/lib/config.js
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/config/lib/index.js
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/command/lib/command.js
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/command/lib/index.js
- /Users/yondercode/dev/node/oclif-issue/node_modules/@oclif/dev-cli/bin/run
    at Object.<anonymous> (~/dev/node/oclif-issue/src/commands/hello.ts:3:1)
    at Module.m._compile (~/dev/node/oclif-issue/node_modules/ts-node/src/index.ts:473:23)
    at Object.require.extensions.<computed> [as .ts] (~/dev/node/oclif-issue/node_modules/ts-node/src/index.ts:476:12)
```

All tests are passing and `tsc` are working.

### Reproduction

1. Add inside `tsconfig.json`:

```
...
"baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
...
```
2. Do any import with `~/` prefix
3. Run `oclif-dev manifest`

Version: `oclif 1.5.19`

**Comment by pie6k** [comment]
I have the same issue

**Comment by mkosir** [comment]
Same issue, since this issue was opened 3 years ago, any news on this?

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by devilmark84** [comment]
For sure I've no experience with ts-node but it's crazy that I've to add the call to tsconfig-paths everywhere instead of reading it from the tsconfig.json.
