### ISSUE TITLE
Typed args parsing

### ISSUE THREAD

**Issue by dhleong** [oclif/oclif#301]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
This is a feature request

What is the current behavior?
-----------------------------
Currently, the `args` key as returned by `parse()` seems to just be `any` type.

What is the expected behavior?
------------------------------
```
    "@oclif/command": "^1.5.19",
```

I just started playing with oclif, having used yargs in the past. There's a lot to like about oclif for my current use case, but one thing I think could be improved is type safety on the `args` map. As-is, it's a bit tricky to get the raw names from the `static args` array, but it's possible to take advantage of Typescript 3.4's `as const` assertion. Here's some typings I came up with:

```typescript
interface IArgsList {
    [index: number]: {name: string};
}
interface IParserInput {
    args?: IArgsList;
}

type NameOf<T> = T extends {name: string}
    ? T["name"]
    : never;

type RequiredNameOf<T> = T extends {required: true}
    ? NameOf<T>
    : never;

type OptionalNameOf<T> = T extends {required: true}
    ? never
    : NameOf<T>;

type RequiredArgsOf<Args extends IArgsList> = RequiredNameOf<Args[number]>;
type OptionalArgsOf<Args extends IArgsList> = OptionalNameOf<Args[number]>;

type ArgsMap<
    Args extends IArgsList,
> = {
    [K in RequiredArgsOf<Args>]: string
} & {
    [K in OptionalArgsOf<Args>]: string | undefined
};

type TypedArgsOf<T extends IParserInput> = T extends { args: IArgsList }
    ? ArgsMap<T["args"]>
    : {};
type HelloArgs = TypedArgsOf<typeof Hello>;
```

These don't account for the `parse` option, but it's a start. 

Thoughts?

**Comment by dhleong** [comment]
Here's a gnarly version that takes into account `parse` both functions and required-ness:

```typescript
type TypeOf<T, N extends string = NameOf<T>> = T extends {
    name: N,
    parse: (raw: string) => infer R,
}
    ? T extends {required: true}
        ? {[key in N]: R}
        : {[key in N]?: R}
    : T extends {required: true}
        ? {[key in N]: string}
        : {[key in N]?: string};

type TypesOf<Args extends IArgsList> = {
    [I in keyof Args]: TypeOf<Args[I]>
}[number];

type UnionToIntersection<U> =
  (U extends any ? (k: U) => void : never) extends ((k: infer I) => void)
  ? I
  : never;

type TypedArgsOf2<T extends IParserInput> = T extends { args: IArgsList }
    ? UnionToIntersection<TypesOf<T["args"]>>
    : {};

type HelloTypes = TypedArgsOf2<typeof Hello>;
```

Credit goes to [this stackoverflow](https://stackoverflow.com/a/50375286/11601052) answer for the `UnionToIntersection` type. I admit I'm still trying to grok it, but it works!

A rather glaring disadvantage of this one is that without `as const` all properties coalesce to the lowest common denominator type, which if you have `parse` and not `required: true` can become `undefined`.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
