### ISSUE TITLE
Command not found if using ".tsx" extension

### ISSUE THREAD

**Issue by TranquilMarmot** [oclif/oclif#309]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

A bug :bug: 

What is the current behavior?
-----------------------------

I'm trying to use [`react-blessed`](https://github.com/Yomguithereal/react-blessed) with `oclif`. This means that the file that my command ends in `.tsx`.

My command is at `./src/commands/my-command.tsx` and in my `package.json` I have `oclif.commands` set to `./lib/commands` (`"outDir": "lib"` is set in `tsconfig.json`).

When I do `./bin/run my-command` I get an error that there is no command called `my-command`.

Example `my-command.tsx` file (basically the "Hello World" from `react-blessed`):

```tsx
import { Command } from "@oclif/command";
import React, { Component } from "react";
import blessed from 'blessed';
import { render } from 'react-blessed';

// Rendering a simple centered box
class App extends Component {
  render() {
    return (
      <blessed-box
        top="center"
        left="center"
        width="50%"
        height="50%"
        border={{ type: "line" }}
        style={{ border: { fg: "blue" } }}
      >
        Hello World!
      </blessed-box>
    );
  }
}

export default class MyCommand extends Command {
  async run() {
    // Creating our screen
    const screen = blessed.screen({
      autoPadding: true,
      smartCSR: true,
      title: "react-blessed hello world"
    });

    // Adding a way to quit the program
    screen.key(["escape", "q", "C-c"], function(ch: string, key: string) {
      return process.exit(0);
    });

    // Rendering the React app using our screen
    const component = render(<App />, screen);
  }
}

```

I also tried to move all of the `.tsx` code to another file and then import that from my command, but that results in a `MODULE_NOT_FOUND` error on the import.

What is the expected behavior?
------------------------------
The command should be found.

**Comment by RasPhilCo** [comment]
We'll need to add tsx support as this implementation is growing support.

**Comment by jorge0136** [comment]
I too am interested in using `.tsx` files with oclif.

There is a discussion of some folks attempting to use `.tsx` in this [ink issue](https://github.com/vadimdemedes/ink/issues/239). This [comment](https://github.com/vadimdemedes/ink/issues/239#issuecomment-561719774) specifically contains a some details about a work around.

**Comment by ryanwilsonperkin** [comment]
@TranquilMarmot could you try the change in https://github.com/oclif/oclif/issues/309 and see if it works for your example?

**Comment by endquote** [comment]
I'm running into this as well.

I'm not sure how to try the proposed change. I edited my local `node_modules/@oclif/config/lib/plugin.js` to include this bit in `get commandIDs()`, but that didn't seem to do the trick.

```javascript
const patterns = ["**/*.+(js|ts|tsx)", "!**/*.+(d.ts|test.ts|test.js|spec.ts|spec.js)?(x)"];
```

I tried to `npm install --save https://github.com/ryanwilsonperkin/config.git`, but got lots of build errors.

**Comment by ryanwilsonperkin** [comment]
@endquote did you get [this bit](https://github.com/oclif/config/pull/96/files#diff-bbc0ee6b2ca5b4ef994c8cecb234631aR78) as well in `node_modules/@oclif/config/lib/ts-node.js`? That's responsible for telling oclif's `ts-node` configuration to transpile the jsx syntax. 

I wouldn't bother trying to install from my git branch as it hasn't passed through any compile/pack steps so it probably won't be usable in that form.

**Comment by endquote** [comment]
Thank you @ryanwilsonperkin, I was indeed missing that change. Patching both files got it working.

That also explains why my attempted workaround didn't work. I made a `tsx` file outside of `commands` and tried to import a function from it, but that gave me errors as well. I suppose because oclif is doing its own compilation.
