### ISSUE TITLE
Uncovered line numbers incorrect from nyc test output

### ISSUE THREAD

**Issue by Dylanlan** [oclif/oclif#314]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
The outputted uncovered line numbers from running the `test` script in package.json don't seem to match the line numbers in the corresponding .ts files.

I can reproduce this with a fresh project:

1. Create a new cli by running: `npx oclif multi testing`
2. Choose yarn, Typescript, tslint, and mocha
3. Run `yarn test` after it's created
4. Note that it lists line `10` as uncovered from `hello.ts`
5. Line 10 seems to only be a closing array bracket, not the uncovered `if` block

What is the expected behavior?
------------------------------
It should output the correct line number(s), which for the above example project should be 28 (the log statement inside the `if` block)

I'm interested if there's some combination of nyc or mocha options that I can use to get the proper line numbers, but a fresh project should probably be working as expected.

It definitely seems like nyc and mocha should support proper line numbers from typescript.
I've tried following the steps mentioned in these links, and gotten it to inconsistently output line 26 (which is still off by 2), but not reliably (still can output line 10 seemingly randomly):

https://istanbul.js.org/docs/tutorials/typescript/

https://github.com/istanbuljs/nyc/issues/618

I'm using macOS 10.15.1 Catalina, node 10.17.0, and yarn 1.19.1

**Comment by Idered** [comment]
I can confirm this issue. I'm also getting invalid output. I've tried multiple tsconfig, nyc configurations.
 ![](https://i.imgur.com/Uu7hZ5z.png)

**Comment by zbarbuto** [comment]
Likely related https://github.com/oclif/test/issues/50

**Comment by Dylanlan** [comment]
I'm still running into this issue today, but have some more findings.
From the findings in https://github.com/oclif/test/issues/50, it does seem directly related to the `.command()` used in the tests.

If I change the tests to use the `customTest` and `.run()` workaround specified from that issue, I see the correct line number.
Alternatively, if I add this:
```
import Hello from '../../src/commands/hello'
describe('fix uncovered lines', async () => {
    await Hello.run([])
})
```
then it seems to report the correct lines, even when still using the tests that run `.command()`.
And I'm not able to reproduce this issue from a single command cli from `npx oclif single`, since it uses `.run()` in its tests

So it seems that running tests from only `.command()` causes some sort of source mapping problem, but running the command's `.run()` will fix it

This is with oclif 1.16.1, macOS 10.15.4 Catalina, yarn 1.22.4, and node 12.16.0

**Comment by Dylanlan** [comment]
We were still running into some coverage issues with our CLI, and potentially narrowed our problem down to the `proxyquire` package somehow interacting with the command's `.run()` method. Using either on their own seemed to report correct line numbers, but mixing them caused inconsistencies.

We ended up using a workaround to call the command's `_run()` method in tests, instead, which is kinda gross but seems to be working alright for us so far.

Something like this:

```
import proxyquire from 'proxyquire';

const proxyquireCommand = (location: string, stubs: any) => {
    const Proxied = proxyquire(location, stubs).default;
    const stubbedConfig = {
        scopedEnvVarKey: () => {},
    };
    return {
        run: async (args: string[]) => {
            return new (Proxied)(args, stubbedConfig)._run(args);
        },
    };
};

describe('command', () => {
    it('should do something', async () => {
        const command = proxyquireCommand(<COMMAND_PATH>, {
            'some-dependency': stubbedDependency,
        });
        await command.run([]);
        expect(something)...
    });
});
```

Curious to hear if there's any other workarounds!

**Comment by OldSneerJaw** [comment]
I posted a workaround to oclif/test#50 that is minimally invasive, although I cannot guarantee it will work in all cases.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
