### ISSUE TITLE
Make generator respect custom path to command files

### ISSUE THREAD

**Issue by binaryben** [oclif/oclif#317]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------

* Move the source files (src/index.js, src/base.js, src/commands/\*) to a different directory (i.e., ./source/*)
* Update the package.json and run file to reflect change (see below)
* Run `oclif command example`. It generates the command under /src/command/example.\*\*

```
"oclif": {
    "commands": "./source/commands",
    "bin": "***",
    "plugins": [
      "@oclif/plugin-help"
    ]
  },
```

For clarity, the CLI works as expected at this point. The generator does not.

What is the expected behavior?
------------------------------

Oclif should check package.json -> oclif.commands to see where to generate a new command when running `oclif command example` instead of assuming the default.

I think the problem is in [src/generators/command.ts](https://github.com/oclif/oclif/blob/master/src/generators/command.ts) at line 45

**Comment by mlovrovich** [comment]
+1

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by binaryben** [comment]
Just an update, this has actually been resolved now with the full migration to Typescript.

I changed `tsconfig.json` to this and everything seems to be resolving correctly now:

```
{
  "compilerOptions": {
    "declaration": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": ".",
    "strict": true,
    "target": "es2019",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "source/**/*",
    "commands/**/*",
    "modules/**/*"
  ],
  "exclude": [
    "node_modules/**/*"
  ]
}
```
