### ISSUE TITLE
oclif breaks when repo field is object

### ISSUE THREAD

**Issue by binyamin** [oclif/oclif#318]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
1. Run `npm i -g oclif`
2. Navigate to an existing repo's directory
3. run `oclif multi`, and select the relevant options
4. Watch oclif complain that "TypeError: this.pjson.repository.startsWith is not a function"
```
TypeError: this.pjson.repository.startsWith is not a function
    at App.writing (C:/Users/Carl/AppData/Roaming/npm/node_modules/oclif/lib/generators/app.js:320:68)
    at Object.<anonymous> (C:/Users/Carl/AppData/Roaming/npm/node_modules/oclif/node_modules/yeoman-generator/lib/index.js:424:27)
    at C:/Users/Carl/AppData/Roaming/npm/node_modules/oclif/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at C:/Users/Carl/AppData/Roaming/npm/node_modules/oclif/node_modules/run-async/index.js:24:19
    at C:/Users/Carl/AppData/Roaming/npm/node_modules/oclif/node_modules/yeoman-generator/lib/index.js:425:13
```
What is the expected behavior?
------------------------------
Not sure, since this is my first type using oclif 😀. Wasn't expecting an error, though.

`oclif/1.15.2 win32-x64 node-v12.14.1`
Windows 10

**Comment by b3u** [comment]
Relevant repo: https://github.com/b3u/epkit

**Comment by RasPhilCo** [comment]
Run `oclif multi` in an empty directory, oclif thinks your package.json is already an oclif project.

**Comment by b3u** [comment]
The issue was the structure of my `package.json`. The repository field was an object, rather than a string.

**Comment by b3u** [comment]
Repository fields are allowed to be objects; I think that this is a bug worth fixing.

**Comment by RasPhilCo** [comment]
See also #354

**Comment by binyamin** [comment]
@mdonnalley Would you mind explaining why this is "not planned"? It shouldn't be too complicated, and it's breaking the spec.
