### ISSUE TITLE
Explicitly typing Command.args

### ISSUE THREAD

**Issue by slavafomin** [oclif/oclif#319]
Hello!

Thank you for this great framework!

However, right now, it's impossible to correctly type `args` static property of the custom command, because required types (`IArg` interface) are not exported from `@oclif/command` package.

I believe, `@oclif/command` package should re-export `IArg` from the `@oclif/parser` package.

This is not the case for `flags` though, because required types are available:

```typescript
import Command, { flags as Flags } from '@oclif/command';

export interface MyCommandFlags {
  preset?: string;
}

export abstract class MyCommand extends Command {

  public static flags: Flags.Input<MyCommandFlags> = {
    preset: Flags.string({
      default: 'default',
      description: `settings preset`,
    }),
  };

  public static args: ??? = [
    { name: 'foo' },
    { name: 'bar' },
  ];

}
```

Also, I would suggest to update documented examples to use explicit types for `args` and `flags` properties, otherwise correct typing support is not guaranteed.

**Comment by slavafomin** [comment]
I believe there is also no way to specify type of the expected args, so that `const { args } = this.parse(ScriptRunCommand);` would return typed result.

**Comment by mdstaff** [comment]
I'm curious if you've identified any alternatives or solutions to this issue.  I ran into something similar when trying to add type support to flags. I attempted to use the flags.build method but had a similar error. I'm also new to TS so I'm not sure if there's a better way to use TypeScript to get that effect.

```
import { Command, flags } from '@oclif/command'
function getProperty<T, K extends keyof T>(obj: T, key: K) {
    return obj[key];
}
type BrowserFlag = Record<BrowserType, BrowserOptions>
type BrowserType = "safari"
  | "firefox"
  | "chrome"
  | "edge"
  | "ie";
const BrowserFlags: BrowserFlag = {
  safari: {
    browsers: [
      Browsers.Desktop.Mac.Safari,
      Browsers.Desktop.Mac.Safari_12,
      Browsers.Desktop.Mac.Safari_11,
    ]
  },
  ...
}
const browserOptions: BrowserType[] = [
  "safari",
  "firefox",
  "chrome",
  "edge",
  "ie"
];
const browser = flags.string({
  description: 'choose from a list of browsers',
  options: browserOptions,
  required: true
});
export default class BrowserFinder extends Command {
    static flags = {browser}
    async run() {
      const {browser} = flags
      // @ts-ignore Argument of type 'string' is not assignable to parameter of type 'BrowserType'.ts(2345)
      const options = getProperty(BrowserFlags, browser);
      console.log(options);
    }
}
```

I get the `// @ts-ignore` compiler error when using the getProperty method or when trying to access the property directly with BrowserFlags[browser]. I'm trying to figure out how to get TypeScript to allow the expression or how to convert the string to the proper type.  It looks like you were trying to do the same.

Hope that helps,
Matt

**Comment by mdstaff** [comment]
I'm curious if you've identified any alternatives or solutions to this issue.  I ran into something similar when trying to add type support to flags. I attempted to use the flags.build method but had a similar error. I'm also new to TS so I'm not sure if there's a better way to use TypeScript to get that effect.

```
import { Command, flags } from '@oclif/command'
function getProperty<T, K extends keyof T>(obj: T, key: K) {
    return obj[key];
}
type BrowserFlag = Record<BrowserType, BrowserOptions>
type BrowserType = "safari"
  | "firefox"
  | "chrome"
  | "edge"
  | "ie";
const BrowserFlags: BrowserFlag = {
  safari: {
    browsers: [
      Browsers.Desktop.Mac.Safari,
      Browsers.Desktop.Mac.Safari_12,
      Browsers.Desktop.Mac.Safari_11,
    ]
  },
  ...
}
const browserOptions: BrowserType[] = [
  "safari",
  "firefox",
  "chrome",
  "edge",
  "ie"
];
const browser = flags.string({
  description: 'choose from a list of browsers',
  options: browserOptions,
  required: true
});
export default class BrowserFinder extends Command {
    static flags = {browser}
    async run() {
      const {browser} = flags
      // @ts-ignore Argument of type 'string' is not assignable to parameter of type 'BrowserType'.ts(2345)
      const options = getProperty(BrowserFlags, browser);
      console.log(options);
    }
}
```

I get the `// @ts-ignore` compiler error when using the getProperty method or when trying to access the property directly with BrowserFlags[browser]. I'm trying to figure out how to get TypeScript to allow the expression or how to convert the string to the proper type.  It looks like you were trying to do the same.

Hope that helps,
Matt

**Comment by slavafomin** [comment]
@mdstaff Hello! Please delete the duplicate messages.

**Comment by slavafomin** [comment]
@mdstaff Here's example of how flags could be typed and used:

```typescript
import { Command, flags as Flags } from '@oclif/command';

export interface BuildCommandFlags {
  production?: boolean;
}

export default class BuildCommand extends Command {

  public static flags: Flags.Input<BuildCommandFlags> = {
    production: Flags.boolean({
      description: 'production mode',
      default: false,
    }),
  };

  public async run() {
    const { flags } = this.parse(BuildCommand);
    const { production } = flags;
  }

}
```

**Comment by mdstaff** [comment]
Thanks @slavafomin I'll give that a shot, sorry about the duplicates, github was having some issues 😅 as I submitted my comment the first time 🤦

**Comment by mdstaff** [comment]
Hi @slavafomin it looks like that suggestion worked!  It solved my original problem though it created another warning 🤔 

```
type BrowserType = "safari"
  | "firefox"
  | "chrome"
  | "edge"
  | "ie"
  | undefined;

interface MyCommandFlags {
  browser: BrowserType;
  device: PlatformTypes;
  help?: void;
}

const browserOptions: BrowserType[] = [
  "safari",
  "firefox",
  "chrome",
  "edge",
  "ie"
];

const browser = Flags.string({
  description: 'choose from a list of browsers',
  options: browserOptions, // TODO @ts-ignore errors below
  required: true
})();


export default class Screenshots extends Command {
  static flags: Flags.Input<MyCommandFlags> = {
    help: Flags.help({ char: 'h' }),
    browser,
  }
  ...
  async run() {
    const { flags } = this.parse(Screenshots)

    const {browser, device} = flags
    // console.log('Flags', flags)
    console.log('Url & Args', url, args)

    const options = BrowserFlags[browser];
  }
}
```

I also had to add "undefined" to type BrowserType.  
I now get the following error messages when I hover over the "options" property 
```
No overload matches this call.
  Overload 1 of 3, '(options: { multiple: true; } & Partial<IOptionFlag<string[]>>): IOptionFlag<string[]>', gave the following error.
    Type 'PlatformType[]' is not assignable to type 'string[]'.
      Type 'PlatformType' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 3, '(options: ({ required: true; } & Partial<IOptionFlag<string>>) | ({ default: Default<string>; } & Partial<IOptionFlag<string>>)): IOptionFlag<...>', gave the following error.
    Type 'PlatformType[]' is not assignable to type 'string[]'.
  Overload 3 of 3, '(options?: Partial<IOptionFlag<string>> | undefined): IOptionFlag<string | undefined>', gave the following error.
    Type 'PlatformType[]' is not assignable to type 'string[]'.ts(2769)
flags.d.ts(38, 5): The expected type comes from property 'options' which is declared here on type '{ multiple: true; } & Partial<IOptionFlag<string[]>>'
flags.d.ts(38, 5): The expected type comes from property 'options' which is declared here on type '({ required: true; } & Partial<IOptionFlag<string>>) | ({ default: Default<string>; } & Partial<IOptionFlag<string>>)'
```
A step in the right direction but still a bit confused by some of the TypeScript feedback from the compiler 🤔

**Comment by slavafomin** [comment]
@mdstaff

I think the error is pretty self-explanatory. `browser` is a `BrowserType`, which could be `undefined`. And you are trying to use possibly undefined value as a key to `BrowserFlags` record.

As well as I'm glad to answer your typing related questions, it has nothing to do with the issue at hand, so I would suggest to avoid further off-topic messages :)
Please, contact me directly if you have further questions.

**Comment by RasPhilCo** [comment]
Is this still an issue with updated oclif packages? If so, please provide reproduction steps, thanks!

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
