### ISSUE TITLE
Multi-command CLI can't start without compiling the code ("commands": "./lib/commands" || "commands": "./src/commands")

### ISSUE THREAD

**Issue by prokopsimek** [oclif/oclif#320]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
- a feature probably?

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
- clone https://github.com/oclif/example-multi-ts
- add command `"start": "./bin/run"` to `package.json`
- run `yarn start` or `npm start`
- oclif cannot load commands because it tries to load it from `/lib/commands` instead of `/src/commands`

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.
- I should be able to run `yarn start` without the need to build the code.

```
    "@oclif/command": "1.5.19",
    "@oclif/config": "1.13.3",
    "@oclif/plugin-help": "2.2.3",
```
```
MacBook Pro (Retina, 13-inch, Early 2015); MacOS Catalina Version 10.15 Beta (19A582a)
darwin-x64 node-v12.13.0
```

Proposals
------------------------------
1) have a possibility to configure oclif commands root programmatically directly in `./bin/run` or `src/index.ts` instead of `package.json`. The best would be to have a "root command" class where I can import other commands as an array of classes.

**Comment by RasPhilCo** [comment]
I had no issues following your steps (was unable to reproduce your bug). If this is still an issue for you, reopen. Thanks!

**Comment by mshwery** [comment]
I'm seeing this same issue when adding to an existing project.

Node 12.18
```
    "@oclif/command": "^1.8.0"
    "@oclif/config": "^1"
    "@oclif/plugin-help": "^3.2.2"
    "@oclif/dev-cli": "^1.26.0"
    "ts-node": "^9.1.1",
```

The manifest file references `/lib/commands` instead of `/src/commands`
