### ISSUE TITLE
feat ( eslint ) : Update on eslint-plugin-oclif

### ISSUE THREAD

**Issue by aggmoulik** [oclif/oclif#322]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
No

What is the current behavior?
-----------------------------
I have created some basic rules while in Google Summer of Code Time Period and I want to continue my work on that and I want to know when and how it will be implemented in the oclif project. @RasPhilCo 

If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

**Comment by RasPhilCo** [comment]
_If this response solved your issue, please let us know and close out the issue. Thanks!_
