### ISSUE TITLE
conditional dependsOn

### ISSUE THREAD

**Issue by cyrfer** [oclif/oclif#323]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
only statically defined dependencies are supported

What is the expected behavior?
------------------------------
Developers need to be able to define a function that has rules about when other fields are required.

For example, if making a HTTP client like curl, you would define flags for 'method' and 'data' (body). The data field is required ONLY WHEN method=POST.

I propose the "dependsOn" flag property be an object rather than an array, where the keys are the names of other fields required, and the values are `true` or a async function that is passed the complete command context and must return a bool.

Please mention your oclif and OS version.
------------------------------
`@oclif/command": "^1.5.19`

**Comment by jonaslagoni** [comment]
I just encountered the same kind of use case, would love to see this feature.
