### ISSUE TITLE
Cannot pass "-" as argument without "--"

### ISSUE THREAD

**Issue by G-Rath** [oclif/oclif#324]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

This is a bug.

```
import { Command } from '@oclif/command';
import * as Parser from '@oclif/parser';

export default class Format extends Command {
  public static description = 'Formats the given input';

  public static args: Parser.args.IArg[] = [
    { name: 'target', required: false } //
  ];

  public async run(): Promise<void> {
    const {
      args: { target }
    } = this.parse(Format);

    console.log(target);
  }
}
```

What is the current behavior?
-----------------------------

Currently in the above command, `-` will only be accepted as an argument value if it comes after `--`:

![image](https://user-images.githubusercontent.com/3151613/74122607-b199a880-4c30-11ea-911e-524f02753e50.png)

(`cli` is just `"cli": "node -r tsconfig-paths/register bin/terraport"` which is the [project](https://github.com/G-Rath/terraport))

What is the expected behavior?
------------------------------

I would expect `-` to be parsed; it's a common shell convention to use `-` to represent the current input.

Versions:

```
    "@oclif/command": "^1.5.19",
    "@oclif/config": "^1.14.0",
    "@oclif/errors": "^1.2.2",
    "@oclif/plugin-autocomplete": "^0.1.5",
    "@oclif/plugin-help": "^2.2.3",
```

Windows 10, WSL (Ubuntu 18.04), Node v12.14.1, npm v6.13.7

**Comment by chapmanjacobd** [comment]
cool! I just noticed this too. this should fix

```
echo smith | ./bin/run hello -n -
```

right? or will that need to be handled separately ?
