### ISSUE TITLE
Inject result of hooks inside Command

### ISSUE THREAD

**Issue by b4nst** [oclif/oclif#325]
What's the best way to inject data computed in a pre-run hook to the followed Command ?

Let's take this simple example : I want to do a HTTP GET and use the JSON body inside my command.

Currently either I build a Base Command which make the call and initialize the variable inside the init function, or I write a hook that set a global variable.

Is there a way to inject this data directly from the hook to the Command ?

**Comment by franzarmas** [comment]
Friend, did you find any way to get it?

**Comment by b4nst** [comment]
No more than what I was doing as a workaround (Base Command or global var)

**Comment by RasPhilCo** [comment]
I'd go with the base class approach, see the `init` function: https://oclif.io/docs/base_class.

To your question, we do nothing with a returned value from hooks.

_If this response solved your issue, please let us know and close out the issue. Thanks!_
