### ISSUE TITLE
Question on structuring top level command with subcommands

### ISSUE THREAD

**Issue by scalvert** [oclif/oclif#330]
Question on command structure.

I have a CLI where I want to have a top-level command (single command) and additional subcommands.

Example:

Executes the `foo` command with a path argument
```
$ foo .
```

Executes a subcommand to generate a config
```
$ foo config:create
```

How would I set this up? It seems that if I use multi-command, I have to have a subcommand name or topic/subcommand for the bare invocation of `foo .`.

**Comment by RasPhilCo** [comment]
You can now add a "root" command by defining a command at `src/commands/index.ts`. See https://github.com/oclif/oclif/issues/277#issuecomment-668271675

_If this response solved your issue, please let us know and close out the issue. Thanks!_
