### ISSUE TITLE
[Question] Oclif dynamic autocomplete with http call

### ISSUE THREAD

**Issue by eduardnegru** [oclif/oclif#332]
Question
-----------------------------------------------------
Does Oclif support making a call to an API and getting the values returned in order to be used for autocomplete? I have the following use case:

- Multiple users are stored in a database

- When the user presses show users <Tab> <Tab>, the CLI should make a call to an API that returns all available users.

- The CLI should use the values returned from the API.

- The user can then select a user name, for example show users user0001.

Is this possible in Oclif?

**Comment by RasPhilCo** [comment]
It is not possible in oclif, however the Heroku CLI does this. Check out https://github.com/heroku/cli/tree/master/packages/autocomplete.
