### ISSUE TITLE
oclif-dev manifest command is executing source code.

### ISSUE THREAD

**Issue by rockmandash** [oclif/oclif#336]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

I think it's a bug or confusing behavior.

What is the current behavior?
-----------------------------

`oclif-dev manifest` will execute your source code.

What is the expected behavior?
------------------------------

My oclif is latest.

1. run `npx oclif multi mynewcli`
2. create an `index.ts` file under root folder `src/app/index.ts`
3. you put `console.log("test...");` inside the `index.ts` file
4. import the file in your `src/commands/hello.ts`

```diff
import { Command } from "@oclif/command";
import * as fs from "fs-extra";
+ import "../app/index";

export default class extends Command {
  async run() {
  }
}
```
5. Now you run `yarn run prepack`, terminal shows

```bash
mynewcli % yarn run prepack
yarn run v1.22.4
$ rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme
test...
```

I thought oclif will only transpile your source code, turns out it executes it, that's quite strange when you're building an npm library.

The current solution is write everything inside a function.

**Comment by RasPhilCo** [comment]
Good to point out! Though I'll skip calling it a bug for now, unless you want to document an adverse effect.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!

**Comment by LassiterJ** [comment]
> Good to point out! Though I'll skip calling it a bug for now, unless you want to document an adverse effect.

Please document this! I have spent hours trying to figure out the ["root index"](https://oclif.io/blog/#feature-root-index-command) command, which could also use an example in the docs, and was confused when a console.log was firing from a command with only the bin name keyword.

**Comment by kon14** [comment]
> I'll skip calling it a bug for now, unless you want to document an adverse effect.

Having `oclif manifest` execute code is unexpected and troublesome for anyone writing code or depending on libraries that:
a) commonly use patterns such as instantiating a class and exporting an initialized object
b) initialize static class fields using constructors

I came upon this while attempting to start a daemon if not already running, resulting in my startup checks running during my building stage.
I worked around this on my end with a couple pointless refactors, but ideally that shouldn't be required.

Please consider reopening this issue.
