### ISSUE TITLE
Types of flags 

### ISSUE THREAD

**Issue by pavelloz** [oclif/oclif#338]
Hello,

Thank you for the best (IMO) tool for creating CLIs in node.

Im trying to master oclif completely before i migrate my company main CLI to oclif, but i think docs are neglected when it comes to discoverability.

By guessing i found out that there is `flag.integer` that i can use even though there is nothing about it in the docs ( https://oclif.io/docs/flags ) and this got me thinking, how many other types (or even completely different features) im missing (hence: writing sub-optimal code).

It would be nice to at least list with whats out there (increases discoverability), that would allow people to use it/experiment and contribute back by documenting it in a more detailed way.

Example: I have an int flag, and i suspect that there is an option to make it max/min, but its nowhere to be found in docs, so ill probably make some ugly hack to achieve that.

Best,
Pawel

**Comment by svrooij** [comment]
@pavelloz Did you know you can use `F12` (or right click, go to definition) in VSCode while your mouse is at `flags` in `import Command, {flags} from '@oclif/command'` to see the definition? That doesn't document it, but at least gives you an overview of what is available.

So to my initial findings you can use:

- `string`
- `enum`
- `boolean`
- `integer`
- `version`
- `help`

```typescript
export declare function build<T>(defaults: {
    parse: IOptionFlag<T>['parse'];
} & Partial<IOptionFlag<T>>): Definition<T>;
export declare function build(defaults: Partial<IOptionFlag<string>>): Definition<string>;
export declare function option<T>(options: {
    parse: IOptionFlag<T>['parse'];
} & Partial<IOptionFlag<T>>): IOptionFlag<T | undefined>;
declare const _enum: <T = string>(opts: Parser.flags.EnumFlagOptions<T>) => IOptionFlag<T>;
export { _enum as enum };
declare const stringFlag: Definition<string>;
export { stringFlag as string };
export { boolean, integer } from '@oclif/parser/lib/flags';
export declare const version: (opts?: Partial<Parser.flags.IBooleanFlag<boolean>>) => Parser.flags.IBooleanFlag<void>;
export declare const help: (opts?: Partial<Parser.flags.IBooleanFlag<boolean>>) => Parser.flags.IBooleanFlag<void>;
```

**Comment by RasPhilCo** [comment]
While we'd love to have perfect docs - there's always room for improvement - we opted for Typescript partially for this reason.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
