### ISSUE TITLE
How to pass not known number of arguments to command ?

### ISSUE THREAD

**Issue by marckraw** [oclif/oclif#341]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
feature

What is the current behavior?
-----------------------------
I think we need to know how many and what arguments we can pass to command, we cant say we want to have not known numbers of string arguments.

What is the expected behavior?
------------------------------
i would like to pass not known amount of string arguments to command like that:
`cli-app command argument1 argument2 argument3 ....argumentN`

**Comment by marckraw** [comment]
I think i've found out how to do that, well to my usecase, 
Had to use:
```
static strict = false;  
```
(https://oclif.io/docs/args)
and then 
```
 const { args, argv, flags } = this.parse(Backup);
```

just use `argv` to pick up arguments.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
