### ISSUE TITLE
`oclif-typescript` shouldn't require types in JSDoc

### ISSUE THREAD

**Issue by ozum** [oclif/oclif#346]
Hi,

When using TypeScript with TypeDoc `valid-jsdoc` eslint rule requires explicit types for parameters and return types. However TypeDoc infers types from TypeScript and defining types with JSDoc is redundant.

What is the current behavior?
-----------------------------
`oclif-typescript` warns when paremeter or return type is missing.

What is the expected behavior?
------------------------------
`oclif-typescript` should implement rule below:

`"valid-jsdoc": ["warn", { "requireReturnType": false, "requireParamType": false }]`

```ts
/**
 * Some description
 *
 * @param cmd is some string.
 * @returns some string.
 */
export default function command(cmd: string): string {
  return cmd
}
```

**Comment by RasPhilCo** [comment]
Makes sense, a PR to the repo would be great!

**Comment by ozum** [comment]
I added as PR [here](https://github.com/oclif/eslint-config-oclif-typescript/pull/2)

**Comment by RasPhilCo** [comment]
closed via https://github.com/oclif/eslint-config-oclif-typescript/pull/2
