### ISSUE TITLE
Cannot install `.deb` package: "The repository '/apt ./ Release' does not have a Release file."

### ISSUE THREAD

**Issue by busticated** [oclif/oclif#347]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

bug

What is the current behavior?
-----------------------------

1. using an otherwise working oclif cli codebase...
2. produce a `deb` package via `oclif-dev pack:deb`
3. publish your `deb` package via `oclif-dev publish:deb`
4. attempt to install using the instructions provided here: https://oclif.io/docs/releasing#ubuntudebian-packages - specifically:

```
$ wget -qO- https://mys3bucket.s3.amazonaws.com/apt/release.key | apt-key add - # you will need to upload this file manually
$ sudo echo "deb https://mys3bucket.s3.amazonaws.com/apt ./" > /etc/apt/sources.list.d/mycli.list
$ sudo apt update
$ sudo apt install -y mycli
```

...where `mys3bucket` and `mycli` is replaced w/ the appropriate values

What is the expected behavior?
------------------------------

i'd expect the `deb` package to be installed but instead i get:

```
Ign:8 https://o1010000.s3.amazonaws.com/apt ./ InRelease                                                                   
Err:9 https://o1010000.s3.amazonaws.com/apt ./ Release                                                                 
  404  Not Found [IP: 52.217.13.12 443]
...
Reading package lists... Done                                               
E: The repository 'https://o1010000.s3.amazonaws.com/apt ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

using:
`@oclif/dev-cli/1.22.2 linux-x64 node-v12.16.2`
`Ubuntu 18.04.4 LTS`

when i compare to heroku's `deb` setup ([1](https://devcenter.heroku.com/articles/heroku-cli#ubuntu-debian-apt-get), [2](https://cli-assets.heroku.com/install-ubuntu.sh), [3](https://cli-assets.heroku.com/apt/Release), [4](https://cli-assets.heroku.com/apt/Packages.gz)), i appear to be matching every setting. if fact, if you replace `o1010000.s3.amazonaws.com` with `cli-assets.heroku.com` in any of these operations and compare output, you'll see they are the essentially the same. 

when i attempt to debug `apt` using `apt -oDebug::Acquire::https=1 update`, i see logs like:

```
0% [2 InRelease gpgv 2,879 B] [Waiting for headers] [Connected to o1010000.s3.amazonaws.com (52.216.113.3)]GET /apt/./InRelease HTTP/1.1
Host: o1010000.s3.amazonaws.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.6.12ubuntu0.1)


0% [5 InRelease gpgv 88.7 kB] [Waiting for headers]Answer for: https://o1010000.s3.amazonaws.com/apt/./InRelease
HTTP/1.1 404 Not Found
x-amz-request-id: 6271BA244D45EC97
x-amz-id-2: cXtkeT0H9bfEpiHUH9x4Mt/m8SPIRaxeTicqTJcyYQ/qX188b2Iuj/5rBe6j5L3tdHYboxyw1cg=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Fri, 15 May 2020 22:46:43 GMT
Server: AmazonS3

Ign:9 https://o1010000.s3.amazonaws.com/apt ./ InRelease
0% [5 InRelease gpgv 88.7 kB]GET /apt/./Release HTTP/1.1
Host: o1010000.s3.amazonaws.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.6.12ubuntu0.1)


0% [6 InRelease gpgv 242 kB] [Waiting for headers]Answer for: https://o1010000.s3.amazonaws.com/apt/./Release
HTTP/1.1 404 Not Found
x-amz-request-id: 7E805637B0F97F11
x-amz-id-2: eO8mj3kkfheDghM4NtoaHUXPlyVHk6sNJyVLSn6les6HxL42fCb2JZLMxT23QUPRabSg5WG+URc=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Fri, 15 May 2020 22:46:43 GMT
Server: AmazonS3

Err:10 https://o1010000.s3.amazonaws.com/apt ./ Release
  404  Not Found [IP: 52.216.113.3 443]
Reading package lists... Done                     
E: The repository 'https://o1010000.s3.amazonaws.com/apt ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

...but when i `curl` the supposedly 404'ing url, i get:

```
curl -I https://o1010000.s3.amazonaws.com/apt/./Release
HTTP/1.1 200 OK
x-amz-id-2: qJZfTQzlQeOv35UmafjKSCXaEYiLvPgypT+jnylDkne/oUS9I/iU83TXI3URmbDcoMN1U4iW2mA=
x-amz-request-id: CC2C006F8DB2F034
Date: Fri, 15 May 2020 22:50:24 GMT
Last-Modified: Fri, 15 May 2020 22:32:50 GMT
ETag: "21087a5dd9b6d33bd37eb23267844131"
Cache-Control: max-age=86400
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 2031
Server: AmazonS3
```

which is to say, it works. 

if i edit the `/etc/apt/sources.list.d/o1010000.list` file to be:

```
deb https://o1010000.s3.amazonaws.com/apt /
```

...running `apt update` using that configuration then yields:

```
Answer for: https://o1010000.s3.amazonaws.com/apt/InRelease
HTTP/1.1 200 OK
x-amz-id-2: 3JLIgbA8CJmkXg/pBUchxqkpt+W6TyXSsqPQJmfgYX3ufrSdMJ8Yu7ZnrCdN1Ssj87wCMZ/3s78=
x-amz-request-id: DDC885BAEB31340A
Date: Fri, 15 May 2020 22:54:26 GMT
Last-Modified: Fri, 15 May 2020 22:32:50 GMT
ETag: "66d999872443e67dfa63761afd8ae8c5"
Cache-Control: max-age=86400
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 2739
Server: AmazonS3

Get:9 https://o1010000.s3.amazonaws.com/apt  InRelease [2,739 B]
85% [Working]GET /apt/Packages.xz HTTP/1.1                      
Host: o1010000.s3.amazonaws.com
Cache-Control: max-age=0
User-Agent: Debian APT-HTTP/1.3 (1.6.12ubuntu0.1)


Answer for: https://o1010000.s3.amazonaws.com/apt/Packages.xz
HTTP/1.1 200 OK
x-amz-id-2: dFgz2EgThxagiU6uCA2nnm0qbMhE9F9Ow/x1tzd7+ddbmS3VZRpO4RlC/nONHol7JG83RaRsvJA=
x-amz-request-id: 61C6C4AC08D7EBC3
Date: Fri, 15 May 2020 22:54:26 GMT
Last-Modified: Fri, 15 May 2020 22:32:49 GMT
ETag: "4259cc773e5fc0e0dccb5dc1726b5a07"
Cache-Control: max-age=86400
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 624
Server: AmazonS3
```

...which is to say, it works. but note how urls are formatted (`https://o1010000.s3.amazonaws.com/apt/InRelease` vs. `https://o1010000.s3.amazonaws.com/apt/./InRelease`).

however, installation fails with:

```
root@nuc-ubuntu:~# apt install o1010000
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  o1010000
0 upgraded, 1 newly installed, 0 to remove and 26 not upgraded.
Need to get 12.9 MB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://o1010000.s3.amazonaws.com/apt  o1010000 1.0.0-1
  404  Not Found [IP: 52.216.179.163 443]
E: Failed to fetch https://o1010000.s3.amazonaws.com/apt/./o1010000_1.0.0-1_amd64.deb  404  Not Found [IP: 52.216.179.163 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

..once again, `curl` confirms the file is available:

```
curl -I https://o1010000.s3.amazonaws.com/apt/./o1010000_1.0.0-1_amd64.deb
HTTP/1.1 200 OK
x-amz-id-2: snm7mCB9t+HRKaKPNqAWACqsOAv5EDwYXXeyjf2eZlgCmB2n4gyRzXgmRgKEgw9FxX44LS1E65E=
x-amz-request-id: 14806899BB2324C9
Date: Fri, 15 May 2020 23:04:29 GMT
Last-Modified: Fri, 15 May 2020 22:32:47 GMT
ETag: "acdf44f98e5eae54f1ae8b519260ab6e-3"
Cache-Control: max-age=86400
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 12874576
Server: AmazonS3
```

...so at this point, i'm thoroughly stumped. perhaps bins can't use 0-9?? 🤷‍♂️

**Comment by busticated** [comment]
update: i just re-ran the `oclif-dev pack:deb` and `oclif-dev publish:deb` steps after deleting all files from `https://o1010000.s3.amazonaws.com/apt/` and now it seems `InRelease` is no longer being generated..?

**Comment by busticated** [comment]
i figured it out. `curl` was automatically "fixing" the url before trying it so it appeared to work. adding the `--path-as-is` flag revealed the 404:

```
curl -I -L --path-as-is "https://o1010000.s3.amazonaws.com/apt/./InRelease"
```

to get the default configuration working, you'll need to tweak your s3 bucket redirect rules:

<img width="556" alt="oclif apt package s3 redirect rules" src="https://user-images.githubusercontent.com/367674/82236291-bda89c80-98e8-11ea-907c-89f6a72bb15f.png">

with that in place and using the new endpoint, things work as expected:

```
curl -I -L --path-as-is "http://o1010000.s3-website-us-east-1.amazonaws.com/apt/./InRelease"
```

i'm not sure how well this solution scales to other channels, etc. i'm also not clear on why oclif wants to use `./` as the "distribution" ([docs](https://wiki.debian.org/SourcesList)). pointers / insights around those would be very much appreciated :pray:

in the meantime, i'll try to open a PR with docs updates later this week so others don't fall into this down the line.

**Comment by JamieCurnow** [comment]
For anyone in the meantime that needs the JSON redirect version:
```json
[
    {
        "Condition": {
            "KeyPrefixEquals": "apt/./"
        },
        "Redirect": {
            "ReplaceKeyPrefixWith": "apt/"
        }
    }
]
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
