### ISSUE TITLE
Error: Cannot find module `commands`

### ISSUE THREAD

**Issue by crimson-med** [oclif/oclif#349]
Report a *bug*?
-----------------------------------------------------

What is the current behavior?
-----------------------------
Published some updates on my package on npm and it is full broken.
Steps to reproduce:
- yarn global add vestigo
- vestigo scan --target="https://127.0.0.1/" --method="GET" -w

Results in:

```
Error: Cannot find module '/Users/xxx/.config/yarn/global/node_modules/vestigo/lib/commands/scan'
Require stack:
- /Users/xxx/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js
- /Users/xxx/.config/yarn/global/node_modules/@oclif/config/lib/config.js
- /Users/xxx/.config/yarn/global/node_modules/@oclif/config/lib/index.js
- /Users/xxx/.config/yarn/global/node_modules/@oclif/command/lib/command.js
- /Users/xxx/.config/yarn/global/node_modules/@oclif/command/lib/index.js
- /Users/xxx/.config/yarn/global/node_modules/vestigo/bin/run
    at fetch (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:166:31)
    at Plugin.findCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:184:21)
    at Object.load (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:113:72)
    at Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:170:27)
    at Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:22:27)
    at Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:43:31)
```

This does not happen with prior versions:

- yarn global add vestigo@0.0.5
- vestigo scan --target="https://127.0.0.1/" --method="GET"

This does not happen while debugging:

- bin/run scan --target="https://127.0.0.1/" --method="GET" --report="HTML" -w

no issues

What is the expected behavior?
------------------------------

The command line is supposed to run like in prior versions

package.json

```json
{
  "name": "vestigo",
  "description": "A tool for exploring and investigating APIs.",
  "version": "0.1.6",
  "author": "Mederic Burlet",
  "bin": {
    "vestigo": "./bin/run"
  },
  "bugs": "https://github.com/crimson-med/vestigo/issues",
  "dependencies": {
    "@oclif/command": "^1.6.1",
    "@oclif/config": "^1",
    "@oclif/plugin-help": "^2",
    "@types/chalk": "^2.2.0",
    "axios": "^0.19.2",
    "chalk": "^3.0.0",
    "crimson-progressbar": "^1.3.0",
    "tslib": "^1",
    "whois-json": "^2.0.4"
  },
  "devDependencies": {
    "@oclif/dev-cli": "^1",
    "@oclif/test": "^1",
    "@types/chai": "^4",
    "@types/mocha": "^5",
    "@types/node": "^10",
    "chai": "^4",
    "globby": "^10",
    "mocha": "^7.1.2",
    "nyc": "^14",
    "ts-node": "^8",
    "typescript": "^3.3"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "files": [
    "/bin",
    "/lib",
    "/npm-shrinkwrap.json",
    "/oclif.manifest.json"
  ],
  "homepage": "https://github.com/crimson-med/vestigo",
  "keywords": [
    "oclif"
  ],
  "license": "GNU GPLv3",
  "main": "lib/index.js",
  "oclif": {
    "commands": "./lib/commands",
    "bin": "vestigo",
    "plugins": [
      "@oclif/plugin-help"
    ]
  },
  "repository": "crimson-med/vestigo",
  "scripts": {
    "postpack": "rm -f oclif.manifest.json",
    "prepack": "rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme",
    "test": "nyc --extension .ts mocha --forbid-only \"test/**/*.test.ts\" --full-trace",
    "version": "oclif-dev readme && git add README.md"
  },
  "types": "lib/index.d.ts",
  "resolutions": {
    "whois-json/whois/optimist/minimist": "^1.2.5"
  }
}

```

**Comment by crimson-med** [comment]
Any ideas on what could be causing this issue?

**Comment by RasPhilCo** [comment]
Try installing with npm globally, yarn globally sometimes gets wonky.

**Comment by martinlarosa** [comment]
Same thing is happening to me, it was working fine and then newer versions stopped working with that error.
I'm not using yarn.

**Comment by martinlarosa** [comment]
It's not generating any output into the lib directory. I have 3 commands, referencing other files under src/ and under another directory inside src/
Then I modify the file of one of the commands (just removing a line break), do `npm pack` and that file gets to the lib directory and into the packagle. 
But then I run `npm pack` again withouit modifying any file and the lib is empty again

**Comment by martinlarosa** [comment]
Weird thing is that the readme.md file and the help result is updated correctly

**Comment by crimson-med** [comment]
Never been able to solve it personally I just have to run in dev mode. This really hinders my project so I'm thinking to find an alternative

**Comment by martinlarosa** [comment]
Found the problem @crimson-med !
There's a file in my directory called tsconfig.tsbuildinfo, that keeps a signature of the files. Clearly if the file didn't change then it doesn't compile it again.I don't know when or why that file appeared there, but deleting the file fixes the problem. 
The issue is that it appears again after packaging it again. So what I did was to add the removal of that file to the postpack script. Maybe it should go into the prepack? I'm not sure but this works for now.

Now my postpack looks like this :     "postpack": "rm -f oclif.manifest.json tsconfig.tsbuildinfo",

**Comment by crimson-med** [comment]
I tried that but it makes no difference for me @martinlarosa

**Comment by dmoosocool** [comment]
@martinlarosa   hi, thanks your idea. but this doesn't seem to work for me...

`"postpack": "rm -f oclif.manifest.json tsconfig.tsbuildinfo",` 

my `package.json` scripts:
```
  "scripts": {
    "postpack": "rm -f oclif.manifest.json tsconfig.tsbuildinfo",
    "posttest": "eslint . --ext .ts --config .eslintrc",
    "prepack": "rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme",
    "test": "nyc --extension .ts mocha --forbid-only \"test/**/*.test.ts\"",
    "version": "oclif-dev readme && git add README.md"
  },
```

this is  `yarn publish` log,  
```
yarn publish
yarn publish v1.22.4
[1/4] Bumping version...
info Current version: 0.0.9
question New version: 0.0.10
info New version: 0.0.10
$ oclif-dev readme && git add README.md
replacing <!-- usage --> in README.md
replacing <!-- commands --> in README.md
replacing <!-- toc --> in README.md
[2/4] Logging in...
[3/4] Publishing...
$ rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme
wrote manifest to /Users/xxxxxxxx/oclif.manifest.json
replacing <!-- usage --> in README.md
replacing <!-- commands --> in README.md
replacing <!-- toc --> in README.md
$ rm -f oclif.manifest.json tsconfig.tsbuildinfo
success Published.
[4/4] Revoking token...
info Not revoking login token, specified via config file.
✨  Done in 16.25s.
```

The log shows its execution order
1. run `version` script.
2. run `prepack` script.
3. run `postpack` script.

when executing `yarn publish`, the `tsconfig.tsbuildinfo` file may not be deleted when the `prepack` command was triggered.

so I try to delete the `tsconfig.tsbuildinfo` file in the `prepack` command.

here is updated `package.json` scripts: 
```
  "scripts": {
    "postpack": "rm -f oclif.manifest.json",
    "posttest": "eslint . --ext .ts --config .eslintrc",
    "prepack": "rm -rf lib tsconfig.tsbuildinfo && tsc -b && oclif-dev manifest && oclif-dev readme",
    "test": "nyc --extension .ts mocha --forbid-only \"test/**/*.test.ts\"",
    "version": "oclif-dev readme && git add README.md"
  },
```

its works for me..

@crimson-med If you are in the same situation as me, you can also try.

**Comment by martinlarosa** [comment]
Yeah, that's why I mentioned this probably belongs into the prepack. Postpack fix only works if you delete the file manually the first time.

**Comment by bumbummen99** [comment]
This occurred to me on a new, generated project. I use `npx oclif pack:tarballs` and those did not work. I figured out that it does work however after i run `npm i` in the extracted tarball, the issue was that my dependencies/devDependencies were not set correctly and quite everything was missing from the runtime dependencies. Correcting this did solve the issue.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
