### ISSUE TITLE
lodash low severity vulnerabilities

### ISSUE THREAD

**Issue by gkpty** [oclif/oclif#386]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Low severity vulnerability associated to lodash versions <4.17.12

What is the expected behavior?
------------------------------
no vulnerabilities affecting oclif

Oclif version 1.16.1

**Comment by RasPhilCo** [comment]
We have dependabot on all repos so they should all be bumped soon
