### ISSUE TITLE
When to create classes for dependency injection

### ISSUE THREAD

**Issue by Junkern** [oclif/oclif#41]
I started using oclif today and I really like it!

In my commands I use several other service classes (for talking to 3-rd party providers). I want to initialize those classes at one single point of entry. I tried doing that in the `index.ts` but it never gets called. 

What am I missing here? Can I use the mentioned `hooks`. If yes, where can I find the documentation?

Or do you handle such things with a `Command Base Class`?

**Comment by jdxcode** [comment]
by design we do not call any files so we only load the files we need. In a large project, it might take several seconds to create everything.

It sounds like you want an init hook. We should have some docs and a generator for that soon, but for now here is what you need to do:

First add a line like this to declare the hook: https://github.com/heroku/cli/blob/oclif/package.json#L56

(You will want init probably for your usage though, prerun happens later)

Then create a hook file like this: https://github.com/heroku/cli/blob/oclif/src/hooks/prerun/analytics.ts

You can also create your own hooks

**Comment by jdxcode** [comment]
reading it again though, I would definitely use a base class here. Unfortunately I don't have a great example, but I would do something like this:

```js
class MyBaseClass extends Command
  myApiClient = new ApiClient()
end
```

**Comment by jdxcode** [comment]
A third idea:

```js
class MyBaseClass extends Command {
  static apiClient = ApiClient
  myApiClient = new MyBaseClass.apiClient()
}
```

and in the test:

```js
beforeEach(() => {
  MyBaseClass.apiClient = MockApiClient
})
```

Hopefully one of these ideas is helpful. Let me know if you have any ideas how else this might be done!

**Comment by Junkern** [comment]
Thanks for the quick feedback!

I indeed went for the base class scenario. But instead of doing that with `static`, I simply but the initialization of the classes I need in all commands into the `init()` function. It worked, but I don't know  if there are any downsides^^ Just tested it out with `static` and that works as well.

**Comment by jdxcode** [comment]
so long as you don't need to modify the static property in the test then doing it as an instance property should be fine. The advantage of static is you have access to it in the test if you want to modify it, but if you don't need to make any modifications then instance is fine.

**Comment by Junkern** [comment]
That makes totally sense! Thanks a lot:)

**Comment by nsamsami** [comment]
@Junkern I'm a product manager at Heroku where we've been developing oclif. As we're just getting started with the project, I'd be really interested in your feedback and learning more about your use case. Feel free to respond here or drop us a note at heroku-cli-squad@salesforce.com

**Comment by bcomnes** [comment]
These are great examples / ideas.  They should probably be added to https://oclif.io/docs/base_class.html as I had to use github search to find them.  

Is that site open source / taking contributions?
