### ISSUE TITLE
eslint: 'flags' is already declared in the upper scope. (no-shadow)

### ISSUE THREAD

**Issue by bitjson** [oclif/oclif#418]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
Currently, there's a naming overlap in two APIs: the `Command` class requires a static `flags` property, and the result of `this.parse(MyCommand)` also includes a `flags` property. This means that even [the default command example](https://github.com/oclif/oclif/blob/2e3f0956f045b63703a1a05a5e4e3a4044726d55/templates/src/command.ts.ejs#L34) triggers a lint warning since `flags` is being overridden in the lower scope. 

```ts
static flags = [];

...
async run() {
    const { flags } = this.parse(MyCommand);
    //      ^------- 'flags' is already declared in the upper scope. eslint(no-shadow)
    if (args.file && flag.force) {
      this.log(`you input --force and --file: ${args.file}`)
    }
}
```

(With Eslint, the [no-shadow rule](https://eslint.org/docs/rules/no-shadow) is triggered.)

Currently the best we can do is a re-naming destructure:
```ts
const { args, flags: flag } = this.parse(MyCommand);
```
But this syntax can be confusing (verbose + hard to recall), especially for new contributors.

What is the expected behavior?
------------------------------
Could we modify this API to allow for some usage which doesn't trigger a warning? (And also doesn't encourage projects to disable the `no-shadow` rule?)

One backwards-compatible option: could we add a new `flag` property to the result of `this.parse` which references the same object referenced by the `flags` property? This change can be ignored by existing applications, but would allow applications with stricter lint settings to "upgrade" from the `flags` to the `flag` property.

 so the recommended usage would become:

```ts
    const { args, flag } = this.parse(MyCommand);
    if (args.file && flag.force) {
      this.log(`you input --force and --file: ${args.file}`)
    }
```

**Comment by RasPhilCo** [comment]
I'm not getting a lint error on a newly generated project & this shouldn't trigger a lint error either as the linter can decipher between static properties and in scope variables. Nonetheless, do you have reproduction steps for a deeper look?
