### ISSUE TITLE
Pretty Print for `this.log`

### ISSUE THREAD

**Issue by nahtnam** [oclif/oclif#419]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
So I noticed that with `this.warn` and `this.error`, there is a `>` that is inserted and the logs are indented. I was wondering if it was possible to do the same with `this.log`?

What is the expected behavior?
------------------------------
Show a green arrow

**Comment by RasPhilCo** [comment]
You can pass format args to `this.log`, see https://github.com/oclif/command/blob/44a9a7f8520fe7e080a28b61f7125b7aedd1a157/src/command.ts#L134 && https://millermedeiros.github.io/mdoc/examples/node_api/doc/util.html#util.format.

_If this response solved your issue, please let us know and close out the issue. Thanks!_
