### ISSUE TITLE
Support Command Aliases

### ISSUE THREAD

**Issue by WilliamHuey** [oclif/oclif#435]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
# Feature Request

It would be helpful if the oclif commands accepted command aliases such as a shorten version of the command name.

```bash
# Full command name
mycli build mystuff

# Alias version
mycli b mystuff
```

This request is a bit related to this pull request https://github.com/oclif/config/pull/139.

What is the current behavior?
-----------------------------
Command aliases not supported as there are no means of providing them.

What is the expected behavior?
------------------------------
Command aliases allow for custom abbreviated single letter command equivalents.

Specs: oclif/1.16.1 linux-x64 node-v14.11.0

**Comment by WilliamHuey** [comment]
I actually want something that is different from <a href="https://oclif.io/docs/aliases">https://oclif.io/docs/aliases</a> because the docs states that to create aliases for a base command, there would be additional appending to the command to create a new alias. The new alias will actually be longer than the base command which is the opposite effect of what I want.

**Comment by RasPhilCo** [comment]
By base command do you mean the root index command (as that is a special case)? For other commands, there's no appending, you can have a single-character alias.

_If this response solved your issue, please let us know and close out the issue. Thanks!_

**Comment by WilliamHuey** [comment]
Sorry, I have mixed up the terminologies. I want to have aliases for the arguments of the command.

Taking git for example

git is the command and the one argument for git might be 

```
git branch
```

Pretend that the alias for 'branch' in git exists:

```
git b
```

I want to be able to abbreviate the arguments as shown in the git example.

**Comment by RasPhilCo** [comment]
With a newly generated multi-cli:

```
// src/commands/hello.ts
import {Command, flags} from '@oclif/command'

export default class Hello extends Command {
  static aliases = ['h']
...
```

`$ ./bin/run hello`
`$ ./bin/run h`

**Comment by WilliamHuey** [comment]
@RasPhilCo, thanks for the example. :smiley:  It wasn't entirely evident to me in the documentation because the aliases shown were actually longer than the original arguments. I was thinking that the documentation could be updated to show the single letter usage for more clarity.
