### ISSUE TITLE
Readme not updating when prepack is run for Single CLI

### ISSUE THREAD

**Issue by tylerkilburn** [oclif/oclif#441]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Generate a new single cli with oclif.  Upon running prepack, the project is built, but the readme does not reflect description and examples in the index.ts file.  This seems to work with a multi cli.  FYI the Typescript option was used when generating a new project.

What is the expected behavior?
------------------------------
Expect oclif single api to auto generate readme on prepack.
Using OCLIF v1.16.1 on OSX 10.15.7

**Comment by tehkaiyu** [comment]
I'm running into the same issue

**Comment by RasPhilCo** [comment]
Running `oclif-dev readme` generates/updates the README. Ensure that command is run in your package.json scripts, likely in `prepack`.

If you're still having an issue, provide steps to reproduce this bug.

**Comment by therockstorm** [comment]
The repro steps are to just follow the [single command getting started guide](https://oclif.io/docs/single). Now open and look at the `README`, here's the generated portion,

```
<!-- toc -->
* [Usage](#usage)
* [Commands](#commands)
<!-- tocstop -->
# Usage
<!-- usage -->
```sh-session
$ npm install -g mynewcli
$ mynewcli COMMAND
running command...
$ mynewcli (-v|--version|version)
mynewcli/0.0.0 darwin-x64 node-v14.15.5
$ mynewcli --help [COMMAND]
USAGE
  $ mynewcli COMMAND
...
```

# Commands



```

It's not documenting the `name` or `force` flag. Running `./bin/run --help`, however, prints them,

```
❯ ./bin/run --help
describe the command here

USAGE
  $ mynewcli [FILE]

OPTIONS
  -f, --force
  -h, --help       show CLI help
  -n, --name=name  name to print
  -v, --version    show CLI version
```

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
