### ISSUE TITLE
Cannot invoke `/bin/run` when using baseUrl / path aliases in tsconfig.json

### ISSUE THREAD

**Issue by smcelhinney** [oclif/oclif#445]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
This is a bug. 

What is the current behavior?
-----------------------------

Possibly related to this issue https://github.com/oclif/oclif/issues/288, but invoking `/bin/run topic command` doesn't work when using aliased paths either. Eg.

**tsconfig.json**
```json
{
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true,
    "types": [
      "node"
    ],
    "paths": {
      "*": [
        "*",
        "src/*"
      ]
    },
    "esModuleInterop": true,
    "moduleResolution": "node",
    "baseUrl": "."
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*"
  ]
}
```
**topic.ts**
```typescript
// This should resolve, as `classes` exists inside `src`, as specified in tsconfig.json paths property. 
import ServerlessFunction from 'classes/cms/serverless'

// ...
  async run() {
    try {
      const { args, flags } = this.parse(CmsServerlessFunctionCreate);
      const serverlessFunction = new ServerlessFunction(args, flags);
      await serverlessFunction.createServerlessFunction();
      this.log(`New functions directory created at ${resolve(process.cwd(), `./${args.functionName}.functions`)}`)
    } catch (error) {
      console.error(error.message || error)
    }
  }
```
And when invoked using `./bin/run`

```shell
$ ./bin/run cms:serverless:create testing-test

(node:85813) [MODULE_NOT_FOUND] Error Plugin: <package-name>: Cannot find module 'classes/cms/serverless'
module: @oclif/config@1.17.0
task: toCached
plugin: <script-name>
root: /Development/projects/wttools
See more details with DEBUG=*
 ›   Error: command cms:serverless:create not found
```

What is the expected behavior?
------------------------------
I would expect that `./bin/run` would honour the `tsconfig.json` settings for baseUrl / paths when resolving modules in TypeScript.

Using `@oclif/command@1.8.0` and `@oclif/config@1.17.0`

**Comment by johnmcdowall** [comment]
Just ran into this myself, was very confusing. 

From what I can see, `oclif-config` is not looking at the `baseUrl`: https://github.com/oclif/config/blob/71fb6d9b98bff6c2ccee6961c8afa8403a8b1366/src/ts-node.ts#L111, and it probably should. 

Also something like `tsconfig-paths` probably needs to be included: https://github.com/oclif/dev-cli/issues/75#issuecomment-551338733 

This project kinda smells of corporate abandonware, so I'm actually going to rip out `oclif` and just do it all by hand, but maybe these notes will be useful to someone else.

**Comment by 0xBC84** [comment]
Any update on this? Facing this issue myself.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
