### ISSUE TITLE
generating manifest should fail loudly

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#46]
if building the manifest fails the CLI warns. This is fine for normal execution, but when creating the manifest with `oclif-dev manifest` it should exit with nonzero status. Warn is here: https://github.com/oclif/config/blob/master/src/plugin.ts#L195

**Comment by amphro** [comment]
The above PRs will now spit out an error instead. 

![image](https://user-images.githubusercontent.com/918434/37482945-1dcc7d5e-284b-11e8-9bad-78a647fa4c2d.png)
