### ISSUE TITLE
Question : How to make custom flags supporting other type than string ?

### ISSUE THREAD

**Issue by mJehanno** [oclif/oclif#462]
_Do you want to request a *feature* or report a *bug*?_
-----------------------------------------------------
Don't know if it's a bug or a feature request. Depends on what was the expected behaviour or my comprehension of the documentation.

_What is the current behavior?_
-----------------------------

When I create a custom flag like this : 

```javascript

import {flags} from '@oclif/command'

export const myFlag = flags.build({
   char: 'u',
   description: 'description of my flag',
   exclusive: ['my-other-flag'] // problem happens even if without this field
});
```
and use it in my command like this : 

```javascript
import Command, {flags} from '@oclif/command'

export class MyCommand extends Command {

    static flags = {
        myFlag = myFlag() // assuming I made the proper import to my custom flag
    }
    
    async run() {}

}
```
Then oclif assume that myFlag will be of string type. And I didn't find any way to tell oclif that my **custom flag** is a **boolean**.

I want to use the custom flag as it give me the possibility to re-use it in other commands but I need it to be a boolean.
Is it possible without using Command Class inheritance ? (as I need those flags only on 2 commands)

_What is the expected behavior?_

Behing able to tell explicitly the type of custom flags 
------------------------------
Windows 10, oclif 1.16.1

**Comment by scalvert** [comment]
I think you can just use

```
export const myFlag = flags.boolean({
  name: 'my-flag',
  description: 'description of my flag',
  exclusive: ['my-other-flag']
});
```

Will that not work for you?

**Comment by mJehanno** [comment]
Oh yeah it worked, I thought I had already tried that, I probably tried without removing parenthesis when calling the flag in the command ! Many thanks !
