### ISSUE TITLE
README not being updated

### ISSUE THREAD

**Issue by mellis481** [oclif/oclif#501]
I was running `npm run prepack` and noticed that the oflic documentation in the README has a ton of duplicate entries.  So removed all the oclif-related content from the README and I'm attempting to run `npm run version` again, but cannot get any oflic documentation in the README now.  I've also tried deleting the README and seeing if `npm run version` will create a new one with the expected documentation, but I get an error in that case saying there is no README.

**Comment by metasean** [comment]
related/dup of https://github.com/oclif/oclif/issues/429 ?

**Comment by metasean** [comment]
In the meantime, try running `oclif-dev readme` noting that you'll want the readme.md to have the following in it _prior_ to running that command:
```
<!-- toc -->
<!-- tocstop -->
# Usage
<!-- usage -->
<!-- usagestop -->
# Commands
<!-- commands -->
<!-- commandsstop -->
```
