### ISSUE TITLE
Native ES Module support for Oclif v2 w/ continued support of CommonJS

### ISSUE THREAD

**Issue by typhonrt** [oclif/oclif#521]
A pre-announcement edit: While I have initially prototyped ES Module support in Oclif v1 please refer to my modifications to the newly announced Oclif v2 which is where ESM support should be added. You can follow adding ESM to Oclif v2 in `@oclif/core`:
https://github.com/oclif/core/issues/130

I'm leaving this initial issue open for others to find easier, but closing the v1 pull requests. 

Original message:
----

Greets,

I have to say I have been enjoying working with Oclif. It is going to allow me to complete a complex CLI project soon. What would be even better is being able to work with ES Modules (ESM) for the core CLI and plugin development. I personally along with folks like [Sindre Sorhus](https://github.com/sindresorhus/meta/discussions/15) are moving to ESM for all new Node releases imminently. Tooling needs to play catchup, but I like Oclif so much I spent a full day updating Oclif to support ESM along with maintaining CommonJS support. With my [pull request](https://github.com/oclif/config/pull/223) it is possible to write core Oclif CLI code with ESM along with loading a mixture of ESM / CJS Oclif plugins. As noted at the bottom of the pull request I put up a separate Github repo w/ the compiled Typescript code that can be linked from Github to replace `@oclif/config` enabling ESM support now. 

I look forward to working on this pull request and getting things on the up and up for Oclif w/ ESM support. 

A few more details. My modification to @oclif/config handles plugin loading for commands and hooks. There also is loading a custom help class as an ES Module. I have modifications for @oclif/plugin-help & @oclif/command to support loading custom help classes, but due to the cyclic dependency between these modules I have not submitted PRs for them as tests would not pass in the GH Action due to the cyclic dependency even though all tests pass in the forks since I can update the dependencies locally. The remaining concern is @oclif/dev-cli which uses @oclif/plugin-help for the readme command. A quick update would be necessary there as well. Overall I do hope I can work with the project maintainers to bring native ES Module support to Oclif.

**Comment by justinfagnani** [comment]
It would be really great to get this in. I'm trying to write a CLI for a library that's published as JS modules and am hitting a wall because of require(). Thanks!

**Comment by typhonrt** [comment]
@justinfagnani Good news.. I have made several revisions and have things working with @oclif/core IE Oclif v2 which is coming out in a few months. Adding support there makes the most sense vs Oclif v1. I'll be publishing 3 comprehensive test suites this weekend regarding the end user experience & requirements / conditions for Node 12-15 compatibility that I believe really shows the viability. The @oclif/core v2 ESM support issue can be tracked here: 
https://github.com/oclif/core/issues/130

**Comment by typhonrt** [comment]
A final note more or less for now. I have laid out a very concrete case for adding ESM support to Oclif v2. Whether the Oclif team would like to engage an outside contributor on this matter is a bit less clear at this point. It is a core fundamental change to Oclif, but one that I believe is manageable to include responsibly without any loss of functionality to Oclif with much to gain before the v2 launch.  I do hope they consider that not adding ESM support to Oclif v2 may likely bring a significant pain point sooner rather than later during the v2 lifecycle as enough of the Node ecosystem will be rapidly switching to ESM with increasingly more in the coming year or so.

Once again track and follow the issue here:
https://github.com/oclif/core/issues/130

**Comment by typhonrt** [comment]
And exciting news... I was able to contribute significant changes to @oclif/core to support ES Modules. For v2 you can write pure ESM plugins via adding "type": "module" to package.json or mixed CJS / ESM plugins w/ *.cjs or *.mjs extensions for individual files. This will certainly help for anyone converting a CJS plugin to ESM or pulling in ESM packages to a CJS plugin.

You can see the history of the work here oclif/core#130

Thanks to the Oclif team for trusting me to commit these changes! Can close this issue now.. :D
