### ISSUE TITLE
aws cli style commands

### ISSUE THREAD

**Issue by kmalfroid** [oclif/oclif#540]
Does oclif support [aws cli](https://awscli.amazonaws.com/v2/documentation/api/latest/index.html) style command structures?

Example: `aws ec2 start-instances --instance-ids <value>`

At first sight, it seems that oclif does not support spaced subcommands (`aws ec2 start-instances`) or multiword parameters separated by a dash (`--instance-ids`)?

**Comment by mbtts-elsevier** [comment]
Greetings, I too am learning oclif.

> At first sight, it seems that oclif does not support spaced subcommands (aws ec2 start-instances) 

I believe the closest equivalent are “[Topics](https://oclif.io/docs/topics)”.
I appreciate not directly analogous, but it might be close enough for your use case..

> or multiword parameters separated by a dash (--instance-ids)?

These are definitely supported as “[Command Flags](https://oclif.io/docs/flags)“.

**Comment by mbtts** [comment]
Greetings, I too am learning oclif.

> At first sight, it seems that oclif does not support spaced subcommands (aws ec2 start-instances) 

I believe the closest equivalent are “[Topics](https://oclif.io/docs/topics)”.
I appreciate not directly analogous, but it might be close enough for your use case..

> or multiword parameters separated by a dash (--instance-ids)?

These are definitely supported as “[Command Flags](https://oclif.io/docs/flags)“.

**Comment by kmalfroid** [comment]
Thank you for your message!

Indeed, topics allow for subcommands. However, they must be separated by a colon : , not by a space. I realized that there already is an open issue about this from 2018: #186

After your confirmation that multiword parameters separated by a dash are supported, I dug a little deeper and figured out how to make it work:

``` typescript
static flags = {
  help: flags.help({char: 'h'}),
  'long-name': flags.string({char: 'n', description: 'long name to print'}),
}
async run() {
  const {flags} = this.parse(Hello)
  const ln = flags['long-name'] ?? 'mylongname'
  this.log(`hello ${ln}`)
}
```
