### ISSUE TITLE
Command options should also show up when using --help

### ISSUE THREAD

**Issue by Junkern** [oclif/oclif#55]
I have a command with the following args config:
```
static args = [{
      name: 'property',
      required: true,
      description: 'The value you want to change',
      options: [
        'FOOBAR',
        'STORE',
        'VALUE'
      ]
    }]
```

When executing that command in the cli with the `--help` flag, the description gets posted, but not the options. Only upon supplying a wrong value, the user gets information about what values he can provide.

I personally would expect the `--help` flag to output all necessary information about the command.

**Comment by jdxcode** [comment]
this is just missing. We need to the same thing we do here for args: https://github.com/oclif/plugin-help/blob/master/src/command.ts#L118

**Comment by Junkern** [comment]
I could provide a PR some point at the beginning of next week, as I need this feature

**Comment by veera83372** [comment]
Would mind If create a PR?

**Comment by sourabh1031** [comment]
i will work on this

**Comment by moulikcipherX** [comment]
I think this issue must be closed. @jdxcode

**Comment by jdxcode** [comment]
I don't think this is fixed yet

**Comment by sourabh1031** [comment]
@jdxcode please assign it to me

**Comment by jdxcode** [comment]
just go ahead and work on it if you like, there is no need for assigning

**Comment by janpio** [comment]
The options are indeed output when looking at the output of a command:

```
...

ARGUMENTS
  PLATFORM   (android|ios) [default: android] platform to build
  BUILDTYPE  (development|adhoc|appstore|enterprise) [default: development] what type of build to create

...
```

which was defined via

```
BuildCommand.args = [
  {
    name: 'platform',
    required: true,
    default: 'android',
    description: 'platform to build',
    options: ['android', 'ios'],
  },
  {
    name: 'buildType',
    required: false,
    default: 'development',
    description: 'what type of build to create',
    options: ['development', 'adhoc', 'appstore', 'enterprise'],
  }
[...]
```

**Comment by RasPhilCo** [comment]
Closed via https://github.com/oclif/plugin-help/pull/26

**Comment by dmatora** [comment]
What about description for options?
Is this currently doable?
