### ISSUE TITLE
Oclif v2

### ISSUE THREAD

**Issue by amphro** [oclif/oclif#563]
As we announced in this [March blog post](https://oclif.io/blog/2021/03/01/introducing-oclif-core), we’re working on v1 of the new [@oclif/core library](https://github.com/oclif/core), which we hope to release this summer. Part of that will be the next major version bump (v2) of the oclif CLI.

For more visibility, I want to highlight two quotes from that post:

> With the introduction of default command functionality, Core simplifies the oclif project and **removes the notion of single or multi command CLIs**. Core CLIs can have 1 or many commands. 

> At Core's v1 release, the current "main" oclif packages (namely: command, config, errors & parser) will go into maintenance mode until Jan 2022. They will receive only bug and security fixes and they remain compatible with current versions of the oclif and oclif-dev CLIs. Afterwhich, they will be archived.
> 
> Companioning Core, the **next major release of the oclif CLI (literally oclif@2) will generate Core CLIs**.

We will do our best to go through existing PRs and issues but most of our effort is going into the [remaining core work](https://github.com/oclif/core/issues/146). That issue also lists all the repositories that will be archived.

**Comment by typhonrt** [comment]
And exciting news... I was able to contribute significant changes to @oclif/core to support ES Modules. For v2 you can write pure ESM plugins via adding `"type": "module"` to package.json or mixed CJS / ESM plugins w/ `*.cjs` or `*.mjs` extensions for individual files. This will certainly help for anyone converting a CJS plugin to ESM or pulling in ESM packages to a CJS plugin.

You can see the history of the work here https://github.com/oclif/core/issues/130

Thanks to the Oclif team for trusting me to commit these changes!

**Comment by StringKe** [comment]
https://github.com/oclif/oclif/issues/605

support the `nx` project?
