### ISSUE TITLE
Calling out to a shell script

### ISSUE THREAD

**Issue by naseem-opal** [oclif/oclif#564]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Not a feature or a bug, but a question! Sorry if this is not an appropriate use of the issues page.

What is the current behavior?
-----------------------------
We've written a CLI in Typescript and are trying to have one of our commands in part run a bash file's worth of commands. While in development, the bash script is called as expected and the path provided to the script is correct. Once we package it, however, the bash script is not included so the command fails. How do you recommend packaging external non-TS files? I couldn't find this in the docs-- but am happy to be redirected to a page!

What is the expected behavior?
------------------------------
N/A

**Comment by RasPhilCo** [comment]
First thought, is the script listed in `files` in package.json?

**Comment by naseem-opal** [comment]
Thank you @RasPhilCo that fixed the issue :)

**Comment by quentint** [comment]
Hi there!

Is this `files` key is documented? I'm trying to use it but cannot find any details on it.  
Can you help? Thanks!
