### ISSUE TITLE
New multi-command cli creates invalid .eslintrc

### ISSUE THREAD

**Issue by jburnett** [oclif/oclif#567]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
To repro:

1. Use oclif to create new multi-command cli; accept all defaults
2. View generated .eslintrc 

Result: file contents are invalid (it seems to be a copy of .eslintingnore)

What is the expected behavior?
------------------------------
The .eslintrc file should be valid; single-command cli creates valid file

> $ oclif --version                                                                                                                                      ⬡ system 
oclif/1.17.0 linux-x64 node-v14.16.1

**Comment by Peter-Piper** [comment]
Previous comment has been moved to it's own ticket as I realised I did not experience the exact same issue as @jburnett 
See ticket #710

**Comment by mdonnalley** [comment]
Closing this since I can't reproduce it using latest - please feel to open a new issue if you're still seeing it. Thanks!
