### ISSUE TITLE
When using topics and multi-commands, the help output from `./bin/run` is not helpful.

### ISSUE THREAD

**Issue by Junkern** [oclif/oclif#57]
I have a `commands` folder which has two other folders `foo` and `bar`, which have some topics inside them. When running `./bin/run`, the output lists the two possible commands, but also their description. 

The thing is, when using topics I never define a description for the "top-level" command. But there is one anyway, and from what I observed it takes the first file from each commands folders and uses its description.

So, when having a `foobar` folder and inside the folder is a `define` command with description of `Defines a new value`, the output lists
```
Commands
foobar        Defines a new value
```

Which does not make sense, because running the `foobar` command itself is not possible (due to having topics), and the description is from another "topic-command"

I would like to be able to define a generic description for a top-level command.

**Comment by jdxcode** [comment]
you can do this by having an `oclif.topics.foobar.description` property set in the `package.json`. This should be documented more clearly
