### ISSUE TITLE
Architecture best practices

### ISSUE THREAD

**Issue by snowfrogdev** [oclif/oclif#573]
I find myself struggling with organizing my code using oclif. I usually favor composition over inheritance and constructor dependency injection heavily in my apps and oclif's architecture makes it very hard, perhaps impossible or impractical,  to do both. Where I would normally keep my classes small and create a tree of dependencies between them, I find myself writing long monstrosities several 100s of line long, because I can't find a nice way to extract classes from the Command classes.

Can anyone offer some guidance on how to do separation of concern, and apply the SOLID principles within oclif's architecture?

**Comment by Radiergummi** [comment]
I'm not sure whether I can hold up to that, but I personally extract most business logic in functions grouped in related modules, exported individually. This splits the code in smaller units, is easier testable, and forces me to avoid global state. Consider the following (simplified) `modules/api.ts`:

```ts
import got, { Got, Options } from 'got';
import { AuthStore } from './auth.ts';

export function createClient():  Got {
  return got.extend({
    /* ... */
  });
}

export function authenticatedClient( authStore: AuthStore ): Got {
  return createClient().extend({ headers: { Authorization: `Bearer ${authStore.token}` } })
}

export async function get<T>(authStore: AuthStore, uri: string, options?: Options): Promise<Response<T>> {
  const response = await authenticatedClient(authStore).get(uri, options);
  // ...
  return response;
}

export async function listRecords<T extends IEntity>(
  authStore: AuthStore,
  EntityCtor: EntityFactory<T>
): Promise<T[]> {
  const response = await get<JsonApiResponse<T[]>>(authStore, EntityCtor.uri)

  return response.data.map(item => new EntityCtor(item));
}

// ...
```

I subsequently use this module in derived base commands for CRUD operations:
```ts
import { listRecords } from '../modules/api.ts';

export abstract class ListCommand<T extends IEntity> extends Command {
  abstract protected function getEntity(): EntityCtor<T>;

  private function _resolveAuthStore(): AuthStore { /* ... */ }

  protected async function fetch(): Promise<T[]> {
    return listRecords(this_resolveAuthStore(), this.getEntity());
  }
}
```

...which is then used as the base for a, say, `ListUsers.ts` command:
```ts
import { User } from '../entities/User.ts';

export class ListUsers extends ListCommand<User> {
  async run(): Promise<void> {
    const records = await this.fetch();

    records.map(user => this.log(user.name));
  }
}
```

The `ListUsers` command is nice and clean, void of any implementation details and simple to reason about. I hope this helps a bit, but I'm happy to discuss this further :)

**Comment by aggmoulik** [comment]
[ESLint Plugin Oclif](https://github.com/oclif/eslint/issues), Hey Guys, I am looking for issues that most users does on a daily basis while building usinf oclif framework. It would be a great help, if you can create issues that we can overcome using static analysis. 

It is not maintained from a long time but I hope with the help of oclif community we can go ahead create better cli tools using Oclif.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
