### ISSUE TITLE
change config directory

### ISSUE THREAD

**Issue by engeman2008** [oclif/oclif#579]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug
What is the current behavior?
I want to change the cli config directory
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

"oclif": {
    "dirname": ".my-cli",
    "configDir": {
      "unix" : "~/.my-cli"
    },
    "commands": "./lib/commands",
    "bin": "my-cli",
    "plugins": [
      "@oclif/plugin-help",
      "conf-cli",
    ],
    "hooks": {
      "hypi-config": "./lib/hooks/custom/set-global-config"
    },
  },

What is the expected behavior?
I expect that the cli config directory is now ~/.my-cli not ~/.config/my-cli
------------------------------
    "@oclif/config": "^1.17.0",

**Comment by mdonnalley** [comment]
`configDir` isn't a valid configuration option but if you want to do this you need to set the `<CLI>_CONFIG_DIR` env var, otherwise, the config dir will always be placed under `~/.config`
