### ISSUE TITLE
How to import something before the app starts?

### ISSUE THREAD

**Issue by ajsaraujo** [oclif/oclif#603]
I want to use [tsyringe](https://www.npmjs.com/package/tsyringe), a dependency injection library. To use it, one must import the [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) polyfill once, before `tsyringe` is referenced. So far, so good. I tried importing it in `index.ts`:

```ts
import 'reflect-metadata'

export { run } from '@oclif/command'
```

But it didn't work. I got an error saying I didn't import reflect-metadata. So I tried doing this in the init hook:

```ts
import 'reflect-metadata'

export default function onInit() {
  // ...
}
```

But I got no success either. 

Then I tried adding it to the top of my first command (in alphabetical order):
```ts
import 'reflect-metadata'

export default class Config extends Command {
  // ...
}
```

And... it worked.

I guess the run scripts runs the command files first or something. Anyways, this is a quite hacky solution - I'd like to know if there's a more standardized way to do so.

**Comment by ajsaraujo** [comment]
Importing it in the base command works as well, but it doesn't feel like a very neat solution either.

**Comment by xlmnxp** [comment]
same issue for me, did you found solution?

**Comment by xlmnxp** [comment]
for me, I solve it by add 
```
require("reflect-metadata");
```

to `./bin/run` and `./bin/dev` after 
```
#!/usr/bin/env node
```

**Comment by mdonnalley** [comment]
Sounds like a solution has been reached. I'm going to close this issue - please feel free to open a discussion if there' more to discuss
