### ISSUE TITLE
[feature] Request support for nx monorepos

### ISSUE THREAD

**Issue by StringKe** [oclif/oclif#605]
https://nx.dev/ 

> Nx is a smart and extensible build framework that helps you develop, test, build, and scale Angular applications with fully integrated support for modern libraries like Jest, Cypress, ESLint, and more.

There are multiple `nestjs` applications in my `nx` project, I need to write some data processing commands for them, but `nx` does not support any cli framework, so can `oclif` support `nx`?

**Comment by aidanhasaknife** [comment]
Hey! If you're still looking for help, you may want to look [here](https://dev.to/digikare/oclif-on-nx-monorepo-33bo). It appears from the read that you may have to fuss around with your build tooling—but that it is possible to get them working together. I'll close this issue for now as there does seem to be support for NX monorepos, but feel free to re-open it if I've missed something. :)

**Comment by aidanhasaknife** [comment]
Hey! If you're still looking for help, you may want to look [here](https://dev.to/digikare/oclif-on-nx-monorepo-33bo). It appears from the post that you may have to fuss around with your build tooling—but that it is possible to get them working together. I'd suggest closing this issue now as there does seem to be support for NX monorepos, but it's possible I've missed something. :)
