### ISSUE TITLE
Please provide better reporting of bad flags if possible

### ISSUE THREAD

**Issue by 18aa257** [oclif/oclif#621]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------

On oclif/1.18.1 darwin-arm64 node-v14.17.3

Create the command cmd using npx oclif single cmd

(as instructed by https://oclif.io/docs/introduction)

Overwrite contents of cmd/src/index.js with contents of attached
[index.js.txt](https://github.com/oclif/oclif/files/6878403/index.js.txt)

` bin/run output --aFlag `

runs fine, but

` bin/run output --bFlag `

gives

` ›   Error: Unexpected argument: --bFlag `

What is the expected behavior?
------------------------------
It would be nice if the output were

` ›   Error: Unexpected flag: --bFlag `

because --bFlag is an invalid flag, not an invalid argument, so the error message can be confusing.

(This issue may also be related to https://github.com/oclif/oclif/issues/500)

**Comment by mdonnalley** [comment]
The latest version of `@oclif/core` will throw a `NonexistentFlag` error in this scenario. Closing the issue but please feel free to open a new issue if you're still seeing this
