### ISSUE TITLE
Allow usage of different registers instead of ts-node as default

### ISSUE THREAD

**Issue by frencojobs** [oclif/oclif#622]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A feature.

What is the current behavior?
-----------------------------
I found no way to use [esbuild](https://github.com/egoist/esbuild-register) or [swc](https://swc.rs) registers during development. `ts-node` is baked in. In the worst-case scenario, I want to at least be able to use different [ts-node transpilers](https://typestrong.org/ts-node/docs/transpilers#bundled-swc-integration) other than TSC.

What is the expected behavior?
------------------------------
Users should be able to use different registers that they prefer. The oclif version is `^1`.

**Comment by hmaurer** [comment]
`ts-node` supports alternative transpilers, with `swc` baked in; it'd be nice if that could be supported by oclif: https://github.com/TypeStrong/ts-node/releases/tag/v10.0.0

**Comment by JimminiKin** [comment]
@hmaurer I think this can already be achieved by adding
```
	"ts-node": {
		"transpiler": "ts-node/transpilers/swc"
	}
```
to `tsconfig.json`

**Comment by mdonnalley** [comment]
Closing this since:

1. You don't have to use ts-node (see https://github.com/oclif/core/pull/966)
2. oclif will honor the `ts-node.transpiler` option if you want to set that 

Feel free to open a new issue if there's something you'd like to see changed.
