### ISSUE TITLE
Feature Request: flag grouping and ordering

### ISSUE THREAD

**Issue by everett1992** [oclif/oclif#643]
By default oclif alphabetizes command flags in help output. I would like options to organize flags.
 - by preserving my defined order
 - by section or group with heading

For instance, here's `sort --help`, where ordering options are separated from other options.
```
Ordering options:

  -b, --ignore-leading-blanks  ignore leading blanks
  -d, --dictionary-order      consider only blanks and alphanumeric characters
  ...
Other options:

      --batch-size=NMERGE   merge at most NMERGE inputs at once;
                            for more use temp files
  -c, --check, --check=diagnose-first  check for sorted input; do not sort
  ...
 ```

**Comment by mdonnalley** [comment]
You can do this now by using the `helpGroup` property on the flag definitions
