### ISSUE TITLE
make circleci optional

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#68]

**Comment by jdxcode** [comment]
yes, there should be an option to check to add the 2 circleci files

**Comment by Horaddrim** [comment]
Okay, I'll try to PR this :smile: and, first of all! Congratulations for your job @jdxcode I really like people who love CLIs :D

**Comment by aequasi** [comment]
Would be nice if greenkeeper also would use npm if yarn isnt available.

**Comment by CallumDenby** [comment]
Implemented in #137 can close now @jdxcode
