### ISSUE TITLE
npx oclif@2.0.0-main.8 generate is not working

### ISSUE THREAD

**Issue by Peter-Piper** [oclif/oclif#693]
I wanted to try out the version 2.0.0 and the new features it brings.
This turns out to be impossible as running the command 
`npx oclif@2.0.0-main.8 generate mynewcli` can't succeed.

Line 75 in generators/cli.ts:
`execSync('git clone https://github.com/oclif/hello-world.git ${path.resolve(this.name)}')` will do two things:

1. requires you to log in with you git user, which is frustrating as this should never be necessary. 
2. will fail after providing your credentials with: `remote: Repository not found.
fatal: repository 'https://github.com/oclif/hello-world.git/' not found`

I'd love to try and tests the new software, but this is kinda frustrating. Is there something I'm not doing correctly here?

**Comment by RodEsp** [comment]
Hey @Peter-Piper, sorry about that! We just forgot to make the hello-world repo public.
We just did that though, so you should be able to generate new clis now without needing to log into github 😄 

Please confirm and we can close this issue.

**Comment by mdonnalley** [comment]
@Peter-Piper is this still happening for you on `oclif@2.0.0-main.11`?

**Comment by Peter-Piper** [comment]
@mdonnalley No, it now works without the issue shown above.

This ticket can be closed now (from my perspective).

However.... I've seen some change in behaviour that I'd like to address here. Then you can decide wether it's a new ticket or expected behaviour in the 2.x branch moving forward.


When I run `npm oclif@2.0.0-main.11 generate my-cli`, then normally it would suggest _my-cli_ as suggested package-name and github repository name. But now it has _oclif-hello-world_ as suggested name. Is this on purpose?

`? npm package name (oclif-hello-world)`

**Comment by mdonnalley** [comment]
@Peter-Piper thanks for pointing that out! I'll put that on our backlog of things to fix
