### ISSUE TITLE
Compatibility with Typescript 4.5.2

### ISSUE THREAD

**Issue by Fgerthoffert** [oclif/oclif#720]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

A bug (though I'm not sure if it's in Typescript or in oclif)

What is the current behavior?
-----------------------------
With Typescript 4.5.2, the following happens:

``` bash
% tsc -b
node_modules/@oclif/parser/lib/index.d.ts:16:60 - error TS2344: Type 'TArgs' does not satisfy the constraint 'any[]'.
  Type '{ [name: string]: string; }' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.

16 }>(argv: string[], options: Input<TFlags>): Output<TFlags, TArgs>;
                                                              ~~~~~

node_modules/@oclif/command/lib/command.d.ts:69:70 - error TS2344: Type 'A' does not satisfy the constraint 'any[]'.
  Type '{ [name: string]: any; }' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.

69     }>(options?: Parser.Input<F>, argv?: string[]): Parser.Output<F, A>;
    
```

The failing build can be seen here: https://github.com/Jahia/jahia-reporter/actions/runs/1473692971

Reverting to Typescript 4.4.4 did address the issue.

What is the expected behavior?
------------------------------
No errors on `tsc -b` as it is the case with Typescript 4.4.4

**Comment by scvnathan** [comment]
@Fgerthoffert Were you able to find a workaround for this, or is it still a problem?

**Comment by Fgerthoffert** [comment]
Sticking to. `4.4.4` allowed me to keep building, I did not investigate more.

**Comment by darkmavis1980** [comment]
I have a similar issue, but in my case is triggered by the `cli-ux` package

```
/node_modules/cli-ux/lib/styled/table.js:285
        columns: command_1.flags.string({ exclusive: ['extended'], description: 'only show provided columns (comma-separated)' }),
                                 ^

TypeError: Cannot read properties of undefined (reading 'string')
```

So I reverted all the changes in the `package.json` and updated one by one the packages, I reached a point where everything was up to date, apart from a few audit issues, and essentially I have to stick with these versions:

* eslint `7.32.0`
* typescript  `4.4.4`

The very moment I upgrade I start to have issues

**Comment by goulash1971** [comment]
FYI: The issue returns with typescript v4.8.2

**Comment by gojutin** [comment]
I am having the same issue with TS v4.8.2. The error: `TS2344: Type 'F' does not satisfy the constraint 'FlagOutput'.`

**Comment by jellydn** [comment]
Just FYI, I ran into the same issue with TS 4.8.3. Fixed by use `[tsup](https://tsup.egoist.dev/)` instead of `tsc`

Step 1:  change build command on package.json
from
```
 "build": "shx rm -rf dist && tsc -b",
```
to
```
 "build": "shx rm -rf dist && tsup",
```

Step 2: add tsup config file, e.g: tsup.config.json

```
{
  "entry": ["src/**/*.ts"],
  "splitting": false,
  "sourcemap": true,
  "clean": true
}
```

**Comment by Luna-Klatzer** [comment]
Reproducible on version `4.8.3` of typescript, where it arises again after upgrading from 4.7.4

**Comment by slavshik** [comment]
Reproducible for me on version `5.2.2` of typescript

**Comment by mdonnalley** [comment]
If anyone is still experiencing this on oclif/core v3, can you create a repository that replicates it? Thanks!

**Comment by mdonnalley** [comment]
Closing this as stale. Feel free to reopen if the issue still exists and you're able to share a repository that replicates the issue.
