### ISSUE TITLE
Multi-command without `package.json` or multiple multi-commands in one project?

### ISSUE THREAD

**Issue by moltar** [oclif/oclif#721]
We use `oclif` inside the project for quick scripts and other internal tooling. So far we've been using it in single-command mode only.

But now we have a requirement to use multi-command, and for the life of me I cannot figure out if this is possible.

Everything seems to point to needing to get `package.json` involved, and configure from there.

Is it possible to use multi-command mode without changes to `package.json`?

Can we have multiple multi-command commands in one project?

**Comment by mdonnalley** [comment]
@moltar I'm working on closing out old issues - is this still something you need help with? If so, could you provide some more details? The single-vs-multi command paradigm predates me so I'm not exactly sure what your issue might be. Thanks!

**Comment by moltar** [comment]
Yeah, I think we can close it. The "problem" is not solved, but I think it's also not worth it anymore. I am not very much in the monorepo camp with a very narrowly scoped packages.

This question came from the context of a unirepo where everything lived, and I wanted to build internal CLI commands with Oclif. It was not possible to have more than one command per project, because Oclif requires `package.json` manipulations.
