### ISSUE TITLE
improve prompting flow

### ISSUE THREAD

**Issue by jdxcode** [oclif/oclif#73]
To illustrate the current problem: right now it's a bit strange that you can select tslint but not typescript. Here is what I think should be the ideal flow:

* typescript? Y/n
* (if typescript) tslint? Y/n
* mocha?: Y/n
* CI (checkboxes, all default to no)
  * CircleCI
  * TravisCI
  * Appveyor
* optional components (checkboxes, all default to no)
  * codecov (only shown if mocha)
  * semantic-release

**Comment by ZaLiTHkA** [comment]
this would be awesome, but if you're going to go that far, it would be nice to have the GitLab CI variation as well... possibly even with [`semantic-release-gitlab`](https://gitlab.com/hyper-expanse/semantic-release-gitlab)..? :vulcan_salute:

**Comment by jdxcode** [comment]
we likely will not be working on extra CI integrations, but I'm happy to accept a PR for it!

**Comment by ZaLiTHkA** [comment]
I'd love to do that.. however, I'm only just scratching the surface with TS; I can't follow the code in this project well enough (yet) to help, even with the power of my nearly-finished-trial of WebStorm . sorry... (:

**Comment by CallumDenby** [comment]
I've started work on this, waiting for #138 and #139 to be implemented to finish up the logic.
