### ISSUE TITLE
Will kebab case for options flag supported in the near future?

### ISSUE THREAD

**Issue by wataruian** [oclif/oclif#738]
Seeing this issue closed: https://github.com/oclif/oclif/issues/107

Will this be supported in the near future? I am seeing a lot of CLIs implementing this. Is kebab-case not a unix standard?

**Comment by mdonnalley** [comment]
@wataruian we have no plans on implementing the feature described in #107 

To be clear though, you are currently able to define kebab-case flags. For example, 

```typescript
import { Command, Flags } from '@oclif/core';
export default class MyCommand extends Command {
  public static flags = {
     'my-flag': Flags.boolean({
        summary: 'kebab-case flag',
      }),
  }

  public async run() {
    const { flags}  = await this.parse(MyCommand);
    console.log(flags['my-flag');
  }
}
```

**Comment by wataruian** [comment]
Thanks! It worked.
