### ISSUE TITLE
Deprecated documentation, missing command "command"

### ISSUE THREAD

**Issue by bumbummen99** [oclif/oclif#752]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
- Follow getting started.
- Execute `npx oclif command Test`

Following error:
```
 ›   Warning: command is not a oclif command.
Did you mean promote? [y/n]: n
 ›   Error: command command not found
```
What is the expected behavior?
------------------------------
[As mentioned in the documentation](https://oclif.io/docs/generator_commands#oclif-command-name)

**Comment by vinhhuynh-mck** [comment]
Command `npx oclif command Test` just works for Oclif version 1.8.4 or lower. Your issue will exist from Oclif v2.x

**Comment by bumbummen99** [comment]
> Command `npx oclif command Test` just works for Oclif version 1.8.4 or lower. Your issue will exist from Oclif v2.x

Where can the documentation for v2.x be found? I would have assumed it is for main/master.

**Comment by mdonnalley** [comment]
The README has been updated now: https://github.com/oclif/oclif#-migrating-from-v1
