### ISSUE TITLE
Bug: Oclif pack does not work on Yarn v3

### ISSUE THREAD

**Issue by emoyly** [oclif/oclif#759]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
This is a bug.

What is the current behavior?
-----------------------------
Running oclif-dev pack causes Yarn to throw the error  `Unknown Syntax Error: Unsupported option name ("--no-progress").`
Full console output here: https://gist.github.com/0b3f84e2d261486ab4b05743dae7a003

The line causing the issue seems to be here: https://github.com/oclif/oclif/blob/61cb7664ce38f1b7827ff652f063c3be7adeb1af/src/tarballs/build.ts#L63

I assume this is because Oclif is expecting Yarn v1, but as v1 is no longer maintained, I would argue it makes a lot of sense to support v2/v3/berry. 
I don't know exactly how to solve this. The best solution would probably be to detect the version of Yarn installed, and then use different arguments for the Yarn cli based on that.

Steps to reproduce
-----------------------------
1. Install Yarn v3 (berry) in your Oclif command repository
2. Run oclif-dev pack

What is the expected behavior?
------------------------------
I would expect it to work according to the documentation.

### Versions:
**@oclif/dev-cli:** 1.26.9
**@oclif/command:** 1.8.13
**@oclif/config:** 1.18.2
**@oclif/plugin-help:** 3.2.17

**Yarn:** 3.0.2
**Node.JS:** v16.13.0
**OS:** Ubuntu 20.04.3 LTS (In WSL)

**Comment by HardCoreQual** [comment]
I encountered this problem during try to integrate `yarn` workspace to manage monorepo, after `--no-progress` error I switch yarn workspace to use `lerna`, but also fail because `oclif-dev` reinstall dependencies instead using it's from node_modules

**Comment by newtykins** [comment]
For now, I recommend just running `yarn set version ^1.x` if you are still having issues or need an easy workaround (:

**Comment by strophy** [comment]
Thanks @newtykins! This worked for me by setting `yarn set version classic` followed by `yarn install`. You may also need to remove any lines like `"packageManager": "yarn@3.1.0",` in your `package.json` if working with a monorepo, otherwise you will still get the `--no-progress` error when oclif tries to run a command in a shell, and uses the wrong version of yarn from `package.json` again.

**Comment by ricardomartinez-contentsquare** [comment]
Hi, Could be possible to adjust the command by reading the `package.json` and checking property `"packageManager": "yarn@x.x.x"`? Maybe we need to add some extra check to determine which is the root `package.json` to read the property from. I think that I can put together a PR if this will help 😃

**Comment by DaanSchoukens** [comment]
I'm also in need of yarn v3 support. 
@ricardomartinez-contentsquare Where you going to make a PR for this?

**Comment by lordrip** [comment]
In an ideal scenario, I think that makes sense to put it here 😄 , but just wanted to check with the team if they have time to review it 👍

**Comment by peniqliotuv** [comment]
> > For now, I recommend just running `yarn set version ^1.x` if you are still having issues or need an easy workaround (:
> 
> The PR to handle this has been hanging around for a while - for a different (somewhat better?) workaround in the meantime, as opposed to downgrading yarn, you can leverage yarn patch https://yarnpkg.com/cli/patch and make an update like
> 
> ```diff
> diff --git a/lib/tarballs/build.js b/lib/tarballs/build.js
> index 6dc6c060ccb11346ba9e9d38346521e2fd0b9e77..f396c11634b8987692eff237b6e6ecedda6bd57f 100644
> --- a/lib/tarballs/build.js
> +++ b/lib/tarballs/build.js
> @@ -52,7 +52,7 @@ async function build(c, options = {}) {
>          const yarnRoot = findYarnWorkspaceRoot(c.root) || c.root;
>          if (fs.existsSync(path.join(yarnRoot, 'yarn.lock'))) {
>              await fs.copy(path.join(yarnRoot, 'yarn.lock'), path.join(c.workspace(), 'yarn.lock'));
> -            await exec('yarn --no-progress --production --non-interactive', { cwd: c.workspace() });
> +            await exec('yarn workspaces focus --all --production', { cwd: c.workspace() });
>          }
>          else {
>              const lockpath = fs.existsSync(path.join(c.root, 'package-lock.json')) ?
> ```
> 
> if/when it breaks on you, it'll be a clue that the pack logic changed either way.

FYI - you'll need the `workspace-tools` plugin to make that work.

**Comment by partyzan** [comment]
@peniqliotuv I am hitting this wall as well, can you elaborate how you used yarn patch as a workaround? Do you need the oclif as a dependency in the cli project itself and not as a global install for this to work?
