### ISSUE TITLE
"generate is not a oclif command."

### ISSUE THREAD

**Issue by intelliot** [oclif/oclif#760]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
"generate is not a oclif command."

What is the expected behavior?
------------------------------
Docs should reflect the actual version of oclif available from npm as oclif@latest

**Comment by mdonnalley** [comment]
@intelliot thanks for calling this to our attention. I think have accidentally pointed latest back to v1 at some point last week.

The latest tag now points to `2.0.1`, which matches the docs
