### ISSUE TITLE
Bug：run oclif-dev readme throw Error

### ISSUE THREAD

**Issue by monsterboom** [oclif/oclif#761]
1. npm run pre pack
2. when it run `oclif-dev readme`，it throw an Error

```
replacing <!-- usage --> in README.md
    TypeError: HelpClass is not a constructor
```

Here is my dependencies
    "@oclif/command": "^1",
    "@oclif/config": "^1",
    "@oclif/plugin-help": "^3",
    "@oclif/plugin-plugins": "^1.10.1",
    "@oclif/dev-cli": "^1"

my environment
    Operating System - Windows 10 Home China, version 10.0.19042 x64
    Node.js environment
        Node.js - v16.13.0
        npm - 8.1.0
        yarn - 1.22.17

**Comment by peternhale** [comment]
@monsterboom thank for reporting the issue. Could you provide the results of `npm list --depth 1` for your project?

**Comment by hectorvp** [comment]
@monsterboom Did you get any resolution for this bug?

**Comment by allanpaiste** [comment]
Getting same thing:

```
❯ npm list --depth 1|grep oclif
├─┬ @oclif/command@1.8.16
│ ├── @oclif/config@1.18.3 deduped
│ ├── @oclif/errors@1.3.5 deduped
│ ├── @oclif/help@1.0.1 deduped
│ ├── @oclif/parser@3.8.7
├─┬ @oclif/config@1.18.3
│ ├── @oclif/errors@1.3.5 deduped
│ ├── @oclif/parser@3.8.5
├─┬ @oclif/dev-cli@1.26.0
│ ├── @oclif/command@1.8.16 deduped
│ ├── @oclif/config@1.18.3 deduped
│ ├── @oclif/errors@1.3.5 deduped
│ ├── @oclif/plugin-help@3.2.10
├─┬ @oclif/errors@1.3.5
├─┬ @oclif/help@1.0.1
│ ├── @oclif/config@1.18.2
│ ├── @oclif/errors@1.3.5 deduped
├─┬ @oclif/plugin-autocomplete@1.2.0
│ ├── @oclif/core@1.6.4
├─┬ @oclif/plugin-help@5.1.12
│ └── @oclif/core@1.6.4
├─┬ @oclif/plugin-not-found@2.3.1
│ ├── @oclif/color@1.0.1
│ ├── @oclif/core@1.3.0
├─┬ @oclif/test@1.2.8
│ ├── @oclif/core@0.5.41
│ ├── @oclif/linewrap@1.0.0
│ ├── @oclif/screen@1.0.4
├─┬ eslint-config-oclif@4.0.0
├─┬ eslint-config-oclif-typescript@1.0.2
```

**Comment by peternhale** [comment]
@monsterboom I would recommend migrating to [@oclif/core](https://github.com/oclif/core). Many of the libraries you are using today are in maintenance mode. There is a migration guide linked on @oclif/core home page.
