### ISSUE TITLE
Migration docs

### ISSUE THREAD

**Issue by florianbepunkt** [oclif/oclif#762]
Could you please provide some migration from Oclif v1 to v2?

**Comment by mdonnalley** [comment]
@florianbepunkt we have a [migration guide](https://github.com/oclif/core/blob/main/MIGRATION.md) for migrating your plugin(s) to the new `@oclif/core` library

The oclif v2 executable is for the most part a drop-in replacement for v1

I'm going to close this issue but feel free to reopen it if you feel like there's more that we need to document
