### ISSUE TITLE
`command is not a oclif command` When trying to create a new command

### ISSUE THREAD

**Issue by MonteKrysto** [oclif/oclif#767]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Possible bug

What is the current behavior?
-----------------------------
Run `oclif generate mynewcli`
`cd mynewcli`
Run `oclif command setup` to create a `setup` command

What is the expected behavior?
------------------------------
oclif/2.0.1 darwin-arm64 node-v14.18.0
Big Sur 11.6
When running `oclif command setup` I expect a new `setup` command to be scaffolded

**Comment by emadridm** [comment]
This happen in version 2.1.0 too.

**Comment by verymuch** [comment]
Commands `hook` and  `plugin` are lost in version 2.1.0 too.

**Comment by verymuch** [comment]
I found that it was deleted by @RasPhilCo in [this commit](https://github.com/oclif/oclif/commit/731ed490bc3bc1857d414dfd56d0d8dfd7b6be2b#diff-f0f9cc2d816c784657b8d246460afcc23530b9de1ce49e748871426fb75d50de). 

Is there some kind of upgrade plan?

**Comment by mdonnalley** [comment]
@MonteKrysto @verymuch @emadridm Thanks for brining this to our attention - we had originally planned on adding back the `hook` and `command` commands but that intention got lost when some team members left a few months ago.

On the bright side, I do have a [PR](https://github.com/oclif/oclif/pull/783) for this now which other members of the team will review this week. The PR also includes a few notes in the README about the differences between v1 and v2

**Comment by ImmaZoni** [comment]
Thanks for the fix! Hope the PR is merged soon
