### ISSUE TITLE
Get Started not giving expected result

### ISSUE THREAD

**Issue by brightonmike** [oclif/oclif#785]
I'm using Node LTS 17.3.0.

I ran the commands exactly as per the docs:
https://oclif.io/docs/introduction#quickstart

However my output is:

```
./bin/run hello
Say hello to the world and others

USAGE
  $ mynewcli hello COMMAND
 ```

Feels wrong as docs suggest this should show as `mynewcli COMMAND`.

If I run `mynewcli` in the terminal I also get "command not found". Any ideas what I'm doing wrong?

**Comment by mdonnalley** [comment]
@brightonmike thanks for pointing this out - I'll work on updating that quick start example today.

It should be this:
```
$ npx oclif generate mynewcli
? npm package name (mynewcli): mynewcli
$ cd mynewcli
$ ./bin/dev hello world
hello world! (./src/commands/hello/world.ts)
```


Also, we don't automatically add `mynewcli` to your `PATH` for a number of reasons. So you'll need to do that yourself. Alternatively, if you plan to publish your CLI to npm then `npm install -g mynewcli` will automatically add it to the `PATH` for you

**Comment by brightonmike** [comment]
> ./bin/dev hello world

Ahh great! `./bin/dev hello world` works as expected, and noted on the path variable. Thanks!
