### ISSUE TITLE
Odd vertical characters in terminal when running oclif

### ISSUE THREAD

**Issue by bslayerw** [oclif/oclif#787]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

When running `oclif` I get weird characters scrolling vertically in the terminal. I attempted a google search but no matter which way I described this issue I couldn't find a lead. I attempted to alter my terminal settings (change fonts, double-check encoding etc). Nothing resolved it. I suspect it's something in my environment (`zsh`) or one of the `oclif` packages that are sending characters it doesn't understand. This is only happening with `oclif` 

I'm sure it's just a settings I'm missing. Any help would be appreciated. Here's a screenshot

<img width="1319" alt="Screen Shot 2022-01-08 at 10 40 19 PM" src="https://user-images.githubusercontent.com/42391/148669023-e894fdb3-f4af-4ff4-8895-399b6e04942e.png">

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
- launch terminal 
- run `npx oclif generate test`
- observe terminal output
What is the expected behavior?
- launch terminal
- run `npx oclif generate test`
- log messages from `oclif` should display in text characters.
------------------------------
Please mention your oclif and OS version.

System Info
MacBook Pro M1 Max
Monterey (12.1)
shell: `zsh` (same issues in bash)
Version: `8.3.0`

**Comment by kc-dot-io** [comment]
@bslayerw We're also seeing this. This appears to be a supply chain attack.

**Comment by mdonnalley** [comment]
https://github.com/oclif/oclif/issues/786
