### ISSUE TITLE
Bug: `oclif generate` doesn't work when cwd contains spaces

### ISSUE THREAD

**Issue by amirhoseinsalimi** [oclif/oclif#789]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A bug.

What is the current behavior?
-----------------------------
`generate` command throws an exception if the path contains spaces. This is caused by the `git clone` command I guess.
Screenshot:

![image](https://user-images.githubusercontent.com/25503371/148740812-06e7c151-a97a-4d25-a31c-7de7b95b0212.png)

### Steps to reproduce
(I describe this in a Linux system)
```bash
cd
mkdir "Folder with Spaces"
oclif generate example
```

What is the expected behavior?
------------------------------
`oclif generate` should work even when the path contains spaces.

Environment:
oclif/2.1.4 linux-x64 node-v16.13.1

Do you want to contribute?
------------------------------
Sure 😃.

**Comment by mdonnalley** [comment]
Fixed by https://github.com/oclif/oclif/pull/783
