### ISSUE TITLE
oclif manifest throws error when using custom flag with function for "default"

### ISSUE THREAD

**Issue by motabass** [oclif/oclif#800]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
BUG

What is the current behavior?
-----------------------------
When i try to pack my CLI `oclif manifest` throws an error when i try to use a custom flag with a function assigned to default.

my custom flag (  // @ts-ignore was also necessary to make it even build):
```
export const containerNameFlag = Flags.build<string>({
  char: 'c',
  description: 'Name des Docker-Containers',
  required: false,
  // @ts-ignore
  default: () => getUserConfig().apache?.containerName ?? 'pos-dev-apache',
  env: 'POS_DEV_APACHE_CONTAINER_NAME'
});
```

the error i get:
```
 TypeError Plugin: @mng/devtools: The "path" argument must be of type string. Received undefined
    Code: ERR_INVALID_ARG_TYPE

```
This implementation works fine when i start it via `bin/run` or `bin/dev` but i cant deploy it anymore due to the error in `oclif manifest`.

When i declare the "default"-property as a string all works normal but i'd really want to get defaults from my config-file like explained in https://oclif.io/docs/flags:
```
export const containerNameFlag = Flags.build<string>({
  char: 'c',
  description: 'Name des Docker-Containers',
  required: false,
  default: 'pos-dev-apache',
  env: 'POS_DEV_APACHE_CONTAINER_NAME'
});
```

What is the expected behavior?
`oclif manifest` should run just fine when using default functions in flags.

------------------------------
oclif 2.2.0, ,Windows 11 - WSL2 (ubuntu)

**Comment by motabass** [comment]
The Issue was totally my fault...sorry to bother you

**Comment by peternhale** [comment]
Hi @motabass, I was wondering if you could let us know what you did to resolve the issue?

**Comment by motabass** [comment]
the problem was in getUserConfig(). I was accessing `global.someGlobalVar` which i am initializing only in `bin/run` an `bin/dev`. So it was `undefined` in during `oclif manifest`.

What helped me was to install oclif@2.0.0 which had more error output which then led me to my own function.
