### ISSUE TITLE
[Feature Request] Support new flags: Flags.file, Flags.folder, Flags.fileAndFolder

### ISSUE THREAD

**Issue by theoffricial** [oclif/oclif#803]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

`Flags.file` support, `Flags.folder` support, and combined both file and folder flag.

Currently, when I want one of my CLI commands to support a flag which is a path to a file there is no support for `autocomplete` for files/folders in my current location, This feature is crucial in terms of user experience because it saves a lot of time. 
I won't be surprised if someone in your company implemented it already as a `Custom flag` already.

So currently I have to type the exact path for my command to start using the path which sometimes can be really furstrated.

My guess is this issue is between the `core` repo and the `plugin-autocomplete` repo but both are maintained by `oclif`, so I wrote it here.

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

Currently, I need to use `Flags.string` and type without completing the whole path by myself, which is super inconvenient.
Also, the `Flags.url` is not helping because it won't do the auto-complete.

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

OS: macOS, specific version is not relevant. but I'm using Big Sur.

oclif version:
![image](https://user-images.githubusercontent.com/22051969/150539653-8c98f451-eaca-41b6-8930-412d2d64804a.png)

The expected behavior

When I'm setting a "file" or "folder" flag, I would expect to click <TAB> twice and see the current files/folders on my current CMD/iTerm location, for instance: on macOS when I'm on my home dir (~) and click <TAB> I would expect to see "Downloads", similar to the auto-complete of the linux commands: "cd" and "cat".

**Comment by mdonnalley** [comment]
`@oclif/core` exports `Flags.file` and `Flags.directory`. If you want a flag that combines the two, you can always use `Flags.custom` to implement it yourself.
