### ISSUE TITLE
Question: Default commands in v2

### ISSUE THREAD

**Issue by Peter-Piper** [oclif/oclif#835]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
In v1 a way to create a default command, i.e. a way to call the cli without any commands or topics, was introduced.
Unfortunately I do not see in any docs, how this is done in v2. I've tried the following:

- Creating an alias `['', ' ']`, but this does not seem to work
- Creating an `index` command (`oclif generate command index`), which results in a `[..]/commands/index.ts`, but this also does not seem to be working

Is there a way to introduce the default command again, so I can call the packaged cli without params and it will call the correct command. This means that `help` will only be available as command and `--help` and no longer the default behaviour.

I'm using oclif/2.4.5 darwin-x64 node-v16.14.0

**Comment by Peter-Piper** [comment]
I just realised going through the source code that the package.json's `oclif` property can contain a `default` which can be the name of the default command. So just leaving this for future reference:

```
 "oclif": {
    "bin": "wizard",
    "dirname": "wizard",
    "commands": "./dist/commands",
    "default": "mydefaultcommand",
    "plugins": [
      "@oclif/plugin-help"
    ],
    "topicSeparator": " ",
    "topics": {}
  },
```

**Comment by Geylnu** [comment]
yes, it works
