### ISSUE TITLE
querystring is deprecated

### ISSUE THREAD

**Issue by tomasmateus** [oclif/oclif#851]
When installing this package, npm prints the following warning:

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

This is because this package depends on aws-sdk, and aws-sdk depends on querystring, which has been deprecated.

**Comment by mdonnalley** [comment]
Closing this since the latest version depends on v3 of aws-sdk, which doesn't have a dependency on querystring
