### ISSUE TITLE
Should this.log have the same interface as console.log?

### ISSUE THREAD

**Issue by JuanCaicedo** [oclif/oclif#88]
```js
const { args } = this.parse(MyCLI)

this.log('args', args)
// args
```

It looks like only the first argument will be logged. I say that because of
this:

```js
this.log(args) 
// { 'my-arg': 'my-value' } 
```

What I would expect is this

```js
this.log('args', args)
// args { 'my-arg': 'my-value' } 
```

To clarify, I made the assumption that `this.log` would behave exactly the same
as `console.log`. Is that the expected behavior? If so, would you like any help
implementing that?

There might be some sharp edges related to the other features of console.log,
like formatting and substitution:
<https://developer.mozilla.org/en-US/docs/Web/API/console#Outputting_text_to_the_console>

**Comment by jdxcode** [comment]
I'm open to this, it should be pretty easy though. Just pass the args to `util.format`: https://nodejs.org/api/console.html#console_console_log_data_args

**Comment by jdxcode** [comment]
https://github.com/oclif/command/commit/7d145e1fff534acd4349eb78d3ef65208d8b1345

**Comment by JuanCaicedo** [comment]
🙌
