### ISSUE TITLE
Bug: Top-level --help does not show descriptions for custom commands

### ISSUE THREAD

**Issue by gary-affonso-remitly** [oclif/oclif#880]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Report a bug

What is the current behavior?
-----------------------------
When getting top-level help, my commands are listed but they do not show descriptions:
```
crush --help
RTE Command-Line Utilities

VERSION
  crush/1.0.0 darwin-x64 node-v16.14.0

USAGE
  $ crush [COMMAND]

COMMANDS
  auth
  help    Display help for crush.
  scrape
```

Neither the `auth` or the `scrape` commands show a description.  But the command-definitions do have descriptions defined...

```
export default class ScrapeCommand extends Command {
  static description = `
    Extract the key values of a submit-request from a Transaction Control log statement.

    Pipe input into this command (presumably, using something like pbaste).

    By default, emits submit-request as json to stdout.
`
```

What is the expected behavior?
------------------------------
Display the description (maybe just the first line) that's defined in the command-file.

Even better would be to support a "short-description` in the command-file that could be used specifically for these top-level help command descriptions.

What version of oclif are you using?
------------------------------
```
  "dependencies": {
    "@oclif/core": "^1.7.0",
    "@oclif/plugin-help": "^5",
    "@oclif/plugin-plugins": "^2.0.1",
```

**Comment by RodEsp** [comment]
Hey @gary-affonso-remitly, there is already a "short-description" static property called `summary`. That is what will show up in the top level help.

Using your example you'd want to set it like so:
```js
export default class ScrapeCommand extends Command {
  static summary = "Extract the key values of a submit-request from a Transaction Control log statement."
  static description = `
    Extract the key values of a submit-request from a Transaction Control log statement.

    Pipe input into this command (presumably, using something like pbaste).

    By default, emits submit-request as json to stdout.
`
```

**Comment by gary-affonso-remitly** [comment]
Aha!  Fantastic!  Thank you!  (sorry I missed that)

**Comment by RodEsp** [comment]
No problem! 😄 
Hope that helps!
