### ISSUE TITLE
Feature Request?: Make central logger accessible in non-Command classes

### ISSUE THREAD

**Issue by gary-affonso-remitly** [oclif/oclif#881]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
I think I'm making a feature-request unless this functionality already exists.

What is the current behavior?
-----------------------------
Within command-classes you have access to an internal logger.  You can emit log messages like so:
```
    this.debug(`my log ${message}`)
```

One lovely thing about this logger is that it honors the DEBUG ENV value.

If you have custom code that is used-by your command classes (a library, say) you do not have access to the central logger via `this` in those libs.  I believe the oclif docs say that these non-command classes can always use `console.log, etc.` which is true, but those do not honor the central DEBUG env-var.

I would like all debug messages (both those emitted by commands and those emitted by non-command imports such as libs) to use the central logger (and be controllable via the central DEBUG env var)

I was thinking that maybe I could retrieve a reference to the central logger object and pass it into my lib functions as a param (not ideal but better than nothing), but I could not find anything on "this" that will give me a reference to the logger.

What is the expected behavior?
------------------------------
Allow code in non-command classes to access the central logger.

Please mention your oclif and OS version.
------------------------------------------
Oclif:
```
  "dependencies": {
    "@oclif/core": "^1.7.0",
    "@oclif/plugin-help": "^5",
    "@oclif/plugin-plugins": "^2.0.1",
```

OS: `darwin-x64 node-v16.14.0`

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by gary-affonso-remitly** [comment]
Agreed.

The current solution (oclif-supported logging in commands, non-oclif logging everywhere else) yields a pretty terrible logging experience.

Particularly if you're isolating your "business logic" outside of the command class (a good idea, IMO).  All our commands do is trigger calls out to "real" (easily testable) code/classes.  All the "real" logging we want to do is not in command classes.

> This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

It certainly will have a chilling effect on my own willingness to write-up suggestions like the above.

**Comment by nsssayom** [comment]
This suggestion makes a very good sense and closing the issue is maybe not a very good idea!

**Comment by usrbowe** [comment]
Should be able to use the logger via error package: https://oclif.io/docs/commands#thiserrormessage-string--error-options-code-string-exit-number-ref-string-suggestions-string

> Note: You may need to install the latest `@oclif/core` and `@oclif/errors` for code, suggestions and ref to be displayed.


```js
import {CLIError} from '@oclif/errors'

throw new CLIError('my friendly error')
```
