### ISSUE TITLE
The channel files and indexes miss public read ACL

### ISSUE THREAD

**Issue by riywo** [oclif/oclif#884]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
A bug.

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

Unlike `oclif upload`, `oclif promote` doesn't set `public-read` ACL. Therefore, every promotion breaks the channel.

On the build machine:

```
$ npx oclif pack tarballs
$ npx oclif upload tarballs
$ npx oclif promote --channel development --version 0.0.0-development --sha SHA --indexes
```

Then, on the client side:

```
❯ DEBUG=\* ./bin/mycli update --available
  http → GET https://BUCKET.s3.amazonaws.com/versions/mycli-darwin-arm64-tar-gz.json
  http ← GET https://BUCKET.s3.amazonaws.com/versions/mycli-darwin-arm64-tar-gz.json 403
  http   '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5WDFSGNJ6JQQXWH1</RequestId><HostId>N+cLoMqEr8NCqfi/+s3qMOrQahnP+E4SqOFwL3bT06kMu+wJOLaDlUGrOP+LxVITOUAwRbbh7PU=</HostId></Error>' +157ms
Error: No version indices exist for mycli.
```

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

`oclif promote` should set `public-read` ACL like `oclif upload`.

### `oclif upload`
https://github.com/oclif/oclif/blob/c26946d64a1b3c8702fd71b92010f1006970c7ff/src/commands/upload/tarballs.ts#L37-L40

### `oclif promote`
https://github.com/oclif/oclif/blob/e9d89f567abbbba72fd0da4641d131bf703e77c7/src/commands/promote.ts#L60-L68
https://github.com/oclif/oclif/blob/e9d89f567abbbba72fd0da4641d131bf703e77c7/src/version-indexes.ts#L68-L72

```
$ npx oclif --version
oclif/3.0.1 linux-x64 node-v16.14.0
```

**Comment by truesteps** [comment]
I was just about to create this issue... I'm experiencing the same problem! The version-indexes.ts file does not include ACL definition from package.json, i'm gonna try and send a PR

**Comment by riywo** [comment]
Currently, we use `patch-package` https://github.com/autifyhq/autify-cli/blob/main/patches/oclif%2B3.2.1.patch (including another patch there)
