### ISSUE TITLE
All heroku commands on Windows exit with code 1 on success

### ISSUE THREAD

**Issue by frederikhors** [oclif/oclif#886]
I'm sorry to open this here, but on the heroku/cli repo [this bug](https://github.com/heroku/cli/issues/1051) is from 2018 and was closed but it's still an issue.

> Hello, I'm on Heroku CLI 7.16.0 using Windows 10 and it seems like _all_ Heroku commands exit with status code 1 even when they succeed using git bash, e.g.:
> 
> ```shell
> $ heroku maintenance:on
> Enabling maintenance mode for ⬢ tenants2... done
> $ echo $?
> 1
> ```
> 
> Or:
> 
> ```shell
> $ heroku container:push -R
> ... stuff happens ...
> Your image has been successfully pushed. You can now release it with the
> 'container:release' command.
> $ echo $?
> 1
> ```
> 
> This might be a more general case of #955. In any case, it makes automating things with the CLI not terribly reliable.

I'm using `heroku/7.60.2 win32-x64 node-v14.19.0` with PowerShell or Git Bash for Windows (sh.exe) and the problem is still there.

This is a HUGE problem.

Can we fix it in some way?

**Comment by maciejgliwinski** [comment]
The solution for windows machine is to use WSL (installed from Microsoft store). Then use command `wsl --install Ubuntu` to install Ubuntu distribution. run then wsl command and install heroku cli: `curl https://cli-assets.heroku.com/install-ubuntu.sh | sh`.

**Comment by mdonnalley** [comment]
Closing this since https://github.com/heroku/cli/issues/1051 has been reopened
