### ISSUE TITLE
Non-root user support for `oclif pack deb`

### ISSUE THREAD

**Issue by riywo** [oclif/oclif#887]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Mixture.

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

With non-root user:

```
$ npx oclif pack deb
...
    Error: Command failed: /bin/sh -c chown -R root "/workspaces/mycli/tmp/apt/mycli_0.1.0.d5f2854-1_amd64.apt"
    Code: 1
```

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.

Here is the problematic code:

https://github.com/oclif/oclif/blob/e9d89f567abbbba72fd0da4641d131bf703e77c7/src/commands/pack/deb.ts#L78-L79

These days we don't need to use the real root user when packaging deb:

https://askubuntu.com/questions/735883/what-user-file-owner-to-use-when-creating-debian-packages

**Comment by mdonnalley** [comment]
Fixed by #987
