### ISSUE TITLE
Option to hide aliases from root help commands list

### ISSUE THREAD

**Issue by devdumpling** [oclif/oclif#888]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
Running `[bin]` or `[bin] help` gives the root help for the CLI, including the list of all available commands. This is great for discovering everything that's available. However, my project supports many aliases, and those are cluttering the list making it harder to see what's available at a glance. It would be nice if there was a quick way to hide aliases from showing up in the root help.

I'm new to oclif and was trying to get this to work with the custom Help classes. Still digging there, so might find a cleaner solution but flagging it as a nice-to-have.

What is the expected behavior?
------------------------------
Passing some kind of `hideAliasesFromRoot` option to a command (or at a higher level config) hides command alias from `rootHelp`.

**Comment by shazron** [comment]
Related #925

**Comment by motabass** [comment]
I also tried CustomHelp class approach and finally found a preety good solution:

`import { Help } from '@oclif/core';
import * as Interfaces from '@oclif/core/lib/interfaces';

export default class MyHelpClass extends Help {
  formatCommands(commands: Interfaces.Command[]): string {
    if (commands.length === 0) return '';

    // console.log(commands);

    const mainCommandNames: Set<string> = new Set<string>();
    for (const command of commands) {
      if (!command.aliases.some((a) => a === command.id)) {
        mainCommandNames.add(command.id);
      }
    }

    const body = this.renderList(
      commands
        .filter((c) => mainCommandNames.has(c.id))
        .map((c) => {
          if (this.config.topicSeparator !== ':') c.id = c.id.replace(/:/g, this.config.topicSeparator);

          return [c.id, this.summary(c) + ` (Aliases: ${c.aliases.join(', ')})`];
        }),
      {
        spacer: '\n',
        stripAnsi: this.opts.stripAnsi,
        indentation: 2
      }
    );

    return this.section('COMMANDS', body);
  }
}
`
