### ISSUE TITLE
'myCommand' -h not working

### ISSUE THREAD

**Issue by grloch** [oclif/oclif#892]
Do you want to request a *feature* or report a *bug*?
Possible a bug (?)

-----------------------------------------------------

What is the current behavior?
When I test using ``.\bin\run hello -h`` the terminal returns ``TypeError: cmd._help is not a function``

-----------------------------

If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?
I'm using the follow command:
```import {Command, Flags} from '@oclif/core'

export default class Hello extends Command {
  static description = 'Say hello'

  static examples = [
    `$ oex hello friend --from oclif
hello friend from oclif! (./src/commands/hello/index.ts)
`,
  ]

  static flags = {
    from: Flags.string({char: 'f', description: 'Whom is saying hello', required: true}),
    help: Flags.help({ char: "h" }),
  }

  static args = [{name: 'person', description: 'Person to say hello to', required: true}]

  async run(): Promise<void> {
    const {args, flags} = await this.parse(Hello)

    this.log(`hello ${args.person} from ${flags.from}! (./src/commands/hello/index.ts)`)
  }
}
```
 I would expect that the framework display the help of the command, with description etc, insted, it display the folling error: ``TypeError: cmd._help is not a function``

------------------------------

Please mention your oclif and OS version.
oclif:
```
"@oclif/core": "^1"
"@oclif/plugin-help": "^5"
"@oclif/plugin-plugins": "^2.0.1"
```
OS
`Windows 11`

**Comment by gafish** [comment]
i have the issue also

**Comment by carryall** [comment]
I found a solution in [this issue](https://github.com/oclif/plugin-help/issues/44) in plugin-help 

> You can do it with additionalHelpFlags in your configuration. Example
> 
> `"additionalHelpFlags": ["-h"]`
