### ISSUE TITLE
Testing documentation

### ISSUE THREAD

**Issue by JuanCaicedo** [oclif/oclif#90]
I noticed that the generated tests don't look like the mocha tests that I'm used to. That's probably because they leverage [@oclif/test](https://github.com/oclif/test). 

I'm not opposed to that at all (especially if it makes testing easier 😄), but it would be helpful when writing new tests to have some documentation to reference.

I plan on writing some tests, if you want I would be willing to help write up some documentation as I go

**Comment by jdxcode** [comment]
yeah the helpers are there to make things like starting the CLI and wrapping stdout/stderr easier. It should have docs.
