### ISSUE TITLE
bin/run can't be executed without previous "npm run build"

### ISSUE THREAD

**Issue by pe1uca** [oclif/oclif#905]
I have a new CLI generated with version 3 that when I try to run a new command or any update to an existing command requires "npm run build" to be ran.  

With an old one in version 1 I can easily change anything and type `./bin/run mycommand` and see the changes.  
Even new commands can easily be added and accessed without a build step.  

What do I need to have this behavior in the new version?

**Comment by AndrewSouthpaw** [comment]
I'm assuming `ts-node` was used previously to run directly from TS source files, I'm a little surprised it now runs from generated JS files... Is there any way to enable that behavior?

**Comment by mdonnalley** [comment]
You can achieve this by using `bin/dev` instead of `bin/run`

**Comment by AndrewSouthpaw** [comment]
Ah great, thanks! Any objections to me contributing to the documentation to clarify the difference in behavior?

**Comment by Ak-patel** [comment]
> Ah great, thanks! Any objections to me contributing to the documentation to clarify the difference in behavior between `/bin/run` and `/bin/dev`?

Can we replace ./bin/dev by a custom string  like **mycmd mycommand** instead of ./bin/dev mycommand

**Comment by acerbisgianlucathoesch** [comment]
Hey there,
I've the same problem, but with `bin/dev.js` as well. How does it know to look for the commands in the `src/` folder instead of `dist/`?
If I delete the `dist/` folder and run the CLI, it tells me there are no commands. While if I build the code and run it, then I've all the commands. This happens with both files.

dev.js:
```javascript
#!/usr/bin/env -S npx tsx --no-warnings
import {execute} from '@oclif/core';
await execute({development: true, dir: import.meta.url});
```

run.js:
```javascript
#!/usr/bin/env npx tsx
import {execute} from '@oclif/core';
await execute({dir: import.meta.url});
```

**Comment by acerbisgianluca** [comment]
Hey there,
I've the same problem, but with `bin/dev.js` as well. How does it know to look for the commands in the `src/` folder instead of `dist/`?
If I delete the `dist/` folder and run the CLI, it tells me there are no commands. While if I build the code and run it, then I've all the commands. This happens with both files.

dev.js:
```javascript
#!/usr/bin/env -S npx tsx --no-warnings
import {execute} from '@oclif/core';
await execute({development: true, dir: import.meta.url});
```

run.js:
```javascript
#!/usr/bin/env npx tsx
import {execute} from '@oclif/core';
await execute({dir: import.meta.url});
```

Ref: oclif/core#1170

**Comment by tehnrd** [comment]
I am also very curious about the documented differences between `await execute({development: true})` and  `await execute({development: false})`. I will eventually dig through the source code later to try to answer myself, but if anyone knows, that would be great. 

I am simply using oclif in a project for it's ts support and clear args/flag API. I have no intention to build or distribute these commands as an actual CLI, so I am happy to use `tsx` to run with `{development: true}`, but it would be good to know all the implications of doing this.

**Comment by mdonnalley** [comment]
> I am also very curious about the documented differences between await execute({development: true}) and await execute({development: false}). I will eventually dig through the source code later to try to answer myself, but if anyone knows, that would be great.

You can see [here](https://github.com/oclif/core/blob/4.0.20/src/execute.ts#L58-L62) that we do two things when `development:true`

1. set `process.env.NODE_ENV = 'development'` - this tells oclif/core to attempt to use the ts source instead of the compiled js. Here's the [function](https://github.com/oclif/core/blob/4.0.20/src/config/ts-path.ts#L286) where that's done
2. set `settings.debug = true` - this gives you stack traces anytime there's an error or warning

**Comment by tehnrd** [comment]
@mdonnalley Perfect, thank you!

I don't care about NODE_ENV as it doesn't impact anything in my project, and I would like to see full stack traces/warnings, so running with dev is fine for isolated project scripts. 

I'm essentially just looking for a replacement for [commander](https://www.npmjs.com/package/commander) where I want to run simple single file screens but with a clean API for args. Looks like development node does what I need.

**Comment by tehnrd** [comment]
@mdonnalley I have one more question if you have a moment. I am running the dev command, but I have completely removed the ts-node/tsx references on the shebang line and the script is still running the TS files without issue.

My dev.js file looks like this:

```
#!/usr/bin/env node

import {execute} from '@oclif/core'

await execute({development: true, dir: import.meta.url})
```

Does development mode also compile and execute the TS files automatically? If so, why do the docs even mention needing ts-node or tsx?

**Comment by mdonnalley** [comment]
@tehnrd 

>Does development mode also compile and execute the TS files automatically?

Yes, that's why tsx/ts-node are used. Using node might appear to be working because it's defaulting to the compiled javascript when it fails to compile the typescript.

**Comment by tehnrd** [comment]
@mdonnalley I'm not 100% following, and I appreciate your help digging into this. I have code that is working, but I don't understand why it is working, and sometimes this is worse than when code is not working!

I know screenshots aren't ideal for debugging, but my .ts files are running successfully when I would expect them to fail. ts-node doesn't appear to be used anywhere. I am not compiling the ts code. Is oclif compiling the ts at runtime? If so, can you point me to the code in oclif doing this?

<img width="1563" alt="Screenshot 2024-09-09 at 3 56 01 PM" src="https://github.com/user-attachments/assets/6d4da692-ce5e-4532-95a7-ea95a6b4cdf4">

**Comment by mdonnalley** [comment]
@tehnrd set `DEBUG=*ts-path` in your environment. That will get you all the logs from [this file](https://github.com/oclif/core/blob/main/src/config/ts-path.ts), which is where all this logic lives

**Comment by tehnrd** [comment]
I was about to reply to this thread and say, "looks like this ts logic is inhttps://github.com/oclif/core/blob/main/src/config/ts-path.ts !" I was looking this (oclif) repo,  and wasn't seeing anything doing this runtime conversion, so I was very confused. 

Thanks for the help!
