### ISSUE TITLE
How to: Create global flags

### ISSUE THREAD

**Issue by jercle** [oclif/oclif#907]
Looking at https://oclif.io/blog/2022/01/12/announcing-oclif-v2, I've been trying to figure out how to create global flags. Please provide any assistance you can.

**Comment by mdonnalley** [comment]
@jercle Thanks for creating this issue. We clearly forgot to add a section on that!

I just updated the docs to include it: https://oclif.io/docs/global_flags

**Comment by jercle** [comment]
> @jercle Thanks for creating this issue. We clearly forgot to add a section on that!
> 
> I just updated the docs to include it: https://oclif.io/docs/global_flags

Thanks a heap for this! Thought I was just completely missing it
