### ISSUE TITLE
`oclif readme` for single command CLIs produces wrong output

### ISSUE THREAD

**Issue by felipecrs** [oclif/oclif#915]
Follows-up oclif/core#426

Like this:

## `bindl .`

Downloads and extracts binaries from compressed packages using a config file

```
USAGE
  $ bindl . [--version] [--help] [-c <value>]
FLAGS
  -c, --config=<value>  Path to the config file
  --help                Show CLI help.
  --version             Show CLI version.
DESCRIPTION
  Downloads and extracts binaries from compressed packages using a config file
  The config will be read from any valid config file in the current directory. The configuration file can be defined
  using all the extensions and names accepted by cosmiconfig, such as bindl.config.js
```

_See code: [src/index.ts](https://github.com/felipecrs/bindl/blob/v2.0.0/src/index.ts)_

**Comment by mdonnalley** [comment]
@felipecrs I'm not seeing this on the latest versions of oclif/core (1.9.6) and oclif (3.0.1). Can you confirm that it's fixed? Thanks!

**Comment by felipecrs** [comment]
Nope, it didn't help. Here is the diff between when I reported the issue and now:

https://github.com/felipecrs/bindl/commit/f715170983b5286888dd1302de8f1a2095565207#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
