### ISSUE TITLE
`oclif readme` can not always get the correct command path within the official template

### ISSUE THREAD

**Issue by taujiong** [oclif/oclif#927]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
1. generate a project with command `oclif generate mycli`
2. just run `oclif readme`, and the see code link is targeting to`See code: [dist/commands/hello/index.ts](...)`, just like [the template repo shows](https://github.com/oclif/hello-world/blob/main/README.md?plain=1#L64)

What is the expected behavior?
------------------------------
It is supposed to be `src/commands/hello/index.ts`

According to [the code of readme command](https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L221), the correct command path should be `lib` rather than `dist`.

So, here are two solutions:
1. update the template repo and replace all the releated `dist` with `lib` and ask user not to change it
2. make it a config field, so we can customize

**Comment by Rinse12** [comment]
> make it a config field, so we can customize
Agreed, I think we need to have more customization with the process of generating `readme`

**Comment by mdonnalley** [comment]
This has been fixed by https://github.com/oclif/oclif/pull/1191
