### ISSUE TITLE
oclif generate not compatible with Node 12

### ISSUE THREAD

**Issue by Mordano** [oclif/oclif#938]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
Generate a new CLI with Node version 12.22.12

When generating a new CLI the following error message is popping up:
 
<details><summary>Console output</summary>

```bash

⇒  npx oclif generate mynewcli
~/.nvm/versions/node/v12.22.12/lib/node_modules/oclif/node_modules/@oclif/core/lib/command.js:52
            delete this.globalFlags?.json;
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~/.nvm/versions/node/v12.22.12/lib/node_modules/oclif/node_modules/@oclif/core/lib/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
</details>

I also tried Node versions 14 and 18, with these oclif is running without any problems.
I also tested the behavior on two different machines, it was the same result.
(Going back to a version of @oclif/core before the above line was added -> 1.13.8 produces another error message)

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.
oclif@3.1.2
OS version: Ubuntu 22.04.1 LTS && MacOs 12.5

The CLI generator would generate a new CLI.
CLIs with the current version of @oclif/core@1.13.10 would be executable with Node 12.

**Comment by Mordano** [comment]
Instead of silently closing my issue @mdonnalley , you could at least explain why. Because the oclif README says the following:
`Currently, Node 12+ is supported. We support the [LTS versions](https://nodejs.org/en/about/releases) of Node. You can add the [node](https://www.npmjs.com/package/node) package to your CLI to ensure users are running a specific version of Node.`

I know you probably closed the issue because Node v12 is since April no longer an LTS version. But then it should be updated in the README as well.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by Mordano** [comment]
> Also here working with this issue, and disappointed there's no support

The missing support is reasonable, @snarkeystarkey. Node v12 is end of life and therefore no longer supported. You should upgrade your Node application to the newest LTS version, alone for security reasons.

But nonetheless Oclif should update the README to exclude v12 from the supported version list.

**Comment by snarkeystarkey** [comment]
> 

What's odd is that I got this error when using node 18. I'm installing the twilio CLI. Sounds like I just need to get support from them.

**Comment by Mordano** [comment]
That is really odd. Especially I tested my case with Node v14 as well as with v18 and it worked without any problems in both cases.
I have no experience with the twilio CLI, but I would also suggest to ping them.
Good luck on your journey!
