### ISSUE TITLE
How to make an alias for my command?

### ISSUE THREAD

**Issue by henryhu712** [oclif/oclif#954]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature.

What is the current behavior?
-----------------------------
I can create my command with oclif.

What is the expected behavior?
------------------------------
I want to have an abbreviated name for my command. For example, I create "mycommand" command with oclif. I want "mc" command as an alias for "mycommand".

**Comment by mdonnalley** [comment]
@henryhu712 This feature is documented here: https://oclif.io/docs/aliases

**Comment by henryhu712** [comment]
@mdonnalley The feature seems only for sub commands. I want an alias command for the main command.
