### ISSUE TITLE
oclif-dev publish replacement is not working, doesn't upload all generated tarballs

### ISSUE THREAD

**Issue by shrutiburman** [oclif/oclif#956]
Do you want to request a *feature* or report a *bug*? 
bug
-----------------------------------------------------

What is the current behavior?
`oclif-dev publish` is replaced with `oclif upload tarballs`, which doesn't work as expected. 

Oclif upload doesn't upload the vanilla tarballs, as it used to do [earlier](https://github.com/oclif/dev-cli/blob/ef2ec22438e87fb7107b4c49d2c47584a2222817/src/commands/publish/index.ts#L51) in oclif-dev. 
These are breaking changes that are possibly not well-documented.  

-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.
```
oclif pack tarballs --xz
oclif upload tarballs --xz
```

What is the expected behavior?

The `oclif upload tarballs` command to work as a replacement of `oclif-dev publish`

------------------------------
Please mention your oclif and OS version.
oclif : ^3
OS: [macos-latest](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md) in Github Actions
    System Version: macOS 11.6.8 (20G730)
    Kernel Version: Darwin 20.6.0
    Image Version: 20220906.1

**Comment by riywo** [comment]
You can specify all the targets you need by `-t`.

**Comment by shrutiburman** [comment]
Tried that too, the vanilla tarballs do not get uploaded with the new oclif command. You can see the difference in [oclif](https://github.com/oclif/oclif/blob/007468b2b66fdc9678dc60ff39131e35ce2d1301/src/commands/upload/tarballs.ts#L78) and in [dev-cli](https://github.com/oclif/dev-cli/blob/ef2ec22438e87fb7107b4c49d2c47584a2222817/src/commands/publish/index.ts#L51) codebase.

**Comment by mdonnalley** [comment]
@shrutiburman Is this still an issue for you? If so, could you provide a repository that replicates the issue? Thanks!
