### ISSUE TITLE
Is the v3 release a major release with breaking changes ?

### ISSUE THREAD

**Issue by paolomainardi** [oclif/oclif#957]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Feature.

What is the current behavior?
-----------------------------

I am wondering if the v3 that has been released in the past month should be considered a new major with breaking changes; I cannot find any reference even on the official blog; the latest post talks just about v2: https://oclif.io/blog/

**Comment by mdonnalley** [comment]
@paolomainardi v3 introduced now supports Apple M1 installers. It was considered a breaking change because it required that we change the resulting package name for macos installers.

You can see more here: https://github.com/oclif/oclif/releases/tag/v3.0.0
