### ISSUE TITLE
Installing packed tarball - node not found

### ISSUE THREAD

**Issue by tilersmyth** [oclif/oclif#959]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug (i think)

What is the current behavior?
-----------------------------
On Linux (with no Node installation), installing packed tarball ` curl https://[my-bucket].s3.amazonaws.com/versions/latest/[file-name]-linux-arm.tar.gz | tar zxf -` and trying to run with `./bin/run [cmd]` but getting the error `/usr/bin/env: ‘node’: No such file or directory`.

Per the [documentation](https://oclif.io/docs/releasing#standalone-tarballs), it seems like this should work without installing Node: 

> These include the node binary so the user does not have to already have node installed to use the CLI

What is the expected behavior?
------------------------------
`./bin/run [cmd]` works properly with Node installed but hoping to run my CLI on a Node-less system.

OS: `Ubuntu 22.04`, Oclif: `v3.2.2`

**Comment by RodEsp** [comment]
`./bin/run` is a javascript file so you will need node to run it. You shouldn't try to run that directly, run the `./bin/cliName` script instead, or `./bin/cliName.cmd` on Windows.

**Comment by tilersmyth** [comment]
Thanks @RodEsp. When running `./bin/cliName` I get "cannot execute binary file: Exec format error". Any ideas?

**Comment by RodEsp** [comment]
@tilersmyth what does that file look like? It should be a bash file that looks something like [this](https://cs.github.com/oclif/oclif/blob/007468b2b66fdc9678dc60ff39131e35ce2d1301/src/tarballs/bin.ts#L41-L85).

Usually that error is something your terminal throws when you're trying to execute a binary file that was built for a different OS or architecture.
