### ISSUE TITLE
Package with Deno

### ISSUE THREAD

**Issue by AndresPrez** [oclif/oclif#968]
Feature Request
-----------------------------------------------------

What is the current behavior?
-----------------------------
`oclif package` currently works for packaging Node CLIs. 

What is the expected behavior?
------------------------------
It would be awesome if there could be support for packaging CLIs projects built on Deno.

**Comment by AndresPrez** [comment]
Moved to https://github.com/oclif/core/issues/503

**Comment by ataylorme** [comment]
For anyone coming across this give [Cliffy](https://cliffy.io/) a try
