### ISSUE TITLE
http://oclif.io/docs/introduction is returning a 404

### ISSUE THREAD

**Issue by toymachiner62** [oclif/oclif#970]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
This page is returning a 404

What is the expected behavior?
------------------------------
Some getting started instructions would be available

**Comment by mshanemc** [comment]
yep, I was doing some migration stuff that caused github to un-validate our custom domain (oclif.io).

In the meantime, you can use `oclif.github.io` like https://oclif.github.io/docs/introduction
