### ISSUE TITLE
axios package is undefined in production

### ISSUE THREAD

**Issue by heesungjang** [oclif/oclif#994]
Hi, I am new to oclif and was building cli tool for revalidating my blog CDN cache. 

I am using axios for http request, however, it only works locally.

imported axios package returns undefined in production. Any help would be very appreciated!! thanks!!

**Comment by MartinDawson** [comment]
Just using pure js:

```js
import * as axios from 'axios';
```

If you use typescript then do this:

tsconfig.json needs this:

```ts
  "ts-node": {
    "files": true
  },
```

```ts
import * as axios from 'axios';
```

And in your src folder add declarations.d.ts:

```ts
declare module 'axios' {
  import axios from 'axios/index';

  export = axios;
}
```
