### ISSUE TITLE
Global base class?

### ISSUE THREAD

**Issue by cyberwombat** [oclif/oclif#996]
Would it be possible to either have all plugins use my base class (perhaps defined in `package.json` like help is or some way to have a hook to translate/reformat things like description? For example - translation need aside - i'd like to have consistent `descriptions` but the various official plugins use a mix and match of capitalization and periods which makes my help look rather unprofessional but have no way to fix.

**Comment by mdonnalley** [comment]
We have a section in our docs that goes over base command classes: https://oclif.io/docs/base_class

For manipulating the `description`, I believe could do something like this:

```typescript

import {Command, Flags, Interfaces} from '@oclif/core'

export type Flags<T extends typeof Command> = Interfaces.InferredFlags<typeof BaseCommand['globalFlags'] & T['flags']>

export abstract class BaseCommand<T extends typeof Command> extends Command {
  protected static _description: string;

  public static get description(): string {
    // do custom logic to the description
    return this._description
  }

  protected flags!: Flags<T>

  public async init(): Promise<void> {
    await super.init()
    const {flags} = await this.parse(this.constructor as Interfaces.Command.Class)
    this.flags = flags
  }
}

export default class MyCommand extends BaseCommand<typeof MyCommand> {
  static _description = 'This is a child class that extends BaseCommand and translates the description'
}

```

**Comment by cyberwombat** [comment]
@mdonnalley Perhaps I was not clear - how do I use a global base class for everything? like plugins? I already have a base class but there seems to be no way to define it globally for plugins to use. For example: `plugins-help` uses a capitalization/period and `plugins-autocomplete` uses a lowercase/no period. Besides forking the plugin how would I fix this?

**Comment by mdonnalley** [comment]
@cyberwombat I understand now. To answer the broader question, there is currently no way to define a global base command class that will apply to all installed plugins

But if all you're concerned about is modifying descriptions in the help output then implementing a custom help class will get you what you need. We have this documented [here](https://oclif.io/docs/help_classes) but, unfortunately, it doesn't go over more advanced use cases like yours. 

Taking a quick glance at the code, the `CommandHelp` class is responsible for rendering the descriptions: https://github.com/oclif/core/blob/59e6f5151932e62de4cf21ba83ba37b720b6a451/src/help/command.ts#L105. So your help class will need to override that. You can see an example of how we do that for ourselves here: https://github.com/salesforcecli/cli/blob/main/src/help/sfHelp.ts

**Comment by cyberwombat** [comment]
Ah excellent - that's what I was looking for!
