### ISSUE TITLE
unclear docs on 'single' / 'simple' CLI usage

### ISSUE THREAD

**Issue by techieshark** [oclif/oclif#998]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Docs bug

What is the current behavior?
-----------------------------
Not clear how to use `oclif generate` to make a a CLI with just one top level command.

What is the expected behavior?
------------------------------
Somewhere it should be documented how to generate a CLI that has just one (top level) command that takes some options.

For example, I'm hoping to do 

```
$ oclif generate ...
```

and then I'd expect that src/index.ts says

```
export {run} from '@oclif/core' // or something like this, as it does now
```

but instead of the `commands/` directory, we would have ___ (what? this is where I'm unclear)

**Comment by mdonnalley** [comment]
@techieshark This use case was addressed in https://github.com/oclif/core/pull/426. But I agree that the docs are not clear about it. I'll make a note to update the docs this week
